### ISSUE TITLE
Account Switching Between Sovereign/Non-Sovereign Authorities is Unsupported

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1025]
See [`adal/#1005#pullrequestreview-73249881`](https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1005#pullrequestreview-73249881)

Per @heidijinxujia 

> There is a "bug" or "by design", after signing in a sov test account, when we try to sign in with our msdevex test account, it will not able to find the tenant and the sign-in failed. This is because we keep the auth context and updated the authority after the sov test account sign-in, regardless with which authority UI passed in. My previous commit is only a temp support for sov cloud test. I think we need to fix this.

**Comment by nazukj** [comment]
@iambmelt to sync with @addev-ashish and close accordingly.

**Comment by iambmelt** [comment]
By design

/cc @nazukj @addev-ashish @heidijinxujia
