### ISSUE TITLE
resource and loginHint

### ISSUE THREAD

**Issue by MansoorJafari** [AzureAD/azure-activedirectory-library-for-android#1035]
Hi

what is the resource and loginHint?

**Comment by iambmelt** [comment]
Hi @MansoorJafari 

From [the docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code):

**login_hint**
> You can use this parameter to pre-fill the username and email address field of the sign-in page for the user, if you know the username ahead of time. Often, apps use this parameter during re-authentication, after already extracting the username from an earlier sign-in by using the preferred_username claim.

**resource**
> The App ID URI of the web API (secured resource). To find the App ID URI of the web API, in the Azure Portal, click Active Directory, click the directory, click the application and then click Configure.

At a high-level, the resource is the 'thing' you want to authorize users for. If you need access to a user's files in SharePoint, then SharePoint is the resource. If you want the user to be able to make requests to the Microsoft Graph, then the Microsoft Graph is your resource. These are generally identified either by a GUID or a URL.

**Comment by MansoorJafari** [comment]
Thanks.
I'm not using azure But, I'm using active directory local.
Can you help me to right this section??
