### ISSUE TITLE
IdP (issuer) never gets parsed out of the ID token

### ISSUE THREAD

**Issue by GTValentine** [AzureAD/azure-activedirectory-library-for-android#1043]
When parsing ID tokens, we are searching for the "idp" field in the token (ID_TOKEN_IDENTITY_PROVIDER) and assume that it keys the identity provider. The corresponding value can later be returned by the `getIdentityProvider()` function.

However, it seems that the key doesn't exist. I am not seeing it in a real ID token I got. I am not seeing it documented anywhere on the Internet. And [this article](https://connect2id.com/blog/how-to-validate-an-openid-connect-id-token) say that it's actually the "iss" field which contains the issuer (the IdP): `Issuer (iss) and audience (aud) — specify the IdP that created the ID token and who it is intended for (the client_id)`.

Moreover, the issuer will be in this form: 
`"iss"`: `"https://sts.windows.net/3371b64f-3ea4-4cd8-8c9f-ca95e77512cf/"`, so it contains the tenant ID, and is therefore PII, and should be hashed for telemetry purposes in `APIEvent::setIdToken`, or at least truncated.

**Comment by GTValentine** [comment]
Just check with @kpanwar, he says "idp" may be an actual optional home-cooked field. Looking into it. Closing for now.

**Comment by iambmelt** [comment]
Clearing `February2018` milestone /cc @nazukj @addev-ashish

**Comment by iambmelt** [comment]
Closing due to age; outdated
