### ISSUE TITLE
Telemetry - reporting authority correctly

### ISSUE THREAD

**Issue by GTValentine** [AzureAD/azure-activedirectory-library-for-android#1045]
Authority is being reported in two different places: in httpEvent::SetHttpPath and in ApiEvent::SetAuthority. The first one reports any given authority, but the second one checks that it's a whitelisted authority first. Both places should perform this check.

Also, we need to make sure that we only report AAD authorities, not arbitrary ADFS authorities.

Also, HttpEvent shouldn't strip off the tenant from the http path.

**Comment by nazukj** [comment]
@ashish to provide comments and close

**Comment by addev-ashish** [comment]
On second thought @iambmelt and I think that this can serve as the extensible point. Where every http event irrespective of whether its to the authority or not reports it. 
The stripping of tenant was in the original spec, i think we can leave it in.
