### ISSUE TITLE
Could be breaking: Strictly enforce that the Context used to initialize AuthenticationContext is an Application and not an Activity

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1056]
[These constructors](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L87-L131) advise users to supply the `AuthenticationContext` with an application `Context` -- to ensure that user explicitly **do not** supply an Activity, we could do one of a few things:
- Change the constructor parameter to accept `Application` (If users have integrated ADAL correctly, this shouldn't be a breaking change
- Invoke `getApplicationContext()` on the supplied `context` parameter and do not trust that users have supplied the proper `Context`

Why should users not supply an `Activity`? Read more [here](https://android-developers.googleblog.com/2009/01/avoiding-memory-leaks.html).

/cc @shoatman

**Comment by piqiums** [comment]
using Activity context might cause mem leak. The Application context has the same lifycycle with the app and it's a singleton. so we don't need to worry about it. I will make this change when I have time.

**Comment by iambmelt** [comment]
Awesome, thank you @piqiums! 😄

**Comment by piqiums** [comment]
I've prefer that second solution. In this way, we could solve this issue without any change from others.

```
Invoke getApplicationContext() on the supplied context parameter and do not trust that users have supplied the proper Context
```

**Comment by iambmelt** [comment]
This is complete. Resolving
