### ISSUE TITLE
ADFS & Common Library

### ISSUE THREAD

**Issue by shoatman** [AzureAD/azure-activedirectory-library-for-android#1067]
As far as I know ADFS 3 (2012 R2) doesn't support using multi-resource refresh tokens.  As a result there is no way to use the refresh token as an SSO artifact.  Hence no need write the refresh token into the MSAL cache.  

So for the moment we should have the Save Token logic use the existing ADAL Cache implementation and not the unified/common cache.

**Comment by iambmelt** [comment]
Closed via #1189 /cc @shoatman
