### ISSUE TITLE
Ask: Expose a method that helps clients determine if current tenant is home tenant

### ISSUE THREAD

**Issue by nazukj** [AzureAD/azure-activedirectory-library-for-android#1092]
Currently, there is no way to know if the current tenant is the user's home tenant or not. Expose a method to provide this information

**Comment by iambmelt** [comment]
Clearing `February2018` milestone /cc @nazukj @addev-ashish

**Comment by iambmelt** [comment]
Not adding new features any longer. Closing /cc @hamiltonha
