### ISSUE TITLE
Certificate auth fails with ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by mpaliath** [AzureAD/azure-activedirectory-library-for-android#1105]
When trying to authenticate our app against an federated office 365 account using certificate based auth, I get an error as soon as I select the certificate. Looking at ADAL logs, I see the below error. Note that I am able to successfully sign in with iOS ADAL.

Error info:Error Code:-6 net::ERR_CONNECTION_RESET for requestId: 1032515341 CorrelationId: a11a85a3-741e-48a8-90d7-7809a2f25e84 ver:1.13.3-null

Full logs below
[ADAL Logs.txt](https://github.com/AzureAD/azure-activedirectory-library-for-android/files/1657362/ADAL.Logs.txt)

**Comment by piqiums** [comment]
Hi, @mpaliath   thanks for reporting this issue. Out of the information you provided, I think this might be related with the network connectivity. Were the iOS device and the Android device using the same network connectivity? And is it still happening on the Android device now? If it still happens, does it happen every time? If not, how many time this would happen out of 10 times trying.  thanks

**Comment by mpaliath** [comment]
Hi @piqiums 
Yes this happens every time and I see the same happening when trying to login with the browser too. It seems the Android v5.1.2 doesn't support certificates for auth? Tried it on a different device on v7.x and this worked fine against the same environment. Is that expected? Do we know which versions are supported for CBA?

**Comment by piqiums** [comment]
@mpaliath  thanks for the update. Would you try to remove the cached certificate and try it again? thanks

**Comment by mpaliath** [comment]
I tried removing the cached certificate and using a copy of the certificate. Neither works.
