### ISSUE TITLE
Bound Service: broker-based sign in failed with error BROKER_AUTHENTICATOR_NOT_RESPONDING

### ISSUE THREAD

**Issue by yuliwa** [AzureAD/azure-activedirectory-library-for-android#1107]
ADAL would sometimes keep throwing the error  BROKER_AUTHENTICATOR_NOT_RESPONDING  and says "Didn't receive the activity to launch from broker: Failed to bind the service in broker app"

**Comment by demoritas** [comment]
to add to this:

this happens for us when we try to get a token while in background.
mostly on Android 8.X
mostly on Samsung and Huawai devices

**Comment by nazukj** [comment]
Please provide us with complete ADAL and Broker logs. Thanks.

**Comment by demoritas** [comment]
Sadly I cannot do that since we do not log them in telemetry and while this happens for Users we are not able to reproduce it on the devices available onsite

**Comment by iambmelt** [comment]
@yuliwa @demoritas -- From investigation/reports from other partners + internal testing. We were able to reproduce this issue by instantiating the `AuthenticationContext` with an `Activity` context that has been backgrounded or has been torn-down by the Android Activity Lifecycle.

Please ensure that your `AuthenticationContext` is initialized using an Application `Context` -- when making calls to `acquireToken` pass the current foregrounded `Activity` as a parameter.
