### ISSUE TITLE
Ask: TLS 1.2 support for Android <= v4.4

### ISSUE THREAD

**Issue by kubo-uchida** [AzureAD/azure-activedirectory-library-for-android#1111]
[Disabling TLS 1.0 and 1.1 in Microsoft Office 365](https://support.microsoft.com/en-us/help/4057306/preparing-for-tls-1-2-in-office-365) was annouced in Dec 2017, and sign-in pages shown in ADAL-for-android seems to be included in this change.
However, [default web browsers (and maybe webviews) of Android  <= v4.4 are not compatible with TLS 1.2  encryption](https://qsportal.atlassian.net/wiki/spaces/DOC/pages/3571715/TLSv1.2+Browser+Compatibility).

I'm afraid that we will not be able to show Microsoft sign-in pages with Android  <= v4.4 after May 1, 2018.
Does ADAL-for-android work with TLS 1.2 and Android  <= v4.4?
If not, is there any way to enable TLS 1.2 with webview included in ADAL-for-android ?

Thanks in advance.

**Comment by iambmelt** [comment]
Hi @kubo-uchida -- Clients which do not support TLS 1.2 will fallback to [`MS-PKAP`](https://msdn.microsoft.com/en-us/library/mt223996.aspx)

To enable this scenario, a [user-agent extension](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/9ee4f32be6f88e7b8e831aef3379d2a14e9311f9/adal/src/main/java/com/microsoft/aad/adal/AuthenticationConstants.java#L436-L437) is placed in the request headers sent to your designated authority. AAD/ADFS will identify clients not supporting TLS 1.2 by this value, and will negotiate the exchange of tokens without its usage.

**Comment by HiroshiYoshino** [comment]
@iambmelt , thank you for sharing background.
After all, we could use ADAL-for-android on Android <=4.4 in the same usage as before disabling TLS 1.0 and 1.1 in Office 365 ?

**Comment by iambmelt** [comment]
Hi @HiroshiYoshino 

Yes, the expectation is that any version of Android running API 14+ (ICS `4.0.1`) should continue to work
