### ISSUE TITLE
Resiliency fix to not crash: Null Pointer Exception at isMultipleRTsMatchingGivenAppAndResource

### ISSUE THREAD

**Issue by ravarora** [AzureAD/azure-activedirectory-library-for-android#1115]
<ul>
  <li>Expected behavior</li>
         While requesting to acquire token from ADAL library when the session is expired, User is asked to log in. 
  <li>Actual behavior</li>
         App crashes with a null pointer exception. 
  <li>Steps to reproduce the problem</li>
         User Signs in to Office 365 account using ADAL. The session expires for the user after 15 days. User Taps to Sign in again. App crashes. 
        We have received this crash from one of our customers and This is the only information we have. Th
  <li>Specifications like the version of the library, operating system etc</li>
         Adal Library 1.13.3
         Device Google Pixel. Android 8.1.0
  <li>Relevant logs and traces</li>
        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
	at com.microsoft.aad.adal.TokenCacheAccessor.isMultipleRTsMatchingGivenAppAndResource(TokenCacheAccessor.java:309)
	at com.microsoft.aad.adal.TokenCacheAccessor.throwIfMultipleATExisted(TokenCacheAccessor.java:424)
	at com.microsoft.aad.adal.TokenCacheAccessor.getATFromCache(TokenCacheAccessor.java:87)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(AcquireTokenSilentHandler.java:101)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(AcquireTokenRequest.java:427)
	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(AcquireTokenRequest.java:391)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:347)
	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:327)
	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:46)
	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
</ul>

**Comment by ravarora** [comment]
More detailed Logs

02-08 16:25:42.631 12872 12872 V AuthenticationContext: 2018-02-08 10:55:42-null-Broker redirectUri:msauth://com.microsoft.mobile.polymer/fcg80qvoM1YMKJZibjBwQcDfOno%3D packagename:com.microsoft.mobile.polymer signatureDigest:fcg80qvoM1YMKJZibjBwQcDfOno= ver:1.13.3
02-08 16:25:42.633 12872 12872 V BrokerProxy: 2018-02-08 10:55:42-null-Device runs on 23 and above, skip the check for 22 and below. ver:1.13.3
02-08 16:25:42.639 12872 12872 V AcquireTokenRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Sending async task from thread:12872 ver:1.13.3
02-08 16:25:42.640 12872 18295 V AcquireTokenRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Running task in thread:18295 ver:1.13.3
02-08 16:25:42.641 12872 18295 V AcquireTokenRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Start validating authority ver:1.13.3
02-08 16:25:42.646 12872 18295 V Discovery: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Sending discovery request to:https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2F%252Fcommon%252Foauth2%252Fauthorize ver:1.13.3
02-08 16:25:42.647 12872 18295 V WebRequestHandler: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-WebRequestHandler thread18295 ver:1.13.3
02-08 16:25:42.648 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-HttpWebRequest send thread:18295 ver:1.13.3
02-08 16:25:42.648 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-HttpWebRequest setupConnection thread:18295 ver:1.13.3
02-08 16:25:42.649 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: return-client-request-id ver:1.13.3
02-08 16:25:42.649 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: Accept ver:1.13.3
02-08 16:25:42.650 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: client-request-id ver:1.13.3
02-08 16:25:42.650 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: Host ver:1.13.3
02-08 16:25:42.650 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: x-client-Ver ver:1.13.3
02-08 16:25:42.650 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: x-client-DM ver:1.13.3
02-08 16:25:42.651 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: x-client-SKU ver:1.13.3
02-08 16:25:42.651 12872 18295 V HttpWebRequest: 2018-02-08 10:55:42-646cde5c-4609-4e6e-8622-eeef8309f866-Setting header: x-client-OS ver:1.13.3
02-08 16:25:44.319 12872 18295 V HttpWebRequest: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Response is received ver:1.13.3
02-08 16:25:44.324 12872 18295 V AcquireTokenRequest: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-The passed in authority is valid. ver:1.13.3
02-08 16:25:44.349 12872 18295 V AuthenticationContext: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Broker redirectUri:msauth://com.microsoft.mobile.polymer/fcg80qvoM1YMKJZibjBwQcDfOno%3D packagename:com.microsoft.mobile.polymer signatureDigest:fcg80qvoM1YMKJZibjBwQcDfOno= ver:1.13.3
02-08 16:25:44.353 12872 18295 V AcquireTokenRequest:verifyBrokerRedirectUri: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-The broker redirect URI is valid: msauth://com.microsoft.mobile.polymer/fcg80qvoM1YMKJZibjBwQcDfOno%3D ver:1.13.3
02-08 16:25:44.354 12872 18295 V AcquireTokenRequest: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Try to acquire token silently, return valid AT or use RT in the cache. ver:1.13.3
02-08 16:25:44.355 12872 18295 V AcquireTokenRequest: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Try to silently get token from local cache. ver:1.13.3
02-08 16:25:44.357 12872 18295 V DefaultTokenCacheStore: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Started to initialize storage helper ver:1.13.3
02-08 16:25:44.358 12872 18295 V DefaultTokenCacheStore: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished to initialize storage helper ver:1.13.3
02-08 16:25:44.358 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.359 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.378 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Reading Key entry ver:1.13.3
02-08 16:25:44.417 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Reading SecretKey ver:1.13.3
02-08 16:25:44.420 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Reading key data from a file ver:1.13.3
02-08 16:25:44.582 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished reading SecretKey ver:1.13.3
02-08 16:25:44.592 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.594 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.594 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.595 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.595 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.595 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.596 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.596 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.597 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.597 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.598 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.598 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.598 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.599 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.599 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.600 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.601 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.601 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.602 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.602 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.602 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.603 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.603 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Starting decryption ver:1.13.3
02-08 16:25:44.604 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Encrypt version:A001 ver:1.13.3
02-08 16:25:44.604 12872 18295 V StorageHelper: 2018-02-08 10:55:44-646cde5c-4609-4e6e-8622-eeef8309f866-Finished decryption ver:1.13.3
02-08 16:25:44.614 12872 18295 E AndroidRuntime: FATAL EXCEPTION: pool-34-thread-1
02-08 16:25:44.614 12872 18295 E AndroidRuntime: Process: com.microsoft.mobile.polymer, PID: 12872
02-08 16:25:44.614 12872 18295 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.isMultipleRTsMatchingGivenAppAndResource(SourceFile:309)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.throwIfMultipleATExisted(SourceFile:424)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.getATFromCache(SourceFile:87)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(SourceFile:101)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(SourceFile:427)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(SourceFile:391)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(SourceFile:347)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(SourceFile:327)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(SourceFile:46)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(SourceFile:109)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-08 16:25:44.614 12872 18295 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

**Comment by ravarora** [comment]
Update: Other Apps for user Like Word and OneNote are working fine. They dont see a crash. Is there any workaround? User had Authenticator installed and  tried uninstalling the authenticator and tried login again. Still crash persists

**Comment by heidijinxujia** [comment]
@ravarora Has this crash only happened on one user/device so far?

**Comment by heidijinxujia** [comment]
Could not get the repro on the test device. The AT is successfully refreshed. 

According to the logs, the exception was thrown because equalsIgnoreCase was called on a  null object, that is either the passed in clientId or resource string is null. Could you send me the full logs of the repro so that we could check on the passed-in parameters.

Thanks,
Heidi

**Comment by iambmelt** [comment]
Closing due to age, inactivity -- please reopen if this issue persists with latest release of the library
