### ISSUE TITLE
Acquiring token sometimes takes around 25-30 seconds

### ISSUE THREAD

**Issue by somdas** [AzureAD/azure-activedirectory-library-for-android#1120]
We are using the library in Outlook app. When the token expires and we call acquireTokenSilentAsync it takes around 25-30 seconds. This happens only sometimes. Is the  behaviour expected?

[logcat.txt](https://github.com/AzureAD/azure-activedirectory-library-for-android/files/1730661/logcat.txt)

<ul>
  <li>Expected behavior</li> Acquiring the token should take few seconds only.
  <li>Actual behavior</li> Sometimes it takes around 25-30 seconds
  <li>Steps to reproduce the problem</li> We should look for scenarios when the token expires for the outlook app and then we try to acquire the new token.
  <li>Specifications like the version of the library, operating system etc</li> Version 1.13.3 for Android
  <li>Relevant logs and traces</li> Attached
</ul>

**Comment by nazukj** [comment]
@addev-ashish any updates on this issue on your end?

**Comment by addev-ashish** [comment]
We checked on the logs and followed up on email, the logs do not show a 25-30 second delay in response.
