### ISSUE TITLE
onActivityResult BROWSER_FLOW data is null.... ADALError.ON_ACTIVITY_RESULT_INTENT_NULL

### ISSUE THREAD

**Issue by l4ces** [AzureAD/azure-activedirectory-library-for-android#1121]
With singleInstance launchMode - onActivityResult BROWSER_FLOW data is null.... ADALError.ON_ACTIVITY_RESULT_INTENT_NULL

<ul>
  <li>Expected behavior</li>
Expecting Intent passed in onActivityResult to contain a non-null intent when the client application uses a launchMode set to singleInstance and for the AuthenticationActivity to succeed after entering credentials.  With launchMode property set to singleTask, the Intent parameter is valid and the rest of the AuthenticationActivity succeeds (after entering credentials).

  <li>Actual behavior</li>
BROWSER_FLOW data is null when the launch mode is set to singleInstance.

  <li>Steps to reproduce the problem</li>
Set launchMode to singleInstance in your application and request a token.

  <li>Specifications like the version of the library, operating system etc</li>
Adal lib version 1.1.16 and 1.2.2.
  <li>Relevant logs and traces</li>
02-16 11:15:21.779 6691-6691/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-Sending async task from thread:6691 ver:1.2.2
02-16 11:15:21.802 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-Running task in thread:6953 ver:1.2.2
02-16 11:15:21.826 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-Token request started ver:1.2.2
02-16 11:15:21.880 6691-6953/com.my.app.application V/AcquireTokenSilentHandler: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-No valid access token exists, try with refresh token. ver:1.2.2
02-16 11:15:21.912 6691-6953/com.my.app.application V/AcquireTokenSilentHandler: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-Regular token cache entry does not exist, try with MRRT. ver:1.2.2
02-16 11:15:21.943 6691-6953/com.my.app.application V/AcquireTokenSilentHandler: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-MRRT token does not exist, try with FRT ver:1.2.2
02-16 11:15:21.966 6691-6953/com.my.app.application V/AcquireTokenSilentHandler: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-FRT cache item does not exist, fall back to try MRRT. ver:1.2.2
02-16 11:15:21.982 6691-6953/com.my.app.application V/AcquireTokenSilentHandler: 2018-02-16 16:15:21-3202a09e-2d33-4543-8359-1bd10d7b7904-Send request to use MRRT for new AT. ver:1.2.2
02-16 11:15:22.005 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-3202a09e-2d33-4543-8359-1bd10d7b7904-No token returned for silent flow or promptbehavior is set to always. ver:1.2.2
02-16 11:15:22.045 6691-6953/com.my.app.application E/AuthenticationContext: AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED:2018-02-16 16:15:22-3202a09e-2d33-4543-8359-1bd10d7b7904-Prompt is not allowed and failed to get token: ver:1.2.2 Request authority:https://login.windows.net/common resource:https://webdir3a.online.lync.com clientid:d3590ed6-52b3-4102-aeff-aad2292ab01c 
02-16 11:15:22.068 6691-6691/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-b2b1bced-7311-434e-b0b5-435ca30c76ca-Sending async task from thread:6691 ver:1.2.2
02-16 11:15:22.099 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-b2b1bced-7311-434e-b0b5-435ca30c76ca-Running task in thread:6953 ver:1.2.2
02-16 11:15:22.123 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-b2b1bced-7311-434e-b0b5-435ca30c76ca-Token request started ver:1.2.2
02-16 11:15:22.130 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-b2b1bced-7311-434e-b0b5-435ca30c76ca-No token returned for silent flow or promptbehavior is set to always. ver:1.2.2
02-16 11:15:22.162 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-b2b1bced-7311-434e-b0b5-435ca30c76ca-Starting Authentication Activity with callback:1112680576 ver:1.2.2
02-16 11:15:22.177 6691-6953/com.my.app.application V/AuthenticationContext: 2018-02-16 16:15:22-b2b1bced-7311-434e-b0b5-435ca30c76ca-Put waiting request: 1112680576 CorrelationId: e6faba85-6348-4547-ae18-d52f38be6417 ver:1.2.2
02-16 11:16:52.655 6691-6691/com.my.app.application D/MainActivitytid: 1:  onPause
02-16 11:16:52.655 6691-6691/com.my.app.application D/MainActivitytid: 1:  onActivityResult for OAuth requestCode = 1001resultCode = 0
02-16 11:16:52.655 6691-6691/com.my.app.application E/MainActivitytid: 1: Data is null
02-16 11:22:07.874 6691-6691/? E/AuthenticationContext: ON_ACTIVITY_RESULT_INTENT_NULL:2018-02-16 16:22:07-b2b1bced-7311-434e-b0b5-435ca30c76ca-onActivityResult BROWSER_FLOW data is null. ver:1.2.2 
</ul>

<b>Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.</b>

For <b>privacy/security</b> issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>

**Comment by iambmelt** [comment]
Closing due to age; please reopen if you see this issue with the latest version of the lib
