### ISSUE TITLE
Add UI Automation support to Unified Dev

### ISSUE THREAD

**Issue by shoatman** [AzureAD/azure-activedirectory-library-for-android#1127]
The following are needed:

- Upgrade to leverage Gradle 4.1 and Gradle Plugin 3.0 in order to support build variants
- Add build variants for the automation app for ADAL release, MSAL release and ADAL dev to support regression testing
- Rollback some API breaking changes (we still want these, but will need to come later)

**Comment by heidijinxujia** [comment]
@shoatman I am probably lack of context here. Have we already decided to use Espresso instead of others for automation?

**Comment by iambmelt** [comment]
Automation has graduated `dev`, rendering this issue outdated.

Closing, as noop here
