### ISSUE TITLE
authenticationContext.acquireToken() can throw a WindowManager$BadTokenException if the context passed during construction is not an Activity

### ISSUE THREAD

**Issue by murki** [AzureAD/azure-activedirectory-library-for-android#1136]
- **Expected behavior:** The documentation for the AuthenticationContext constructor has [this to say about the context parameter](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/38cf008f0bd7916df7b50ffd5f14ed05d82a68e9/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L91-L93): `appContext: It needs to have handle to the Context to use the SharedPreferences as a Default cache storage. It does not need to be activity.` 

- **Actual behavior:** If you instantiate an `AuthenticationContext` and pass an application context, and then attempt to call `acquireToken(myResource, myClientId, myRedirectUri, myLoginHint, PromptBehavior.FORCE_PROMPT, myExtraQueryParameters, myAuthenticationCallback)` then a `WindowManager$BadTokenException` will be thrown

>android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application

This makes sense since it's not possible to create a Dialog with only an Application, since it has no associated parent window, but clearly the documentation is wrong. This is [the offending line](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d50ec801109a9051c9aeac30087c756135c945db/adal/src/main/java/com/microsoft/aad/adal/AuthenticationDialog.java#L83).

**Comment by iambmelt** [comment]
Related: #1047

**Comment by iambmelt** [comment]
@danieldobalian It looks like there's some opportunity to improve the developer experience here through documentation. Maybe something we consider patching in a future sprint or whenever there are spare cycles?

I think the issue outlined in #1047 may be slightly more complicated than documentation alone can fix, but this issue (#1136) seems at least _partially_ resolvable in this way

**Comment by nazukj** [comment]
This is an opportunity for us to improve our developer experience by not accepting incorrect context

**Comment by iambmelt** [comment]
Closing as no-op as library is crit-fixes only
