### ISSUE TITLE
Null check missing for PromptBehavior... which is nullable

### ISSUE THREAD

**Issue by shoatman** [AzureAD/azure-activedirectory-library-for-android#1138]
https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/21afcaf50b495fe1b63553963af6a5f93e50a4a7/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L595

There are a few places where this code appears.

**Comment by iambmelt** [comment]
Per offline w/ @shoatman 

>We should investigate how this code would have behaved in the ADAL releases pre-telemetry: if this was formerly an acceptable value that would have fallen back on a default (specified either by the client or the server) we should make our fix consistent with the previous behavior.

/cc @addev-ashish
