### ISSUE TITLE
DEVELOPER_REDIRECTURI_INVALID

### ISSUE THREAD

**Issue by mores** [AzureAD/azure-activedirectory-library-for-android#1139]
I am trying the Quick Start....

./gradlew installDebug

'hello' did not show up on the android device, but 'Fancy ADAL Test App' did.

When I try to 'AQUIRETOKEN' I get:
`03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.request_id:910c1e6b-4a3e-4d78-b08e-a4c5c1a54f20
03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.api_error_code:DEVELOPER_REDIRECTURI_INVALID
03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.device_id:akubWTkC8z0Ff/mWJ+plvTXGhFkhtbUi1cg5TjiQSIU=
03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.api_id:115
03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.authority_type:aad
03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.application_name:com.microsoft.aad.adal.userappwithbroker
03-09 16:23:30.725  5846  5914 E SampleTelemetry: Microsoft.ADAL.application_version:1.0
03-09 16:23:30.726  5846  5914 E SampleTelemetry: Microsoft.ADAL.authority_validation_status:yes
03-09 16:23:30.726  5846  5914 E SampleTelemetry: Microsoft.ADAL.response_time:28
03-09 16:23:30.726  5846  5914 E SampleTelemetry: Microsoft.ADAL.client_id:b92e0ba5-f86e-4411-8e18-6b5f928d968a
03-09 16:23:30.726  5846  5914 E SampleTelemetry: Microsoft.ADAL.is_successful:false
03-09 16:23:30.726  5846  5914 E SampleTelemetry: Microsoft.ADAL.correlation_id:e0ce9485-1df2-4923-961d-3c403b00d5f3
03-09 16:23:30.726  5846  5914 E SampleTelemetry: Microsoft.ADAL.prompt_behavior:Auto
03-09 16:23:30.727  5846  5913 V UserAppWithBroker.Main: MainActivity userapp:The base64 url encoded signature component of the redirect uri does not match the expected value.
`
The android device is currently logged in with Outlook.....

**Comment by addev-ashish** [comment]
Hi @mores 
You will need to change the RedirectUri and other constant in https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/userappwithbroker/src/main/java/com/microsoft/aad/adal/example/userappwithbroker/Constants.java to match your tenant setup

**Comment by mores** [comment]
I think https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md should be updated with this instruction under QuickStart....are you going to do that or should I make a merge request ?

**Comment by addev-ashish** [comment]
@mores we would appreciate your contribution.
