### ISSUE TITLE
Telemetry: AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED hides valid server errors like time_out

### ISSUE THREAD

**Issue by nazukj** [AzureAD/azure-activedirectory-library-for-android#1140]
There are several code paths where AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED is not surfacing the underlying web error which is leading to this exception. Since this is a top error in silent calls for ADAL, getting detailed information here is essential.

**Comment by lingzlu** [comment]
any update on this bug?

**Comment by iambmelt** [comment]
Closing as no-op as library is crit-fixes only
