### ISSUE TITLE
Telemetry: Additional information needs to be provided around BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN to disambiguate scenarios

### ISSUE THREAD

**Issue by nazukj** [AzureAD/azure-activedirectory-library-for-android#1141]
Currently, when authentication through broker fails, we get a generic telemetry event "BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN" which does not contain specific information around what failed. We need to add extra information for this call to understand reasons why auth with broker fails.

This is a top error in telemetry for silent calls.

AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED is the top error which also requires more information

**Comment by iambmelt** [comment]
Closing as no-op as library is crit-fixes only
