### ISSUE TITLE
onError called with null exception

### ISSUE THREAD

**Issue by sixpi** [AzureAD/azure-activedirectory-library-for-android#1148]
Please ensure the following information is provided when logging a new issue:

* Expected behavior
We are calling `AuthenticationContext.acquireToken()` or `acquireTokenSilentAsync()` from our code, and when the call fails we get our `onError()` method called with the exception that caused the failure.
*Actual behavior
`onError()` is called with a `null` exception.
*Steps to reproduce the problem
Unknown, since without the exception we can't tell what's causing the failure.
*Specifications like the version of the library, operating system etc
This only started happening after updating to version 1.14.0, did not happen on version 1.13.3
*Relevant logs and traces
None, since without the exception we don't have a stack trace.

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>

**Comment by iambmelt** [comment]
Confirming this bug.

PR to resolve is out in #1222 & #1223 -- need CR /cc @addev-ashish @heidijinxujia @danieldobalian

**Comment by iambmelt** [comment]
Closed by #1222
