### ISSUE TITLE
New exception with version: Fail to valid authority with errors: [50049]

### ISSUE THREAD

**Issue by sixpi** [AzureAD/azure-activedirectory-library-for-android#1151]
Please ensure the following information is provided when logging a new issue:

* Expected behavior
We can log in successfully.
* Actual behavior
We get an exception in `sendRequest` with the error code [50049]
* Steps to reproduce the problem
* Specifications like the version of the library, operating system etc
We started seeing this error with version 1.14.0, was not present with version 1.13.3
* Relevant logs and traces
Stack trace:
```
Fail to valid authority with errors: [50049]  
com.microsoft.aad.adal.Discovery.sendRequest(Discovery.java:274)
com.microsoft.aad.adal.Discovery.performInstanceDiscovery(Discovery.java:230)  
com.microsoft.aad.adal.Discovery.validateAuthority(Discovery.java:133)  
com.microsoft.aad.adal.AcquireTokenRequest.validateAuthority(AcquireTokenRequest.java:293)  
```

<b>Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.</b>

For <b>privacy/security</b> issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>
[](url)

**Comment by iambmelt** [comment]
`50049` is an STS error mapping to `NoSuchInstanceForDiscovery` -- this would have yielded an `HTTP 400 Bad Request` indicating an invalid tenant.

@sixpi What's your status on this issue?

**Comment by sixpi** [comment]
Haven't seen this error recently, so I'll close this issue for now.

**Comment by iambmelt** [comment]
Thanks for following up, @sixpi!
