### ISSUE TITLE
Update issue/PR templates to Markdown

### ISSUE THREAD

**Issue by sixpi** [AzureAD/azure-activedirectory-library-for-android#1152]
The issue and PR templates don't use Markdown, I think it would make filling in the templates more enjoyable if they were. 

<b>Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.</b>

For <b>privacy/security</b> issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>

**Comment by iambmelt** [comment]
Closed by #1153 

Thank you @sixpi
