### ISSUE TITLE
Telemetry: Additional information needs to be provided around AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED to disambiguate scenarios

### ISSUE THREAD

**Issue by nazukj** [AzureAD/azure-activedirectory-library-for-android#1158]
Currently, when authentication through broker fails, we get a generic telemetry event "AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED" which does not contain specific information around what failed. We need to add extra information for this call to understand reasons why auth with broker fails.

This is a top error in telemetry for silent calls.

**Comment by addev-ashish** [comment]
#1140 is tracking the same issue. Or are the intent of both of these different?

**Comment by addev-ashish** [comment]
Closing this one in favor of #1140
