### ISSUE TITLE
Please remove library dependency on appcompat

### ISSUE THREAD

**Issue by kmansoft** [AzureAD/azure-activedirectory-library-for-android#1169]
The ADAL library (the library itself) has a dependency on appcompat.

Not all apps use Android AppCompat.

I checked the sources - the only imports from android.support in the library itself (under adal/main) are for:

- android.support.v4.content.LocalBroadcastManager
- android.support.annotation.Nullable
- android.support.annotation.VisibleForTesting

These only require:

- com.android.support:support-core-utils
- com.android.support:support-annotation

Or a dependency on support-core-ui would get both.

There are sample apps that do use appcompat - automationtestapp, userappwithbroker - they could have dependencies on appcompat in with their individual bulid.gradle files, as needed.

**Comment by iambmelt** [comment]
No plans to change this currently
