### ISSUE TITLE
Please remove "zoom controls" in the login activity

### ISSUE THREAD

**Issue by kmansoft** [AzureAD/azure-activedirectory-library-for-android#1170]
Please see attached screenshot.

![device-2018-04-17-000146_rs](https://user-images.githubusercontent.com/1686219/38835078-19f20cb6-41d3-11e8-9aaf-efa96cb24791.png)

The zoom controls are:

- Ugly as sin
- Not needed since the login page is "mobile enabled" and adapts itself to the width of WebView (CSS media queries)

The relevant lines in AuthenticationActivity are:

```
        mWebView.getSettings().setUseWideViewPort(true);
        mWebView.getSettings().setBuiltInZoomControls(true);
```

**Comment by danieldobalian** [comment]
@kmansoft thanks for the recommendation. We're doing to do a few minor reviews on the end user implications, but I like this change.

**Comment by iambmelt** [comment]
No plans to change this currently
