### ISSUE TITLE
Resource parameter when getting access token from code?

### ISSUE THREAD

**Issue by kmansoft** [AzureAD/azure-activedirectory-library-for-android#1171]
This is more of a question - or _potential_ concern, but I'm not sure.

There is a mismatch between what ADAL does vs. Azure AD OAUTH2 documentation for the step of "exchanging approval code for tokens".

Azure AD OAUTH2 docs:

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code

Under: Use the authorization code to request an access token

> **resource | required** if specified in authorization code request, else optional | The App ID URI of the web API (secured resource).

On the other hand, ADAL (looking at source code, and and I've also debugged into it):

**Uses resource=**... on the authorization URL, this is in Oauth2.java  in getAuthorizationEndpointQueryParameters

https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/Oauth2.java#L111

But **does not use resource=** on the "get tokens from access code" request, again Oauth2.java in buildTokenRequestMessage, although the docs (above) say that resource= is required in this case.

https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/Oauth2.java#L195

The login process is working for me just fine and no trouble (I'm testing with resource = "https://outlook.office365.com/", Office 365), but it still worries me that it contradicts the official docs.

- Is the AD OAUTH2 documentation page wrong about **resource** being mandatory in this case (when it was included on the authorization request)?

- If it is wrong, is there a "right" version of docs somewhere (where)?

- Or are the docs correct and it's a bug in ADAL but it just happens to work for now (and may break in the future)?

**Comment by danieldobalian** [comment]
@kmansoft we've just published some updates to those docs to be more clear on the behavior. Expect the docs to be more explicit shortly.  

The endpoints allow for the resource URI to be specified on either or both endpoints. In the case of ADAL, it does not allow apps to customize behavior in the authorization code flow meaning the resource URI going to each endpoint will be consistent (hence we just specify it once).

**Comment by kmansoft** [comment]
Yes the docs are more clear now, covering both "either" and "both" scenarios.

And I can see that ADAL code complies with the updated documentation.

Thank you.
