### ISSUE TITLE
Fix the ignored unit tests caused by the unified/dev Merge

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/azure-activedirectory-library-for-android#1186]
There are couple of unit tests ignored in the unified/dev. @iambmelt should have detailed context why these unit tests are skip for now as well as the future plan of them.

- testScenarioEmptyIdToken
- testNewTokenOnlyWrittenToPreferredCacheLocation
- testGetChallengeResponseInvalidRedirect

RFC #1184

**Comment by iambmelt** [comment]
Working as intended. CLosing
