### ISSUE TITLE
update ADAL's targetSdkVersion to 26

### ISSUE THREAD

**Issue by piqiums** [AzureAD/azure-activedirectory-library-for-android#1191]
On 12/19/2017 Google announced the following:

In the second half of 2018, Play will require that new apps and app updates target a recent Android API level. This will be required for new apps in August 2018, and for updates to existing apps in November 2018. This is to ensure apps are built on the latest APIs optimized for security and performance.

source: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

August 2018: New apps required to target API level 26 (Android 8.0) or higher.
November 2018: Updates to existing apps required to target API level 26 or higher.
2019 onwards: Each year the targetSdkVersion requirement will advance. Within one year following each Android dessert release, new apps and app updates will need to target the corresponding API level or higher.

 Hence, we need to update the targetSdkVersion to 26 for ADAL

**Comment by piqiums** [comment]
working in progress

**Comment by iambmelt** [comment]
Closed by #1240 , thanks @piqiums @kreedula
