### ISSUE TITLE
getAuthority on AuthenticationResult fails in non-instance aware cases

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/azure-activedirectory-library-for-android#1196]
Please ensure the following information is provided when logging a new issue:

<ul>
  <li>Expected behavior</li>

```myAuthResult.getAuthority == "the_authority_used_in_auth"```

  <li>Actual behavior</li>

```myAuthResult.getAuthority == null```
  <li>Steps to reproduce the problem</li>
do not enable instance aware, do a normal sign in, inspect the AuthenticationResult or use the getter.

**Comment by rpdome** [comment]
Fix in #1481
