### ISSUE TITLE
Verify ADAL POM task with maven-central common dependency

### ISSUE THREAD

**Issue by kreedula** [AzureAD/azure-activedirectory-library-for-android#1217]
Prerequisites 
1. common is published to maven-central
2. ADAL - dev is merged to master for release

On a new release branch, make sure to include common as a maven dependency and run gradle assembleRelease task.
Ensure that a new POM file is generated and it has common  `<dependency> `  tag associated with it.

(Edit: @iambmelt)
Build variants to support dependency resolution from various environments are needed to keep our development workflow from becoming encumbered with build script changes pre/post deployment.

**Comment by iambmelt** [comment]
See #1231
