### ISSUE TITLE
Feature Request - Please make IBrokerProxy and BrokerProxy public for Android

### ISSUE THREAD

**Issue by jiankai82** [AzureAD/azure-activedirectory-library-for-android#1227]
Currently, IBrokerProxy and BrokerProxy have no scope modifier.  Therefore, they are package private.  I have a need to check if user can use a broker (e.g. Microsoft Authenticator app) for authentication before user tries to sign in to my app.  I would like to call canSwitchToBroker in BrokerProxy from outside of the library.  Can you make this happen?

**Comment by danieldobalian** [comment]
@jiankai82 in what cases do you expect the user not to be able to use the broker app?

**Comment by jiankai82** [comment]
In addition to authenticator is not installed on the device, I see the canSwitchToBroker method does several other checks such as certificate, signature, account verification, etc.  If any of these failed, it will not allow user to use authenticator.

**Comment by iambmelt** [comment]
Assigning to @hamiltonha as this is a feature request

**Comment by iambmelt** [comment]
We are not looking to take this feature currently, closing.
