### ISSUE TITLE
Dialog version of AuthenticationContext.acquireToken() causes subsequent non-ADAL Chromium webviews to throw

### ISSUE THREAD

**Issue by ms-jihua** [AzureAD/azure-activedirectory-library-for-android#1234]
### Steps:
On a device that uses Chromium for its WebViews by default:

1. Call AuthenticationContext.acquireToken() ([a Dialog-based one](http://static.javadoc.io/com.microsoft.aad/adal/1.14.0/com/microsoft/aad/adal/AuthenticationContext.html#acquireToken-java.lang.String-java.lang.String-java.lang.String-java.lang.String-com.microsoft.aad.adal.PromptBehavior-java.lang.String-com.microsoft.aad.adal.AuthenticationCallback-))
2. On the UI thread, call anything that causes a WebView to inflate (ie: create another Dialog, setContentView(R.layout.some_layout_with_webview)

### Expected:
The new WebView inflates successfully.

### Actual:
An IllegalStateException is thrown:

> E/AndroidRuntime: FATAL EXCEPTION: AcquireTokenRequestHandlerThread
> java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
> at com.android.webview.chromium.WebViewChromium.createThreadException(WebViewChromium.java:294)
> at com.android.webview.chromium.WebViewChromium.checkThread(WebViewChromium.java:309)
> at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:227)
> at android.webkit.WebView.<init>(WebView.java:606)
> at android.webkit.WebView.<init>(WebView.java:542)
> at android.webkit.WebView.<init>(WebView.java:525)
> at android.webkit.WebView.<init>(WebView.java:512)
> at java.lang.reflect.Constructor.newInstance(Native Method)
> at android.view.LayoutInflater.createView(LayoutInflater.java:619)
> at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
> at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
> at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
> at android.app.Dialog.setContentView(Dialog.java:512)

This is on a device running Android 6.0.1, ADAL 1.14.0.

### Speculative cause:
In my logs, when I run acquireToken(), I see the following a few lines after:
> V/WebViewChromiumFactoryProvider: Binding Chromium to background looper Looper (AcquireTokenRequestHandlerThread, tid 2626) {b98db11}

Chromium web views appear to [bind to the thread that they are first called on](https://android.googlesource.com/platform/frameworks/webview/+/f989a7846d5fe4116de1a0635a8aade09d2be7b2/chromium/java/com/android/webview/chromium/WebViewChromiumFactoryProvider.java#199), treating it as the UI thread. They will then [throw if called from any other thread](https://android.googlesource.com/platform/frameworks/webview/+/f989a7846d5fe4116de1a0635a8aade09d2be7b2/chromium/java/com/android/webview/chromium/WebViewChromium.java#354).

Since #906, ADAL has been calling its webview methods on a private thread rather than the UI thread. Chromium binds to this, making webviews inoperable from any other thread. I can successfully work around this issue by rolling back to ADAL version 1.12.0, before this change was added.

Assuming the above cause is correct, is it possible to fix the memory leak mentioned in #906 some other way?

**Comment by iambmelt** [comment]
Hi @ms-jihua -- Do you have a small sample project you could share with us demonstrating this behavior?

**Comment by ms-jihua** [comment]
Hi @iambmelt, are there any updates?

**Comment by shoatman** [comment]
I've picked this up.  Currently adding some additional automation test app support for this scenario in particular.

**Comment by shoatman** [comment]
I'm inclined to rollback the change to threading model that was introduced.  Have a follow up email out to the team to confirm a few other issues observed during investigation.
