### ISSUE TITLE
Fix incorrect Exception returned on IOException in Discovery.java

### ISSUE THREAD

**Issue by kreedula** [AzureAD/azure-activedirectory-library-for-android#1288]
Please ensure the following information is provided when logging a new issue:
ADAL throws DEVELOPER_AUTHORITY_IS_NOT_VALID_INSTANCE when it encounters IOException in performInstanceDiscovery() in Discovery.java.
We should break it up into SockettimeoutException and IOException,

Excepted Behavior : ADAL throws the same error that is thrown when network errors are hit.

**Comment by kreedula** [comment]
Fixed via https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1289

**Comment by addev-ashish** [comment]
The fix does not address the developer experience around this issue. we should catch sockettimeoutexception and return the network error that we return when network is not available

**Comment by iambmelt** [comment]
Closing as fixed
