### ISSUE TITLE
Add attribution information for 3rd party dependencies

### ISSUE THREAD

**Issue by demoritas** [AzureAD/azure-activedirectory-library-for-android#1299]
adal 1.15 includes more 3rd party libraries. It would be good if the adal documentation mentions them so we can attribute them correctly

+--- com.microsoft.aad:adal:1.14.1
|    \--- com.google.code.gson:gson:2.8.1

vs

+--- com.microsoft.aad:adal:1.15.0
|    +--- com.google.code.gson:gson:2.8.4
|    \--- com.microsoft.identity:common:0.0.3
|         +--- com.nimbusds:nimbus-jose-jwt:5.7
|         |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|         |    \--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3
|         |         \--- net.minidev:accessors-smart:1.2
|         |              \--- org.ow2.asm:asm:5.0.4
|         \--- com.google.code.gson:gson:2.8.4

**Comment by danieldobalian** [comment]
Will include dependencies in future release notes.
