### ISSUE TITLE
Update proguard documentation for 1.15

### ISSUE THREAD

**Issue by demoritas** [AzureAD/azure-activedirectory-library-for-android#1300]
* Expected behavior
Proguard obfuscates adal and dependencies with the provided information 

* Actual behavior
Proguard fails because there are unresolved references

com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.engines.AESEngine	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.params.KeyParameter	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.engines.AESEngine	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.params.AEADParameters	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.InvalidCipherTextException	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.InvalidCipherTextException	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.engines.AESEngine	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.CipherParameters	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.BlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.params.AEADParameters	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.InvalidCipherTextException	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.modes.GCMBlockCipher	
com.nimbusds.jose.crypto.LegacyAESGCM: can't find referenced class org.bouncycastle.crypto.InvalidCipherTextException	
com.nimbusds.jose.crypto.bc.BouncyCastleProviderSingleton: can't find referenced class org.bouncycastle.jce.provider.BouncyCastleProvider	
com.nimbusds.jose.jwk.ECKey: can't find referenced class org.bouncycastle.cert.jcajce.JcaX509CertificateHolder	
com.nimbusds.jose.jwk.ECKey: can't find referenced class org.bouncycastle.asn1.x509.SubjectPublicKeyInfo	
com.nimbusds.jose.jwk.ECKey: can't find referenced class org.bouncycastle.asn1.x509.AlgorithmIdentifier	
com.nimbusds.jose.jwk.ECKey: can't find referenced class org.bouncycastle.cert.jcajce.JcaX509CertificateHolder

**Comment by cofitz1** [comment]
I also hit this - I needed to add the following to my proguard rules since 1.15.0.  This really needs to be updated because it is not obvious what may need to be added without code inspection.

```
#Keep ADAL classes
-keep class com.microsoft.aad.adal.** { *; }
-keep class com.microsoft.identity.common.** { *; }

#Keep Gson for ADAL https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep class com.google.gson.examples.android.model.** { *; }
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-dontwarn org.bouncycastle.**
```

**Comment by kreedula** [comment]
Thanks cofitz1 for your contribution we have updated our guidance [here](https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/ProGuard) with your recommendation
