### ISSUE TITLE
Don't use findbugs annotations to suppress warnings

### ISSUE THREAD

**Issue by demoritas** [AzureAD/azure-activedirectory-library-for-android#1301]
HttpWebRequest uses edu.umd.cs.findbugs.annotations.SuppressFBWarnings to suppress a warning.
 This leads to problems with Proguard since the import cannot be resolved which forces us to add

-dontwarn edu.umd.cs.findbugs.annotations.SuppressFBWarnings

to the proguard configuration

**Comment by iambmelt** [comment]
No current plans to change this behavior
