### ISSUE TITLE
ADAL returns "Doze" mode error after device should be out of Doze mode.

### ISSUE THREAD

**Issue by shoatman** [AzureAD/azure-activedirectory-library-for-android#1302]
* Expected behavior
Once out of Doze mode application is able to refresh access token again.

* Actual behavior
App continues to receive "Network connection is disabled, because the device is in doze mode or the app is standby.Unable to access the network due to power optimizations" error message.

* Steps to reproduce the problem
User  was travelling abroad and as a result had disabled cellular data roaming but had enabled wifi.  User had recently disabled airplane mode in order to check email upon arrival.

* Specifications like the version of the library, operating system etc.
Will update once collected from partner team

* Relevant logs and traces
Will update once collected from partner team

**Comment by athornz** [comment]
I've also come across this. When my app receives a push notification after being in doze mode I can't authenticate because the library thinks it's still in doze mode.

**Comment by hamiltonha** [comment]
@shoatman

**Comment by iambmelt** [comment]
I was able to get a repro on this by using the following steps:

1. Create the following activity (uses same network detection logic as ADAL)
```java
package com.microsoft.testing.arbitraryexecutionapp;

import android.app.usage.UsageStatsManager;
import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.os.PowerManager;
import android.util.Log;
import android.view.View;
import android.widget.Button;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    private static final String TAG = MainActivity.class.getSimpleName();

    Button mBtnRun;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mBtnRun = findViewById(R.id.btn_run);
        mBtnRun.setOnClickListener(this);
    }

    @Override
    public void onClick(@NonNull final View view) {
        Log.d(TAG, getInternetConnectionState(MainActivity.this));
        Log.d(TAG, getIsDeviceIdleMode(MainActivity.this));
        Log.d(TAG, getIsAppInactive(MainActivity.this));
        Log.d(TAG, getIsAppIgnoringBatteryOptimizations(MainActivity.this));
    }

    private String getIsAppIgnoringBatteryOptimizations(Context context) {
        return "isIgnoringBatteryOptimizations? "
                + ((PowerManager) context.getSystemService(Context.POWER_SERVICE)).isIgnoringBatteryOptimizations(context.getPackageName());
    }

    private String getIsAppInactive(Context context) {
        return "isAppInactive? "
                + ((UsageStatsManager) context.getSystemService(Context.USAGE_STATS_SERVICE)).isAppInactive(context.getPackageName());
    }

    private String getInternetConnectionState(Context context) {
        final ConnectivityManager connectivityManager = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        final NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();
        boolean result = null != networkInfo && networkInfo.isConnectedOrConnecting();
        return "(Real)" + "Network is available? " + result;
    }

    private String getIsDeviceIdleMode(Context context) {
        return "Device is idle? "
                + ((PowerManager) context.getSystemService(Context.POWER_SERVICE)).isDeviceIdleMode();
    }
}
```

2. [Force device into idle mode](https://developer.android.com/training/monitoring-device-state/doze-standby.html)
```
adb shell dumpsys deviceidle force-idle
```

3. Observe logging outputs
```sh
2020-03-10 18:15:41.566 548-548/com.microsoft.testing.arbitraryexecutionapp D/MainActivity: (Real)Network is available? true
2020-03-10 18:15:41.572 548-548/com.microsoft.testing.arbitraryexecutionapp D/MainActivity: Device is idle? true
2020-03-10 18:15:41.573 548-548/com.microsoft.testing.arbitraryexecutionapp D/MainActivity: isAppInactive? false
2020-03-10 18:15:41.574 548-548/com.microsoft.testing.arbitraryexecutionapp D/MainActivity: isIgnoringBatteryOptimizations? false
```

Per the above logic, ADAL believes that idlestate == no network; however, this is demonstrably false.

So, we've established that network can continue to work even if idle state is reported however, I don't think the "fix" here is an simple as removing the check.
 
Per the docs the device **may** restrict network access when in idle mode ("may" being the operative word here). My worry here if we simply remove this check as-is, would be that requests are proxied to the broker, the broker is in "idle" mode and has no internet connection so the request is not serviced and ADAL hangs until the broker exits idle mode. That would be a pretty bad user experience

Currently I think the best solution here is to have affected users exclude the broker app from battery optimization (AKA doze mode) via Settings to force `isIgnoringBatteryOptimizations() == true`

**Comment by shahzaibj** [comment]
@iambmelt Could the network be available because the device was going through the maintenance window? https://source.android.com/devices/tech/power/platform_mgmt

Also when Android say that network is available, does that mean it is actually available? When you ran your test and got `true` for network is available, were you actually able to make a network request?

**Comment by iambmelt** [comment]
> @iambmelt Could the network be available because the device was going through the maintenance window? https://source.android.com/devices/tech/power/platform_mgmt
> 
> Also when Android say that network is available, does that mean it is actually available? When you ran your test and got `true` for network is available, were you actually able to make a network request?

The device had an active and valid network connection for this test: switching to my browser still let me navigate, refresh, and otherwise use everything normally

**Comment by iambmelt** [comment]
This issue should now be resolved by changed in `common`:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/894
