### ISSUE TITLE
UTF-8 is not supported error: whats the mitiation and resolution?

### ISSUE THREAD

**Issue by sucindra** [AzureAD/azure-activedirectory-library-for-android#1312]
Please ensure the following information is provided when logging a new issue:

* Expected behavior
ADAL lib returns valid ticket for all valid cases.

* Actual behavior
the ADAL library (1.14.0)  returns "UTF-8 is not supported". This is called out here. https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN#utf-8-is-not-supported

* Steps to reproduce the problem
when user tries to signin with acquireToken call,

* Specifications like the version of the library, operating system etc.
ADAL 1.14.0

* Relevant logs and traces

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting)

**Comment by kreedula** [comment]
We have identified an issue where we are incorrectly reporting  UTF_8_IS_NOT_SUPPORTED on an IOException in 3 instances. This is fixed here : https://github.com/AzureAD/azure-activedirectory-library-for-android-unity-fork/pull/236
