### ISSUE TITLE
Incorrect Javadoc class type in CoreAdapter

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1330]
Missed this in my CR of #1328 -- The parameters/return types are not subclasses of `AccountRecord`, it should be ~`BaseAccount`~ `AzureActiveDirectoryAccount` instead

**Comment by iambmelt** [comment]
I'll fix this in the `release/1.15.2` branch @kreedula

**Comment by kreedula** [comment]
Fixed via  https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1331
Thanks @iambmelt
