### ISSUE TITLE
Refactor a minimal subset of Adal classes into common to support x-cache synchronization

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1346]
Objective:
- For a future release, MSAL should be able to synchronize SSO state from the ADAL format by reading its `SharedPreferences`

Given:
- ADAL writes to `SharedPreferences` by serializing instances of `TokenCacheItem` using `Gson`.
- `TokenCacheItem` is namespaced to ADAL (thus inaccessible in `common` / MSAL)

Therefore:
- `TokenCacheItem` (+ a minimal subset of supporting classes) must be migrated to `common` such that the schema is not just 1:1 with ADAL's cache format, but actually uses the same POJO as the deserialization target

**Comment by hamiltonha** [comment]
@iambmelt Is this done? If so can you close the issue?

**Comment by iambmelt** [comment]
Yeah, this is done. Thanks @hamiltonha
