### ISSUE TITLE
Close FileInputStream in getVersionProps in version_tasks.gradle

### ISSUE THREAD

**Issue by kreedula** [AzureAD/azure-activedirectory-library-for-android#1354]
FileInputStream is not closed in getVersionProps which could leak file descriptors. Fix like below

```
def versionPropsStream = new FileInputStream(versionPropsFile))
try {
    def versionProps = new Properties()
    versionProps.load(versionPropsStream)
} finally {
    versionPropsStream.close()
}
```

**Comment by iambmelt** [comment]
@kreedula I'm stealing this

**Comment by iambmelt** [comment]
Other projects have this issue too - I will file the associated GitHub issues and update this comment:
- Common
- MSAL
- Broker

**Comment by iambmelt** [comment]
See links in `@mentioned`
