### ISSUE TITLE
Is the callback of acquireToken() in the class of AuthenticationContextObject possibly return null for authority

### ISSUE THREAD

**Issue by mrjoema** [AzureAD/azure-activedirectory-library-for-android#1357]
from https://identitydocs.azurewebsites.net/static/aad/sovereign_clouds.html 
(Section of Azure AD instance discovery), it said we need to re-initialize the AuthContext object with the new authority from the result given through acquireToken call.
 
My question is: 
Is getAuthority() possibly returning null ?

**Comment by danieldobalian** [comment]
To add more color, in some instances they are seeing null returned.

**Comment by danieldobalian** [comment]
After further discussion, there shouldn't be any case `getAuthority()` should return null. We'll fix this in a future release. 

In the meantime, based on offline discussions it sounds non-essential for each request to provide an authority- your app can continue to use the first response.

**Comment by mrjoema** [comment]
Hi, I want to follow up when this bug is gonna resolved ?

**Comment by iambmelt** [comment]
`authority` will be `null` in non-sovereign cloud scenarios. This is a known implementation gap, but there is no current scheduled work to change this behavior

/cc @hamiltonha
