### ISSUE TITLE
[Memory leak]: Authentication Activity leaked - 749 KB

### ISSUE THREAD

**Issue by ravarora** [AzureAD/azure-activedirectory-library-for-android#1363]
ADAL version : 1.13.3
Logcat:
In com.microsoft.mobile.polymer.dev1:1.0.9931.9005:1699319005.
* com.microsoft.aad.adal.AuthenticationActivity has leaked:
* GC ROOT static com.microsoft.intune.mam.client.app.offline.OfflineComponents.mActivityLifecycleMonitor
* references com.microsoft.intune.mam.client.app.offline.OfflineActivityLifecycleMonitor.mLastKnownForegroundActivity
* leaks com.microsoft.aad.adal.AuthenticationActivity instance

* Retaining: 749 KB.
* Reference Key: a2084745-e839-44ea-b9cc-51ca4a56cd4e
* Device: vivo vivo vivo 1718 1718
* Android Version: 7.1.2 API: 25 LeakCanary: 1.5.4 74837f0
* Durations: watch=5124ms, gc=160ms, heap dump=3285ms, analysis=93901ms

* Details:
* Class com.microsoft.intune.mam.client.app.offline.OfflineComponents
|   static mEnrollmentManager = com.microsoft.intune.mam.client.app.offline.OfflineMAMEnrollmentManager@319987968 (0x1312a100)
|   static mActivityLifecycleMonitor = com.microsoft.intune.mam.client.app.offline.OfflineActivityLifecycleMonitor@319970560 (0x13125d00)
|   static mContext = android.app.ContextImpl@315230576 (0x12ca0970)
|   static mMAMIdentityManager = com.microsoft.intune.mam.client.app.offline.OfflineMAMIdentityManager@317660776 (0x12ef1e68)
|   static mMAMLogManager = com.microsoft.intune.mam.client.app.offline.OfflineMAMLogManager@319976112 (0x131272b0)
|   static mMAMLogPIIFactory = com.microsoft.intune.mam.client.app.offline.OfflineMAMLogPIIFactory@317626608 (0x12ee98f0)
|   static mLocalSettings = com.microsoft.intune.mam.client.app.OfflineLocalSettings@319976096 (0x131272a0)
|   static mOfflineTelemetryLogger = com.microsoft.intune.mam.client.telemetry.FileCacheTelemetryLogger@319666144 (0x130db7e0)
|   static mSessionDurationStore = com.microsoft.intune.mam.client.telemetry.SessionDurationStore@319699744 (0x130e3b20)
|   static mMAMLogHandlerWrapper = com.microsoft.intune.mam.log.MAMLogHandlerWrapperImpl@319944592 (0x1311f790)
|   static mMAMEnrollmentStatusCache = com.microsoft.intune.mam.policy.MAMEnrollmentStatusCache@319970584 (0x13125d18)
|   static mMAMWEAccountManager = com.microsoft.intune.mam.policy.MAMWEAccountManager@319976128 (0x131272c0)
|   static $classOverhead = byte[108]@316159889 (0x12d83791)
|   static mInstallReceiver = com.microsoft.intune.mam.client.notification.OfflineCompanyPortalInstallReceiver@319976080 (0x13127290)
|   static NOTIFICATION_RECEIVER_REGISTRY = com.microsoft.intune.mam.client.ipcclient.MAMNotificationReceiverRegistryImpl@319691952 (0x130e1cb0)
* Instance of com.microsoft.intune.mam.client.app.offline.OfflineActivityLifecycleMonitor
|   static $classOverhead = byte[96]@316144097 (0x12d7f9e1)
|   mForegroundActivity = null
|   mLastKnownForegroundActivity = com.microsoft.aad.adal.AuthenticationActivity@319325952 (0x13088700)
|   mLiveActivities = java.util.HashSet@319976144 (0x131272d0)
|   shadow$_klass_ = com.microsoft.intune.mam.client.app.offline.OfflineActivityLifecycleMonitor
|   shadow$_monitor_ = 0
* Instance of com.microsoft.aad.adal.AuthenticationActivity
|   static BACK_PRESSED_CANCEL_DIALOG_STEPS = -2
|   static $classOverhead = byte[1824]@316360705 (0x12db4801)
|   static TAG = java.lang.String@315076160 (0x12c7ae40)
|   mAccountAuthenticatorResponse = null
|   mAuthRequest = com.microsoft.aad.adal.AuthenticationRequest@319548400 (0x130bebf0)
|   mAuthenticatorResultBundle = null
|   mCallingPackage = null
|   mCallingUID = 0
|   mJWSBuilder = com.microsoft.aad.adal.JWSBuilder@319550504 (0x130bf428)
|   mPkeyAuthRedirect = true
|   mReceiver = com.microsoft.aad.adal.AuthenticationActivity$ActivityBroadcastReceiver@319970728 (0x13125da8)
|   mRedirectUrl = java.lang.String@319992208 (0x1312b190)
|   mRegisterReceiver = true
|   mSpinner = android.app.ProgressDialog@319972384 (0x13126420)
|   mStartUrl = java.lang.String@319100928 (0x13051800)
|   mStorageHelper = com.microsoft.aad.adal.StorageHelper@319988128 (0x1312a1a0)
|   mUIEvent = com.microsoft.aad.adal.UIEvent@318731864 (0x12ff7658)
|   mWaitingRequestId = 0
|   mWebRequestHandler = com.microsoft.aad.adal.WebRequestHandler@319976160 (0x131272e0)
|   mWebView = android.webkit.WebView@319391744 (0x13098800)
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityExt = android.app.mobileagent.ext.ActivityExt@319976176 (0x131272f0)
|   mActivityInfo = android.content.pm.ActivityInfo@319983968 (0x13129160)
|   mActivityTransitionState = android.app.ActivityTransitionState@319780784 (0x130f77b0)
|   mApplication = com.microsoft.mobile.kaizala.PolymerApplication@315459088 (0x12cd8610)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@319976192 (0x13127300)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@319959600 (0x13123230)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEatKeyUpEvent = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1890792888 (0x70b335b8)
|   mExecutorService = null
|   mExitTransitionListener = android.app.SharedElementCallback$1@1890792888 (0x70b335b8)
|   mFinished = true
|   mFragments = android.app.FragmentController@319976208 (0x13127310)
|   mFreeformAlpha = 1.0
|   mFreeformEnableAlpha = false
|   mFreeformMode = false
|   mHandler = android.os.Handler@319929312 (0x1311bbe0)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 13450291
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@319976224 (0x13127320)
|   mInstrumentation = android.app.Instrumentation@317515592 (0x12ece748)
|   mIntent = android.content.Intent@319932160 (0x1311c700)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@314585440 (0x12c03160)
|   mManagedCursors = java.util.ArrayList@319970752 (0x13125dc0)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mReferrer = java.lang.String@319701568 (0x130e4240)
|   mResultCode = 2001
|   mResultData = android.content.Intent@319932224 (0x1311c740)
|   mResumed = false
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTaskDescription = android.app.ActivityManager$TaskDescription@319929344 (0x1311bc00)
|   mTemporaryPause = false
|   mTitle = java.lang.String@316791328 (0x12e1da20)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@319929376 (0x1311bc20)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1968513752 (0x755522d8)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@319706112 (0x130e5400)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@319970776 (0x13125dd8)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@319945024 (0x1311f940)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@319945072 (0x1311f970)
|   mTheme = android.content.res.Resources$Theme@319976240 (0x13127330)
|   mThemeResource = 2131820546
|   mBase = android.app.ContextImpl@319657344 (0x130d9580)
|   shadow$_klass_ = com.microsoft.aad.adal.AuthenticationActivity
|   shadow$_monitor_ = 1268397774
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.textservice.SpellCheckerSession$1.this$0
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by danieldobalian** [comment]
@ravarora is this the same issue you filed a few months back? Is there any difference between the two issues? Can we merge/track off this one?

**Comment by ravarora** [comment]
Yes those are the same. Many a times we get leaks from com.microsoft.aad.adal.AuthenticationActivity instance. You can merge the issues. 

Also We have updated to ADAL 1.16.0 and till now we haven't got this issue.
