### ISSUE TITLE
shouldOverrideUrlLoading(final WebView view, String url): Need a way to allow http-based URL loading with target as localhost

### ISSUE THREAD

**Issue by rahulsu** [AzureAD/azure-activedirectory-library-for-android#1367]
Hi
 Details:
========
  OS: Android 8.1.0
  model: Nexus 5X
  native app: One Drive
  flow being tested: office365 SAML flow

 Steps to reproduce: 
===========
       Open 'One Drive'
       type the user name(email id)
       Azure AD knows the SAML-idp
      Onedrive redirects (https://<all the path>/<athn-request-info>) the user to the IDP
      IDP-authenticates user
     IDP wanst to talk to localhost ( on a web server hosted in the same mobile device where OneDrive is running), but URL is 'http://localhost:<portno>"
      WebView says, any redirection has to be HTTPS. SO my redirection fails

   Expected Behavior: If the target is localhost, and the packet does not leave device, I would like to request to please allow such redirection thats based on 'http'. I am not able to workaround, since I cant get CA-issued certificate for 'localhost'

More Details:
========
     
  I have some solution, which integrates with some MS native applications ( o n Andoid and Ios) such as OneDrive. My solution has one server, and one native app ( on the same device). 
  MS native apps (such as OneDrive) are based on ADAL, and handles all web redirection via WebViews. My server is https-based, so I am able to get redirection at my server. But my server needs to redirect this user agent to localhost (where the OneDrive is running) to process some action and gets the reponse back and complete the whole flow.
  But When I do this , by redirecting the WebView to my app(running a web server) i.e "http://localhost:<port-no>/url-path" , I see the errors by OneDrive android native app:

 E/AuthenticationActivity:processInvalidUrl: WEBVIEW_REDIRECTURL_NOT_SSL_PROTECTED:2018-11-22 01:23:24-0a5ae950-c760-49e4-b182-8e0206797fcc-The webview was redirected to an unsafe URL. ver:1.14.0
2018-11-21 17:23:24.897 6170-6170/? E/AuthenticationContext:onActivityResult: ON_ACTIVITY_RESULT_INTENT_NULL:2018-11-22 01:23:24-0a5ae950-c760-49e4-b182-8e0206797fcc-onActivityResult did not find the waiting request. requestId:0 ver:1.14.0

Upon reveiwing the ADAL source code, the 
shouldOverrideUrlLoading(final WebView view, String url){

} 

function currently has no provisioning for allowing such http-based redirect on to localhost.

Since the communication is not leaving the device(web server is hosted locally), can such a url be allowed be loaded ? Otherwise, forcing https for  localhost , just like external resource loading, people like me will be stuck for ever - because we cant get CA-issued certificate for 'localhost'....

Can you please advise how I can achieve this 'local redirect' in the middle(initiated by my server) of the whole https redirection orchestrated by the WebView sandbox-contained by Native App  

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting)

**Comment by iambmelt** [comment]
We won't be adding support for non `https` redirect uris at this time
