### ISSUE TITLE
AuthenticationCancelError returned erroneously

### ISSUE THREAD

**Issue by david-serrano** [AzureAD/azure-activedirectory-library-for-android#1369]
Hi, 

In the case when a user is no longer a part of the group authorised to be authenticated, we were expecting the `AuthenticationCallback<AuthenticationResult>` callback to throw an Error with an `AuthenticationException` and a code of `AdalError.AUTH_FAILED` as specified [here](http://www.java2s.com/Open-Source/Android_Free_Code/Development/sdk/com_microsoft_aad_adalADALError_java.htm) but instead we're getting an `AuthenticationCancelError`.

Interestingly, when looking at the request from Charles, we can see that the code that is returned is the correct one, together with the`error_description`. This is what we see: 
```
error=access_denied&amp;error_description=The+signed+in+user+is+not+assigned+to+a+role+for+the+application
```
It seems like somewhere in the library, the error is being swallowed up.

**Repro steps:**
- Have a user assigned to a group that can sign in
- Sign in the user (to test it works)
- Log out the user
- Remove that user from the group with access rights
- Try and sign the user in again

AD version: 1.16.0
OS: Android (any)

**EDIT:**
Investigating a little further into the problem and into the inner workings of the library, it seems to be that the resultCode in onActivityResult for `AcquireTokenRequest.java` is erroneously of type `AuthenticationConstants.UIResponse.BROWSER_CODE_CANCEL`. At this point the only user interaction has been to press the Sign in button.

**Comment by iambmelt** [comment]
Thanks for filing this issue @david-serrano -- closing, as this appears to be a duple of #726

#726 will stay open, with this item linked.
