### ISSUE TITLE
Point all the `ADALError` constants to it's duplicate class in `common`

### ISSUE THREAD

**Issue by kreedula** [AzureAD/azure-activedirectory-library-for-android#1370]
We have duplicated `ADALError` class in common in order to access some of the error constants for broker. 
Change : https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/314#discussion_r238417183
Since  `ADALError`  is a public surface, it would be a breaking change if we delete it. So instead we need to make a change to point all the constants in Adal's  `ADALError` to the one's in `common`

**Comment by iambmelt** [comment]
`ADALError` is an `enum`, not a class. Unless you have a specific trick in mind, subclassing or pointing references won't 'just work' -- how do you plan to reference these values without a major break?

**Comment by iambmelt** [comment]
With a few very specific exceptions to support SAML flow (recently added), this work is done. Closing
