### ISSUE TITLE
Getting BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN and then AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED

### ISSUE THREAD

**Issue by ravarora** [AzureAD/azure-activedirectory-library-for-android#1371]
For some of our users are getting BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN during silent token refresh. After this fails 3 times ADAL returns AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED and User is prompted to Sign in interactively. This is happening 2-3 times and user has not changed their passwords. 

* Expected behavior
Silent token refresh should happen successfully.

* Actual behavior
getting BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN during silent token refresh. After this fails 3 times ADAL returns AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED and User is prompted to Sign in interactively.

* Steps to reproduce the problem
No Actual Steps available.

* Specifications like the version of the library, operating system etc.
ADAL v1.13.3, Xiaomi Redmi Note 4, Android 6.0

PFA Relevant logs and traces. For ADAL Logs filter by "ADAL_"

[Archive.zip](https://github.com/AzureAD/azure-activedirectory-library-for-android/files/2674684/Archive.zip)

**Comment by bhumin3i** [comment]
hi, any update on this issue?

**Comment by iambmelt** [comment]
@bhumin3i This is a general error message from the broker's AccountManager integration. Logs are required to diagnose specific issues.

I have followed up with @ravarora offline

**Comment by bhandaribhumin** [comment]
@iambmelt 

failed {"code":"AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED","details":{"errorDescription":"Request authority:https://login.microsoftonline.com/xxxxxx clientid:xxxxxx No result returned from acquireTokenSilent","errorCode":"AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED"},"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}


 -> This error is occurs when I call **acquireTokenSilentAsync**

NOTE: Before I call acquireTokenSilentAsync I was getting cache data from tokenCache.readItems()
but cache has empty iOS works but android failed to store data into cache.


CODE: 

  ```
  //check cache for non expired refresh/tokens first and attempt a silent a sync call.
    let items = await this._authContext.tokenCache.readItems();
    //if items in cache, reset auth context
    if (items.length > 0) {
      let _authority = items[0].authority;
      this._authContext = await new Microsoft.ADAL.AuthenticationContext(
        _authority
      );
      this._userID = items[0].userInfo.uniqueId;
    }
    this._userID = this._userID || localStorage.getItem('userID');
      return this._authContext.acquireTokenSilentAsync(
      settingsURLs.graphResource,
      settingsURLs.nativeAppId,
      this._userID
    );

```

**Comment by iambmelt** [comment]
Per offline sync with @ravarora this issue is resolved.

@bhandaribhumin Please see [these docs on ADAL error handling](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-adal-error-handling#acquiretokensilent). `AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED` means you must perform an interactive login using `acquireToken` -- there are a number of non-error circumstances which trigger this Exception
