### ISSUE TITLE
If activity's noHistory is set to true in AndroidManifest callback to onActivityResult will not work

### ISSUE THREAD

**Issue by SergiusPaulus** [AzureAD/azure-activedirectory-library-for-android#1379]
This is probably not an issue but a discovery you may want to add to your (already excellent) Readme.md.  Forgive me if this is the wrong place for this.  After about six hours of debugging and head-scratching as to why my app's onActivityResult was never called after a successful (forced) login, I discovered it was because I had the following line in AndroidManifest.xml for the activity:

            android:noHistory="true"

That setting meant the activity that I supplied to your acquireToken method was not available at the time that callback was required. 

Since you already specifically address the contents of the manifest I thought it might save someone some time if they knew ahead of time they must not have noHistory set to true if they expect onActivityResult to be invoked.

**Comment by iambmelt** [comment]
Closing as not an issue; thank you for providing this information nonetheless
