### ISSUE TITLE
Unreachable code path: ApiDispatcher call to ExceptionAdapter

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1395]
The following code paths inside of `ExceptionAdapter#baseExceptionFromException()` do not appear reachable, based on [this logic inside of `ApiDispatcher`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ApiDispatcher.java#L81).

- Check for [`instanceof ClientException`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ExceptionAdapter.java#L171-L176) (a subclass of `BaseException`)
- Check for [`instanceof UiException`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ExceptionAdapter.java#L188-L194) (a subclass of `BaseException`)

**Comment by shoatman** [comment]
Should this be filed in common?  Not sure why filed in ADAL.  Also didn't follow the issue.  I haven't tested this recently, but anything that's a subclass of BaseException is simply returned.  Exceptions are translated to BaseExceptions in the helper method.

**Comment by iambmelt** [comment]
@shoatman I filed this issue here because it should probably be investigated before we release and ADAL is first. Though the mentioned files are inside of `common` and it could just as reasonably be tracked there.

As for the explanation, [this code block looks for instances of BaseExeception](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ApiDispatcher.java#L81), calling `ExceptionAdapter#getBaseExceptionFromException` if `false`.

Inside `getBaseExceptionFromException`, there are checks for instances of `ClientException` (a subclass of `BaseException`, [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ExceptionAdapter.java#L171-L176)), and `UiRequiredException` (a subclass of `BaseException`, [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ExceptionAdapter.java#L188-L194)) which won't be hit because we won't invoke this method if `instanceof BaseException == true`.

This method is invoked from two different places, both inside of `ApiDispatcher`: it's gated on the same logic in both cases.

**Comment by shoatman** [comment]
Sure.  The code referenced in the baseExceptionFromException method should be removed (because it will never be hit), but it's not breaking anything... or am I missing something.  Why is ADAL first?  Still confused by how this code is used within ADAL.  Since ADAL doesn't use the ApiDispatcher or has something changed?

**Comment by iambmelt** [comment]
This code is used by the `addAccount` API in `BrokerClientApplication` which is used by Company Portal and Authenticator (via `AccountChooserActivity`). Aren't we releasing a new broker with ADAL support targeted first? Filing this issue here was to mean 'investigate before shipping to make sure this works as intended', which seemed reasonable given the dead-code.

**Comment by shoatman** [comment]
Let's move this to the AD Accounts repo or common.  Thanks for the explanation Brian.  Yes the blocked tag drew my attention.
