### ISSUE TITLE
The base64 url encoded signature component of the redirect uri does not match the expected value.

### ISSUE THREAD

**Issue by bhandaribhumin** [AzureAD/azure-activedirectory-library-for-android#1413]
Please ensure the following information is provided when logging a new issue:

 https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/userappwithbroker/src/main/java/com/microsoft/aad/adal/example/userappwithbroker/Constants.java

in this example i see you are using redirecturl like msauth://{package}/2%2BQqCWt1ilKg0IrfKT6CkdMpPqk%3D

but idon't know (2%2BQqCWt1ilKg0IrfKT6CkdMpPqk%3D) where is that come from or how do i generate new one because in debug mode i'm getting error like 
 **"The base64 url encoded signature component of the redirect uri does not match the expected value."**

**Comment by iambmelt** [comment]
Hi @bhandaribhumin - The `userappwithbroker` is one of our test bed apps for 1st Parties (Microsoft) integrating with the authentication broker (MS Authenticator / Intune Company Portal). If your application is not integrating with the broker, you can ignore this and instead consult our [dev sample app](https://github.com/Azure-Samples/active-directory-android).

If you _are_ integrating with the broker, please see step <span>#</span>11 in the `README` under[ **How to use this library**](https://github.com/AzureAD/azure-activedirectory-library-for-android#how-to-use-this-library).

**Comment by bhandaribhumin** [comment]
I’m using broker true in Cordova plugin with Gradle v1.16.... latest one but when I debug it will give me base64 error and not store token in cache also AcquireTokenSilentAsync always fail error show me like  AcquireTokenSilentAsync not return result

**Comment by shoatman** [comment]
Take a look at: [https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v1-enable-sso-android](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v1-enable-sso-android)

Also:[https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/brokerRedirectPrint.ps1](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/brokerRedirectPrint.ps1)

**Comment by bhumin3i** [comment]
@shoatman still AcquireTokenSilentAsync 

> fail error message AcquireTokenSilentAsync not return result

**Comment by renishdeveloper** [comment]
+1
