### ISSUE TITLE
AuthenticationCallback's onError sometimes get called even after onSuccess called

### ISSUE THREAD

**Issue by yangweigbh** [AzureAD/azure-activedirectory-library-for-android#1429]
* Expected behavior
there is only one callback method got called for AuthenticationCallback
* Actual behavior
the onError callback of AuthenticationCallback got called after onSuccess called
* Steps to reproduce the problem
not 100% repro, when there is error in company portal, this problem may occur
* Specifications like the version of the library, operating system etc.
lib version: 1.16.1, android P

**Comment by iambmelt** [comment]
@yangweigbh Please reach out to the dev team internally via email so we can follow-up. Logs and repro steps are required. Additionally 1.16.2 is our latest release; you can try upgrading to see if this resolves your issue.

**Comment by hamiltonha** [comment]
We are closing this issue, feel free to reopen if the issue is still occurring
