### ISSUE TITLE
Silent acquireToken using Android Broker

### ISSUE THREAD

**Issue by ermescs** [AzureAD/azure-activedirectory-library-for-android#1437]
Currently, using the Authenticator Broker on Android, the acquireToken method prompts the user for the selection of the microsoft account retrieved from the broker.

This is causing unnecessary step to the login process, it would be useful to skip it and silently select the account, if a broker is installed. 

The acquireTokenSilentSync and acquireTokenSilentAsync of AuthenticationContext class can only perform a refresh request for a token already in cache.  

According to the following issue, this should be planned for Android ADAL but it is not clear if it's already implemented and how to use it.

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1516

**Comment by hamiltonha** [comment]
Please check the behavior using the MSAL library and open an issue there if it still exists
