### ISSUE TITLE
[1.16.3] ADAL library returning AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED on device with no broker and in airplane mode

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1450]
## Expected behavior
Error should yield `DEVICE_CONNECTION_IS_NOT_AVAILABLE`

## Observed behavior
Error yielded `AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED`

**Comment by iambmelt** [comment]
One more detail to note: On devices where a broker is installed, the error code is `BROKER_AUTHENTICATOR_ERROR_GETAUTHTOKEN`

thanks @vicalcazar

**Comment by Fshiner** [comment]
@iambmelt  Could you please help to double confirm this issue only happens on V1.16.3, what about the V1.16.1, does it also has this issue?
Is there any schedule to fix this issue?

thanks a lot!

**Comment by iambmelt** [comment]
Answer posted via email, issue does exist in older versions

**Comment by iambmelt** [comment]
As we're in crit-fixes only; unlikely this will get picked up. 1.x versions are also out of support cycle
