### ISSUE TITLE
Unable to logged in to skype for business online using flow

### ISSUE THREAD

**Issue by nisng** [AzureAD/azure-activedirectory-library-for-android#1462]
Please ensure the following information is provided when logging a new issue:

* I am trying to create the skype meeting using flow but when i am trying to add the new action "Create an online meeting". It is asking me for sign in.

When i am trying to sign in i am getting below error.

"Failed to create connection for connection id '/providers/Microsoft.PowerApps/apis/shared_skypeforbiz/connections/shared-skypeforbiz-66A03DFF-60F1-4463-89CB-235D2DD31A95'. You have reached the maximum number of connections for the 'skypeforbiz' API."

* Actual behavior/Expected behaviour - Expected behavior should be that it should sign in using my credentails and allow me to insert the values.

* Steps to reproduce the problem
- Create a flow
- Add an Action
- Search for "Skype"
- Click on "Create an online meeting"
- Try Sign in

* Relevant logs and traces

"Errror :
Failed to create connection for connection id '/providers/Microsoft.PowerApps/apis/shared_skypeforbiz/connections/shared-skypeforbiz-66A03DFF-60F1-4463-89CB-235D2DD31A95'. You have reached the maximum number of connections for the 'skypeforbiz' API.

**Comment by iambmelt** [comment]
@nisng Unfortunately this is not an error we can help you with. You will need to contact the Skype team; this error is unrelated to ADAL.

**Comment by nisng** [comment]
Thanks a lot for your response. I checked this and this is related to On-Prime Skype. Skype is not yet migrated to office 365. That is the reason i am not able to connect. Thanks a lot for your response.
