### ISSUE TITLE
adal:1.16.+ ErrorCode:invalid_grant. (working for adal 1.14)

### ISSUE THREAD

**Issue by amitse** [AzureAD/azure-activedirectory-library-for-android#1474]
## Expected behavior
```java
_authenticationContext.acquireToken(activity, resource, clientId, redirectUri, PromptBehavior.Auto, handler )
```
must return valid token for 'com.microsoft.aad:adal:1.16.+'

## Actual behavior
We have been using 'com.microsoft.aad:adal:1.16.+' for our android app for quite some time now.

Starting 1200hrs UTC 30th October our published app using 'com.microsoft.aad:adal:1.16.+' started failing with error (acquireToken method)

[Error: Request authority:https://login.microsoftonline.com/<tendant> clientid:<id>  ErrorCode:invalid_grant]

## Steps to reproduce the problem
create a sample application with adal 1.16,
```java
        AuthenticationContext  mAuthContext = new AuthenticationContext(getCurrentActivity(), authority, true);
 mAuthContext.acquireToken(getCurrentActivity(), resource, clientId, redirectUri, PromptBehavior.Auto,
                        new AuthenticationCallback<AuthenticationResult>() {
....
}
```
## Specifications like the version of the library, operating system etc.
'com.microsoft.aad:adal:1.16.+'

## Relevant logs and traces
[Error: Request authority:https://login.microsoftonline.com/<tendant> clientid:<id>  ErrorCode:invalid_grant]

## Workaround
For now reverting the library to version 1.14 seems to work and all the android apps are receiving valid token 

* MSAL or ADAL? -> ADAL
* Brokered Authentication? -> No

**Comment by iambmelt** [comment]
@amitse Please follow up with me via email -- I have started a thread.

**Comment by iambmelt** [comment]
Following up offline.

@amitse Please reach out if you continue to experience issues
