### ISSUE TITLE
app hitting v2 authentication endpoint instead of v1, when using MS Authenticator

### ISSUE THREAD

**Issue by tavikukko** [AzureAD/azure-activedirectory-library-for-android#1488]
* Expected behavior
when signing in to Azure Ad Application (V1) using MS Authenticator, the app consents the required permissions (Graph User.Read, SharePoint AllSites.Write) and is able to get accesstoken.
* Actual behavior
app consents and returns accesstoken which does not have required permissions and wrong permissions are granted to the app in azure
* Steps to reproduce the problem
create V1 app, call it with android app using this library with MS authenticator, and check the permissions that are granted. If you are not using the MS authenticator, everything works fine.
* Specifications like the version of the library, operating system etc.
latest build of this library, latest version of MS authenticator
* Relevant logs and traces
Issue also created in https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1507
Sent logs using MS Authenticator, here is the incidentID: P2HMVETN

**Comment by kreedula** [comment]
Thanks @tavikukko for reporting this.

We are internally following up the AAD server team to investigate and respond, will update once we have information.

**Comment by iambmelt** [comment]
[ADO: Tracking (corpnet required)](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1063888)

**Comment by iambmelt** [comment]
Closing, see https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1507 for details
