### ISSUE TITLE
Unable to pick an account from authenticator

### ISSUE THREAD

**Issue by aryankranthi** [AzureAD/azure-activedirectory-library-for-android#1499]
> Hi,
> 
> There is a known issue regarding Bind Service on some Android OEM. The work around is to turn off power optimization in Authenticator and Company Portal's settings.
> 
> Thanks,
> Dome
> 
> _Originally posted by @rpdome in https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/1491#issuecomment-589862419_
> 

Hi,

@rpdome : I tried with the power optimization in Authenticator and Company Portal's settings but there is no luck. Still I can able to replicate the issue. 

FYI: 
Tested In below mentioned physical devices

- android 10 Realme pro 
- android 9 Mi A3
- Android 8.1.0 Moto G5Splus
- Android 10 Moto one power

I would like to know is this because of updated version of Authenticator ? Previous versions of my app has been working as expected but annoyingly I can able to see the issue in my recent builds (i.e after 01-feb-2020). 

Thanks In Advance

**Comment by rpdome** [comment]
I believe issue you're facing is a different issue from #1491. 

The fix for account picker is being rolled out. It should hit 100% in production by tomorrow.

**Comment by aryankranthi** [comment]
Thanks @rpdome for the quick update, I updated authenticator app with latest version, now it's working fine. But my Ask is already I have the App with same version Number(6.2002.1200).

I would like to know if it is updated on the same version (6.2002.1200) because when I see the last updated version in PlayStore it is still showing me on 19-feb. can you please let me know what exactly have been changed ? 

Thanks In advance !
