### ISSUE TITLE
Feature Request - Complete logout handling

### ISSUE THREAD

**Issue by torekymilan** [AzureAD/azure-activedirectory-library-for-android#1524]
Please implement complete logout handling that redirects the user to the Microsoft identity platform endpoint to sign out the user properly not just clear the local cache. Is it possible to introduce this functionality?

**Sign out request documentation:**
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request

**Comment by iambmelt** [comment]
This is a feature request, assigning to @hamiltonha

**Comment by iambmelt** [comment]
[ADO: Tracking (corpnet required)](https://identitydivision.visualstudio.com/Engineering/_boards/board/t/DevEx%20-%20Android/Backlog%20items/?workitem=1063895)

**Comment by iambmelt** [comment]
Per sync with PM/planning: we do not plan to add this feature currently. Should this plan change, we will update this ticket

/cc @hamiltonha
