### ISSUE TITLE
About the handle way on Meizu smart phone

### ISSUE THREAD

**Issue by jz1998** [AzureAD/azure-activedirectory-library-for-android#1555]
when i try to sign in onedrive/office365/outlook on my phone(meizu), your app always give me a toast(notification) said "Your battery optimization settings or battery saver mode maybe causing an authentication issue" 
In your "How to Handle" there is no meizu phone, and could you help me to solve it.
btw, i can't find the battery optimization setting on my phone.

**Comment by iambmelt** [comment]
Hi @jz1998 -- Our library does not present any `Toasts` to the user. In fact, the only reference to this mechanism you'll find in this project is [within our sample](https://github.com/AzureAD/azure-activedirectory-library-for-android/search?q=toast&type=Code).

I suggest reviewing [Office's instructions for installation on Android devices](https://support.microsoft.com/en-us/office/install-and-set-up-office-on-an-android-cafe9d6f-8b0c-4b03-b20a-12438a82a22d), searching for your issue on [UserVoice](https://office365.uservoice.com/), making use of in-app feedback tools, or reaching out to [Office Support](https://support.microsoft.com/en-us/home/contact?ContactUsExperienceEntryPointAssetId=cafe9d6f-8b0c-4b03-b20a-12438a82a22d) if your issue persists.
