### ISSUE TITLE
Users need to do Multi Factor authentication multiple times in a day in an internal enterprise application 

### ISSUE THREAD

**Issue by aditya38112** [AzureAD/azure-activedirectory-library-for-android#1588]
We have a react native application that is used for enterprise purposes.

The expected behavior is that the token should not expire in such frequency and users need to do the multi-factor authentication sporadically.

A lot of users, almost all of them did not have intune managed store need to use the authenticator app multiple times in a day.

It is an internal enterprise app, hence could not paste any screenshots, but I hope I am clear in the behavior.

The issue is happening in both Android and IOS devices and there are no clear native issues that we can say about.

One solution we tried is using brokered authentication even after which some users are facing the issues.

So, what are the steps to solve this situation?

**Comment by iambmelt** [comment]
Hi @aditya38112 -- The requirement to perform MFA/brokered auth is specified by the [Conditional Access requirements](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview) of your users' tenant[s] & resources. These policies cannot be bypassed or ignored by this library.

For more information on integrating you app with brokered auth, please see:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on
