### ISSUE TITLE
.aar for this project

### ISSUE THREAD

**Issue by vinceweeks-69** [AzureAD/azure-activedirectory-library-for-android#1598]
Does one exist? If one does, could it be used in a Xamarin Binding project? I need the MultipleAccountPublicClientApplication interfaces and methods which don't exist in the .NET library for Microsoft.Identity.Client

**Comment by iambmelt** [comment]
[AAR is hosted on Maven Central](https://repo1.maven.org/maven2/com/microsoft/aad/adal/3.1.2/) - this question is best addressed by our .NET team over at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet.

I'd suggested engaging that team with your existing question [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2592)
