### ISSUE TITLE
Your app contains a less secure encryption mode

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/azure-activedirectory-library-for-android#1669]
I use MS Graph in my apps and I get "Unsafe Cipher Mode" warning on Google Play
Please see attached screenshot. Article Google is punting is at https://support.google.com/faqs/answer/10046138
![Screenshot 2021-12-16 131705](https://user-images.githubusercontent.com/14060247/146378981-deb25b36-6357-4f2a-82f3-71af82f024a3.jpg)

**Comment by NLLAPPS** [comment]
I think I should have created at https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/1658

**Comment by MarcusPetri** [comment]
> I think I should have created at [AzureAD/microsoft-authentication-library-common-for-android#1658](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/1658)

But it's for another library, right?

I'm using [azure-activedirectory-library-for-android](https://github.com/AzureAD/azure-activedirectory-library-for-android) and I still have this problem with the latest version. 

`    implementation('com.microsoft.aad:adal:3.1.3') {
        exclude group: 'com.android.support'
        exclude group: 'com.microsoft.device.display'
    }`
    
 Probably just need to update the common code

**Comment by MarcusPetri** [comment]
> > I think I should have created at [AzureAD/microsoft-authentication-library-common-for-android#1658](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/1658)
> 
> But it's for another library, right?
> 
> I'm using [azure-activedirectory-library-for-android](https://github.com/AzureAD/azure-activedirectory-library-for-android) and I still have this problem with the latest version.
> 
> ` implementation('com.microsoft.aad:adal:3.1.3') { exclude group: 'com.android.support' exclude group: 'com.microsoft.device.display' }`
> 
> Probably just need to update the common code

Problem solved with version 4.0.2
