### ISSUE TITLE
No error handling if internet access is lost while in authorization activity

### ISSUE THREAD

**Issue by johnlake** [AzureAD/azure-activedirectory-library-for-android#240]
If user loses internet access on login page, the page will simply be non-responsive rather than alerting the user to this issue. The user will have to cancel the activity in order to interact with the app again.

Preferably, the auth activity should display some sort of alert if internet access is lost and the user tries to load an additional page, or in some other way handle this issue.

**Comment by omercs** [comment]
That is perfect! Can you send us that as a pull request? You need to submit CLA agreement https://cla.msopentech.com/ .

**Comment by talk2arpit** [comment]
Sure. I do that.

**Comment by weijjia** [comment]
Are you still seeing the error?
