### ISSUE TITLE
Not receiving AuthenticationCancelError when Cancel button is pressed in Web Auth UI

### ISSUE THREAD

**Issue by thilgen** [AzureAD/azure-activedirectory-library-for-android#282]
1. Modify the sample ADAL Hello World app to acquire a token from a server whose web auth page has a cancel button. 

2. Launch the sample ADAL Hello World app and click Get Token button

3. Click the Cancel button on the web auth page

4. AutheticationCallback.onError is invoked and passed an instance of an AuthenticationException - the following Toast is displayed

"Error in processing code to get token. Request authority:https://login.windows.net/common resource:Microsoft.Lync clientid:d3590ed6-52b3-4102-aeff-aad2292ab01c correlationId:4f1fc46f-df7d-4cb2-8a7e-6cec0e311897"

This action should be equivalent to pressing the back button while the web auth page is being displayed - which will invoke AutheticationCallback.onError and pass an instance of AuthenticationCancelError - which allows the client app to treat as a non-failure.

**Comment by weijjia** [comment]
Close since already merged.
