### ISSUE TITLE
Please allow client apps to specify resource names used by ADAL UI flow

### ISSUE THREAD

**Issue by thilgen** [AzureAD/azure-activedirectory-library-for-android#283]
Currently ADAL library assumes that the client application (which makes use of ADAL library) defines two string resources: "app_loading" and "broker_processing". When these resources are not found - the ProgressDialog (spinner) looks quite awful

![ohub-progress-current](https://cloud.githubusercontent.com/assets/9309340/4694695/aa77b3e2-57d2-11e4-97b0-005e872ce48a.png)

1. There was no error produced by ADAL when I failed to add these resources to my client application. And the UI issue had been completely missed by my team (since in most of our test cases the ProgressDialog lifetime is very short). If these strings are meant to be mandatory - please throw an exception when they are not found.

2. Ideally I would like to take advantage of other strings which already exist in my application instead of defining a duplicate string resource just so ADAL can find the strings with the identifiers "app_loading" and "broker_processing" - please add an API so that I can provide alternative string resource names which are located in my client application for use by ADAL.

**Comment by weijjia** [comment]
Please re-open when you see the issue again.
