### ISSUE TITLE
Sign in None Conditional Access MDM (Intune) account fails intermediately when Company Portal is enrolled

### ISSUE THREAD

**Issue by topgear888** [AzureAD/azure-activedirectory-library-for-android#335]
When Company portal is enrolled, I am seeing about 2% time, sign in non CA MDM account fails (correct credentials) with error msg  "Please sign in with an organization account". And we indeed signed in with correct org account.

**Comment by omercs** [comment]
Issue: Authenticator process could not read the secret key to decrypt list of UIDs for calling apps.
Fix: Store user specified key instead of reading from memory.

**Comment by omercs** [comment]
Fix is in test status. It requires new Company portal app build to test.

**Comment by omercs** [comment]
Broker related code is updated for secret key issue.
