### ISSUE TITLE
OAuthToken is not working for accessing sharepoint files

### ISSUE THREAD

**Issue by cjgehinscott** [AzureAD/azure-activedirectory-library-for-android#336]
I am building an native Android app that is trying to identify and read files that are in Sharepoint.  I have created the native application in the Azure portal and have delegated all the permissions for Sharepoint to allow the app to read and write.  After successfully authenticating I tested a REST endpoint in Postman client in Chrome by adding the OAuth token to the HTTP Authorization header field with the "Bearer " prefix. With this configuration I am getting a 401 unauthorized.  Is this token not allowed for "all" files in Sharepoint like the permissions suggest?

**Comment by omercs** [comment]
Hey @cjgehinscott ,

Do you use sharepoint resource to get this access token?

**Comment by omercs** [comment]
You need to assign the permissions for that app. You can actually use Office 365 API library from here: https://github.com/OfficeDev/Office-365-SDK-for-Android that has samples for that. This library also talks about set up that you need to do.

You need to do discovery call to get the service endpoints and resources. See the API reference here: https://msdn.microsoft.com/en-us/office/office365/api/api-catalog
Initial token is requested for discovery endpoint with resource as 
```
DISCOVERY_RESOURCE_URL = "https://api.office.com/discovery/v1.0/me/";
DISCOVERY_RESOURCE_ID = "https://api.office.com/discovery/";
```

Next service related calls will get token for that service using the serviceResourceId. Discovery response provides this information. If you go through Office365 samples, you will see the details.

**Comment by weijjia** [comment]
Are you still seeing the issue? If so, please open it again. Close for now.
