### ISSUE TITLE
“Can’t access your account?” page does not respond to back link

### ISSUE THREAD

**Issue by omercs** [AzureAD/azure-activedirectory-library-for-android#351]
A partner team reported two bugs in the OneDrive ODB sign in flow and we’ve identified the following issues:

Issue #1
1)	In OneDrive, tap add an account (business account)
2)	Tap ‘Sign in’
3)	Once the discovery page loads, tap the “Can’t access your account?” link
4)	Once the “Can’t access your account?” page loads, tap the Back hyperlink
5)	Verify nothing happens

It seems like Back link on this page doesn’t actually do anything – can you verify if this is the case? If you don’t own this page, who does?
URL: https://passwordreset.microsoftonline.com/PasswordResetInstructionsPage.aspx?ru=#

**Comment by addev-ashish** [comment]
This should have been fixed a longtime back else OneDrive would have let us know by now.
