### ISSUE TITLE
Back button pressed requires two presses at  “Can’t access your account?” link

### ISSUE THREAD

**Issue by omercs** [AzureAD/azure-activedirectory-library-for-android#352]
1)	In OneDrive, tap add an account (business account)
2)	Tap ‘Sign in’
3)	Once the discovery page loads, tap the “Can’t access your account?” link
4)	Once the “Can’t access your account?” page loads, tap the Back button on the phone
5)	Verify nothing happens
6)	Tap the Back button again – verify that the sign-in flow is cancelled

Ideally, we should return to the discovery page when back is pressed. Unfortunately, the “Cant access your account” page requires a redirect so we navigate twice and to the user it appears that nothing happens when ‘Back’ is pressed.

**Comment by addev-ashish** [comment]
This should have been fixed by now.
