### ISSUE TITLE
Dialog based acquireToken() results in NoClassDefFoundError

### ISSUE THREAD

**Issue by myandek** [AzureAD/azure-activedirectory-library-for-android#361]
I tried out the dialog based acquireToken() method, and there seems to be a problem with the resources.  The following error occurs when I tried using it:

`java.lang.NoClassDefFoundError: com.microsoft.aad.adal.R$layout com.microsoft.aad.adal.AuthenticationDialog$1.run(AuthenticationDialog.java:79)`
`android.os.Handler.handleCallback(Handler.java:725)`
`android.os.Handler.dispatchMessage(Handler.java:92)`
`android.os.Looper.loop(Looper.java:137)`
`android.app.ActivityThread.main(ActivityThread.java:5039)`
`java.lang.reflect.Method.invokeNative(Native Method)`
`java.lang.reflect.Method.invoke(Method.java:511)`
`com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)`
`com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)`
`dalvik.system.NativeStart.main(Native Method)`

With the web based authentication method, I copied all of the resources into our app so they are in the APK’s res folder.  I’ve done the same for this one as well, but it seems that the problem is that the code is referencing R directly when using the LayoutInflator:

`// using static layout`
`View webviewInDialog = inflater.inflate(R.layout.dialog_authentication, null);`

It seems that it’s trying to locate R under the ADAL package name, but that doesn’t exist since the resources are all under my APK’s package name.  Is there a way to work around this?

**Comment by omercs** [comment]
I will update this to look up resource from given context.

**Comment by omercs** [comment]
Fix was merged.
