### ISSUE TITLE
X.509 Certificate based authentication does not work

### ISSUE THREAD

**Issue by Chirag-Chauhan** [AzureAD/azure-activedirectory-library-for-android#364]
After successful form based authentication, I will get a option as "Sign In using X.509 certificate".

I am running the Android native application. The certificate based authentication does not show me the list of certificates to select relevant certificate and then perform the certificate authentication.

If I try the same flow on Browser, the browser does show me me popup with list of certificates installed on device. And then selecting the appropriate certificate does authenticate the user.

Any help will be appreciated.

Thanks.

**Comment by omercs** [comment]
We currently do not support x.509 certificates in the webview of our SDK.

**Comment by Chirag-Chauhan** [comment]
Thanks for the information. Is there a alternative approach to achieve the same?

Thanks.

**Comment by omercs** [comment]
We don't have a solution for this right now.

**Comment by weijjia** [comment]
This is currently supported in latest in adal.
