### ISSUE TITLE
Provide toString() impl for VO types extending ODataBaseEntity

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#365]
Would be helpful in development if types like ```com.microsoft.fileservices.Item``` had ```toString()```, ```hashCode()``` and ```equals()``` implementation. Also convenient would be a ```Serializable``` or ```Parcelable``` interface for these Objects.

**Comment by omercs** [comment]
This is related to office sdk not adal.
