### ISSUE TITLE
Login page Continue button does not work after pressing keyboard "Go" on Android OS < 4.4

### ISSUE THREAD

**Issue by hakeemsyd** [AzureAD/azure-activedirectory-library-for-android#370]
Start ADAL and on the very first page type in a valid email address e.g. someone@outlook.com. While keyboard is still up press "Go" button from keyboard (on bottom right corner). Notice that nothing happened. Now try hitting "Continue" button, and it won't work anymore.

**Comment by omercs** [comment]
This could be related to the old login ux. Can you try with extraQueryparameter "nux=1" to try new ux? It does not repro for me with new login ux.

**Comment by omercs** [comment]
Please try the suggestion to check repro.
