### ISSUE TITLE
AuthenticationResult does not always have tenant Id

### ISSUE THREAD

**Issue by davechmsft** [AzureAD/azure-activedirectory-library-for-android#371]
I need to get the tenant id when my app logs in. When calling acquireToken with PromptBehavior.Auto, it will ask the user to provide credentials on the first log in. When I call getTenantId() after the call succeeds, I get the tenant id.

However, when the app is launched later, and the app connects with acquireToken, the user is not prompted because the credentials are cached. At this point getTenantId() returns null.

Is there a way to reliably get the tenant Id? I'm using v1.1.2.
Thanks!
David

**Comment by omercs** [comment]
This is fixed in dev branch. We will push new version to master and to maven repo.

**Comment by davechmsft** [comment]
Good to know. Thanks!
