### ISSUE TITLE
MFA users get into a sign in loop (from Company Portal and OneDrive) - Not a 100% repro

### ISSUE THREAD

**Issue by askhade** [AzureAD/azure-activedirectory-library-for-android#376]
Encountered this issue while signing in from Company Portal and OneDrive apps.
MFA users fall into a sign in loop where they are asked to sign in again and again. Will forward the logs on repro.

**Comment by omercs** [comment]
Can you send logs from Company portal for this issue?

**Comment by weijjia** [comment]
Close for now. Please re-open when you see the issues again.
