### ISSUE TITLE
Enroll screen breaks after changing orientation

### ISSUE THREAD

**Issue by jamoor** [AzureAD/azure-activedirectory-library-for-android#381]
When signing in with a CA enabled account on a device that doesn’t have the Company Portal app installed will change to a failure to sign in page when the phone changes orientation
![signinfailure](https://cloud.githubusercontent.com/assets/12401305/7575170/aa6affde-f7e7-11e4-92cc-98de3f3d2681.png)
. It looks like the KeyAuth header isn’t corrently being sent up for the second request.

**Comment by omercs** [comment]
Do you change orientation after seeing the enroll screen that shows button to setup company portal app?

**Comment by jamoor** [comment]
Yes, I change the orientation after seeing the enroll button appear on the screen first.

**Comment by weijjia** [comment]
Are you still seeing the issue?

**Comment by weijjia** [comment]
Close for now, please re-open if you still see the issue again.
