### ISSUE TITLE
Two-factor auth fails when activity is destroyed in the background.

### ISSUE THREAD

**Issue by brsawler** [AzureAD/azure-activedirectory-library-for-android#386]
Currently if the ADAL login activity is killed in the background (due to memory constraints, or due to Don't Keep Activities being turned on in Developer Options), login isn't possible with two-factor authentication.

Upon leaving the app to enter your PIN into the Azure Authenticator, or to answer the phone call, the activity is destroyed. Upon returning to the app after entering the necessary details, the activity is re-created fresh and users are back at the initial login screen.

Some level of state needs to be saved / restored in this case.

**Comment by omercs** [comment]
can you send logs for that? Adal has logger that can print the info.

**Comment by weijjia** [comment]
Are you still seeing the issue? If so, please reopen it. Close for now.
