### ISSUE TITLE
AuthenticationResult with Error returned in OnSuccess(AuthenticationResult) Callback

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#388]
The following Object is returned in my ```AuthenticationCallback<AuthenticationResult>.onSuccess(AuthenticationResult)``` callback

Surely this isn't a success condition, right?

    com.microsoft.aad.adal.AuthenticationResult
      mAccessToken = null
      mCode = null
      mErrorCode = "invalid_grant"
      mErrorCodes = "[65001]",
      mErrorDesc = "AADSTS65001: No permission to access user information is configured for '<CLIENT_ID>' application, or it is expired or revoked.
      Trace ID: dae12600-ace7-43d8-854d-b5cdfd4eae33
      Correlation ID: 86110b1f-e88a-4e2d-abe7-ea9fc5031461
      Timestamp: 2015-06-08 20:21:17Z"
      mExpiresOn = null
      mIdToken = null
      mInitialRequest = false
      mIsMultiResourceRefreshToken = false
      mRefreshToken = null
      mStatus = "Failed"
      mTenantId = null
      mTokenType = null
      mUserInfo = null

**Comment by omercs** [comment]
App configuration issues are returned if call is not failed. We will update in next versions to be similar to adal.net and return exception.

**Comment by weijjia** [comment]
fix is available in the latest version.

**Comment by iambmelt** [comment]
Thanks for the update @weijjia :+1:
