### ISSUE TITLE
Company Portal Options menu does not show on AAD sign in page

### ISSUE THREAD

**Issue by arnabbiswas** [AzureAD/azure-activedirectory-library-for-android#393]
Company Portal Options menu should be shown on AAD sign in page so that users facing any sign-in issue can send logs, turn on verbose logging, etc. See the screenshot attached.
![capture](https://cloud.githubusercontent.com/assets/7387125/8478757/5ac15e46-20a1-11e5-9c72-44a9dd4045a3.JPG)

**Comment by omercs** [comment]
AuthenticationActivity does not include options specific to any app. Adal supports fragment mode and dialog mode as well.
You can do this:
1-) You can launch activity using fragment and base activity will have options menu.
2-) You can use dialog mode and customize the layout. See AuthenticationDialog.java. Adal will launch the dialog from your activity which has option menu.

**Comment by weijjia** [comment]
Closed.
