### ISSUE TITLE
After deleting the work account and relaunching the app the page still shows its work place joined on Android version 5.0.2

### ISSUE THREAD

**Issue by SwethaGande7** [AzureAD/azure-activedirectory-library-for-android#402]
"WPJ leave on app: FAIL : Once the work account is deleted from the settings, relaunching the app takes us to the start page but when you try to add work account it still displays work account joined page. Tapping on back arrow allows us to add the work account though. The issue does not repro on other android versions like 4.3 and 4.4

**Comment by weijjia** [comment]
Are you still seeing the issue?

**Comment by weijjia** [comment]
Please re-open if you see the issue. Close for now.
