### ISSUE TITLE
Convergence branch: UserInfo object has null properties after authentication 

### ISSUE THREAD

**Issue by JohnAustin-MSFT** [AzureAD/azure-activedirectory-library-for-android#405]
UserInfo object from AuthenticationResult has null properties after authentication with exception of UniqueId.  GetFamilyName(), getGivenName() return null.  
                      @Override
                        public void onSuccess(AuthenticationResult result) {
                            Log.i(TAG, "onConnectButtonClick - Successfully connected to Office 365");

                            sendMailIntent.putExtra("givenName", result
                                    .getUserInfo()  
                                    .getFamilyName());  //null
                            sendMailIntent.putExtra("displayableId", result
                                    .getUserInfo()
                                    .getDisplayableId());
                            startActivity(sendMailIntent);

                            resetUIForConnect();
                        }

**Comment by omercs** [comment]
getName() method call will give the full name.
