### ISSUE TITLE
In Case of No Netwrok, Library sends  SERVER_INVALID_REQUEST instead of DEVICE_CONNECTION_IS_NOT_AVAILABLE

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#407]
If user clicks on Sign-In, in Log-In Activity and if there is no network (turn off Wi-fi ) then library sends SERVER_INVALID_REQUEST error with description Error Code:-5 net::ERR_PROXY_CONNECTION_FAILED. Ideally, It should send  DEVICE_CONNECTION_IS_NOT_AVAILABLE in this case so that app could show proper message to user.

**Comment by weijjia** [comment]
I agree with you. In the case of no network connection, server_invalid_request is not the correct error to throw. Will make the fix.

**Comment by weijjia** [comment]
fix has been merged into dev. Close for now.
