### ISSUE TITLE
TennantId is empty in response to acquireToken if CompanyPortal/Azure Authenticator App is installed

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#408]
If Company Portal App/Azure Authenticator app is installed then ADAL library returns empty Tennant Id in response to acquireToken while if those apps are not installed then library returns some not null Tennant id.

Expected: Library should always returns not null tenant id.

**Comment by weijjia** [comment]
Can you send me the logs? i didn't see this happen.

**Comment by weijjia** [comment]
Fix has already been merged. Close the issue.
