### ISSUE TITLE
In Case of SSLError or any WebViewClient errors, library always sends SERVER_INVALID_REQUEST to its caller

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#411]
If for some reason SSL Handshake fails (possible error codes: http://developer.android.com/reference/android/net/http/SslError.html
) or some errors occurs on webview client (possible error codes : http://developer.android.com/reference/android/webkit/WebViewClient.html), system sends proper error code to BasicWebViewClient on onReceivedSslError and onReceviedError respectively while library always sends SERVER_INVALID_REQUEST to its caller and combines errorCode and errorDescription. Due to which it becomes difficult at caller side 
1. To show more relevant message to end user and 
2.  To troubleshoot the issue if user device’s logs can’t be accessed.

Expected: Library should pass those error codes to its caller as it is e.g. as in additional information in AuthenticationException. This will help library consumer to show more relevant message to end user and troubleshot issues in released apps.

**Comment by weijjia** [comment]
Well, this is really a good point. Today when we capture errors in the webview, we return it to the caller, and wrap the errors in AuthenticationException, return it back to client with the error code as SERVER_INVALID_REQUEST, and wrap the original returned error code and error message in the exception message. This is really something we should consider for updating in the future, but i don't think we have plan for updating it now. This does require more detailed considerations to not break any existing "contract" regarding the error codes.

**Comment by addev-ashish** [comment]
Closing this.
