### ISSUE TITLE
Bad string comparison

### ISSUE THREAD

**Issue by MarcoMartins86** [AzureAD/azure-activedirectory-library-for-android#419]
On HttpWebRequest.java line 211: if (ex.getMessage() == UNAUTHORIZED_ERROR_MESSAGE_PRE18)

Description: Using '==' to compare two strings for equality actually compares the object references rather than their values. It is unlikely that this reflects the intended application logic.
Remediation: Use the equals() method to compare strings, not the '==' operator.

**Comment by sdwilliam** [comment]
Hi I'm William, I am checking out this project and would like to fix this bug.
