### ISSUE TITLE
During acquireToken(...) if the Resource is not valid the auth attempt failures, but no callbacks are issued

### ISSUE THREAD

**Issue by peternied** [AzureAD/azure-activedirectory-library-for-android#423]
Building up my first AAD application, I wanted to query the Discovery service for the signed in account, when I attempted to use this resource defined as https://api.office.com/discovery/v2.0/  the call failed and non of my callbacks were returned even with an error message.

**Comment by weijjia** [comment]
Can you send me the logs?

**Comment by peternied** [comment]
During the course of getting a reproduction of the failure, it looks like I configured my client id incorrectly, I'm guessing this was a mistake on my part, thanks for the quick response!
