### ISSUE TITLE
Permission change in Android M

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#424]
With the permission change in android M, adal needs to make corresponding change:
1. MANAGE_ACCOUNT and USE_CREDENTIAL is already remove from android M. 
2. GET_ACCOUNTS is now given a protection level of dangerous, adal needs to start requesting the run-time permission.

**Comment by heidijinxujia** [comment]
Do you mean  we need to remove all the code related to "android.permission.MANAGE_ACCOUNTS" and ""android.permission.USE_CREDENTIAL" and we do not need to request the permission of these two anymore?

**Comment by titorodi** [comment]
More that the ADAL Library needs to:
1. Ensure that consumers include the GET_ACCOUNTS permission in their manifest
2. That on API M client apps do a runtime request for GET_ACCOUNTS for free as part of ADAL
https://developer.android.com/training/permissions/requesting.html

**Comment by weijjia** [comment]
Adal library itself will not request the runtime permission, client app will be responsible for it. With the change of issue #475, we will return back error containing missing exception back to developer.

**Comment by twentynothing** [comment]
I actually don't think client app should use any of these permission, especially given GET_ACCOUNTS is now dangerous in M and belongs to CONTACTS group.

Company Broker or Azure Authenticator acts as broker, and already use these permissions, the library should just make IPC calls to the broker and ensure all access to account manager come from broker process. 

Thoughts?
