### ISSUE TITLE
GuestId property is missing in UserInfo 

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#425]
On ADAL iOS SDK, there is one property in its UserInfo Object i.e .guestId (ref: https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/ADALiOS/ADALiOS/ADUserInformation.h), which represents internal representation for guest users, which is missing in (Android ADAL SDK) UserInfo. 

For parity, it should be in all SDK irrespective of platforms. We have some apps on both platforms and we are not able to identity whether user has guest account or not (on Android).

**Comment by weijjia** [comment]
Investigating on when guest id will be returned from service side, and will update here.

**Comment by weijjia** [comment]
@talk2arpit Do you only use the guestId for identifying whether the user has guest account? We're still looking why ios returns it. It looks like no other ADAL platforms is returning it.

**Comment by addev-ashish** [comment]
No response in a long time. Kindly reactivate if you still need it.
