### ISSUE TITLE
If ADAL is Authenticator enabled it should immediately error on bad redirect URI

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#427]
When ADAL is in a mode where it will automatically invoke the Authenticator there is the extra requirement that the redirect uri be compatible with the Authenticator.  ADAL should immediately error out when a developer passes in an incompatible redirect uri whenever the Authenticator could even potentially get invoked.

**Comment by weijjia** [comment]
Shipped with PR #520 and #483
