### ISSUE TITLE
acquireToken returns invalid(expired) token if user changes device time.

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#428]
After calling acquireToken once if user changes device time to some previous date then after 1hr, call to acquireToken returns expired access token.

Repro steps:
1.	Call acquireToken for some resource
2.	Wait for 1 hr or more
3.	Change the device time to some timestamp in the past
4.	Call acquireToken again, this time token which it returns would be expired 

Expected: Library should never return expired/invalid token to caller.

**Comment by weijjia** [comment]
There is not a good way for us to tell if the device time is changed. This is really not a scenario we will cover. Close for now, please re-open if you still have any concerns.
