### ISSUE TITLE
android:configChanges attribute for com.microsoft.aad.adal.AuthenticationActivity should be set from library

### ISSUE THREAD

**Issue by gizmoabhinav** [AzureAD/azure-activedirectory-library-for-android#431]
Scenario:
When the following attribute is absent in AndroidManifest.xml,
`android:configChanges="orientation|keyboardHidden|screenSize"` for `com.microsoft.aad.adal.AuthenticationActivity`,
the authentication website reloads on orientation change as the activity is restarted every time.
1.  In the demo app remove above mentioned attribute from AndroidManifest.xml (azure-activedirectory-library-for-android/samples/hello/AndroidManifest.xml)
2.  Click on “Get Token” to launch the authentication website. (This website reloads on orientation change)
3.  Enter organization email ID 
4.  Enter wrong password so that you get an error message on the page
5.  Change the orientation
6.  WebViewClient crashes with ErrorCode= -1  and ERR_CACHE_MISS

I think this attribute is necessary inside the library's manifest and can be overwritten if necessary by the client.

![webview crash](https://photos-5.dropbox.com/t/2/AAAxcZPiKPjYKh1I8DggD3FPsZTDIvpfucj-2uoRNfx9sg/12/50649632/png/32x32/1/1442991600/0/2/Screenshot_2015-09-23-11-21-11.png/CKC0kxggASACIAMgBCAFIAYgBygBKAIoBw/9M3w-zUlWRuMWvva8-0olO0sb05ydnlGDVzwrDA_sl8?size=1280x960&size_mode=2)

**Comment by weijjia** [comment]
The original design should be client app to handle those configs. But I agree with you, we can put it in the library itself, and client can override it for their own sake.

**Comment by nazukj** [comment]
The library no longer crashes if this attribute is absent. Please try 1.12.0 when released. We will be unable to add this to the manifest due to possible manifest merge conflict issues.
