### ISSUE TITLE
Getting SocketException: Socket is closed

### ISSUE THREAD

**Issue by leofirespotter** [AzureAD/azure-activedirectory-library-for-android#435]
I have switched to using the dialog method instead of the activity, because of https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/433

However, I am still having a problem. The authentication is successful I get the id_token. However, I am unable to make any network requests for a long time afterwards (though it doesn't seem to happen 100% of the time). I get ```java.net.SocketException: Socket is closed``` as the error, and occasionally ```IOException shutdown```

**Comment by weijjia** [comment]
Update: Had an offline discuss with Leo, this exception happens after adal returns back the token. Adal already finished the token acquisition, and the calling app use the the id token to authenticate to their own server,  socket shutdown exception happens here.

**Comment by weijjia** [comment]
Are you still seeing the issue? If so, please reopen again. Close for now
