### ISSUE TITLE
NullPointerException when changing password

### ISSUE THREAD

**Issue by LogcatTiger** [AzureAD/azure-activedirectory-library-for-android#437]
I got the following error:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
            at com.microsoft.aad.adal.Oauth2.getToken(Oauth2.java:395)
            at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:772)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
09-30 13:35:48.222  21953-21980/com.applicat.hormiga.screen_components V/AuthenticationContext﹕ Sending error to callback CorrelationId: f20da84b-4bb3-42ab-a433-9c7c296e9706 ver:1.0.5
09-30 13:35:48.222  21953-21980/com.applicat.hormiga.screen_components V/AuthenticationContext﹕ Remove waiting request: 468113349 CorrelationId: f20da84b-4bb3-42ab-a433-9c7c296e9706 ver:1.0.5
09-30 13:35:48.282  21953-21953/com.applicat.hormiga.screen_components I/System.out﹕ error received from microsoft
09-30 13:35:48.282  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ com.microsoft.aad.adal.AuthenticationException: Error in processing code to get token. Request authority:https://login.windows.net/hormigatest.onmicrosoft.com resource:https://hormigademo.cloudapp.net clientid:03b4ccc3-70fd-44ba-931c-3b19f204c736 correlationId:f20da84b-4bb3-42ab-a433-9c7c296e9706
09-30 13:35:48.282  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:784)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at com.microsoft.aad.adal.Oauth2.getToken(Oauth2.java:395)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:772)
09-30 13:35:48.292  21953-21953/com.applicat.hormiga.screen_components W/System.err﹕ ... 5 more

Here's a screenshot with a reference to the line of code in the library (Oauth2.java:395):
![screenshot](https://cloud.githubusercontent.com/assets/14920433/10215014/87e91e64-6826-11e5-8d13-48cd9ea92c6c.png)

I currently fixed the error in my copy of the library by adding another condition: result.getCode() != null. But is that enough? Is there something wrong in what I'm doing? It usually works fine and the crash only occurs when I try to submit the data when the change password dialog is shown.

**Comment by weijjia** [comment]
Can you please take the latest version? The latest version should be able to handle the error.

**Comment by weijjia** [comment]
Latest version already has this issue addressed. Reopen when you see it happen again.

**Comment by LogcatTiger** [comment]
Thank you, Wei. I updated the version and indeed it seems not to crash.

Date: Thu, 15 Oct 2015 19:42:51 -0700
