### ISSUE TITLE
improve logging 

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#438]
1) provide more useful information at info level logs. Usually, the log level for shipped products are all at info level, we need to provide more useful logs for diagnosing issues at info level. 
2) investigate more on logging for better narrowing down issue.

**Comment by weijjia** [comment]
Closed for now. Talked to one drive team, they should be able to always turn on verbose logging for adal. Adal logs only happen when doing authentication.

**Comment by weijjia** [comment]
Reopen...current logging when decryption swallows the exact exception, and throw out the common error "Failed to get private key from keystore". This is hard to tell the exact problem when there is error.

**Comment by heidijinxujia** [comment]
When catching the exceptions, it might be better to catch the known exceptions first, if we need to handle the base exception in the end, we should do the logic first, like logging the error to the caller and rethrow the exceptions which we shouldn't swallow.

**Comment by heidijinxujia** [comment]
To get a more detailed understanding where the log happens, I'm adding the method name into the logging as a format [TAG+".methodName"].

**Comment by weijjia** [comment]
Closed for now for the exceptions changes we have done with OneDrive. Re-open when necessary.
