### ISSUE TITLE
NullPointerException in openLinkInBrowser

### ISSUE THREAD

**Issue by myandek** [AzureAD/azure-activedirectory-library-for-android#442]
W/System.err( 8011): java.lang.NullPointerException
W/System.err( 8011):    at com.microsoft.aad.adal.BasicWebViewClient.openLinkInBrowser(BasicWebViewClient.java:277)
W/System.err( 8011):    at com.microsoft.aad.adal.BasicWebViewClient.shouldOverrideUrlLoading(BasicWebViewClient.java:263)
W/System.err( 8011):    at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:299)
W/System.err( 8011):    at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:95)
W/System.err( 8011):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 8011):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
W/System.err( 8011):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 8011):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 8011):    at android.app.ActivityThread.main(ActivityThread.java:5001)
W/System.err( 8011):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 8011):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 8011):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err( 8011):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err( 8011):    at dalvik.system.NativeStart.main(Native Method)

**Comment by weijjia** [comment]
We worked through it offline, closed for now.
