### ISSUE TITLE
Refresh tokens should expire and force user to reenter credentials when user's UPN changes

### ISSUE THREAD

**Issue by myandek** [AzureAD/azure-activedirectory-library-for-android#443]
A user can be given a new UPN by the administrator (for the same user object), but ADAL does not recognize it and will still successfully re-auth using the refresh token if it's still valid.  When we get our AuthenticationResult back from ADAL, we still see the old UPN, which is breaking some of our scenarios.

**Comment by myandek** [comment]
Specifically the AuthenticationResult.getUserInfo().getDisplayableId() does not change.

It would be nice if either a) we got the new UPN in this value or b) refresh tokens could be made to expire and this would force the user to present credentials again to ADAL.

**Comment by weijjia** [comment]
You can always call acquiretoken and set prompt to always, it will force user to enter credential.

**Comment by weijjia** [comment]
does this solve ur problem? Close for now, and if you're still experiencing the issue, please open it again.

**Comment by myandek** [comment]
I'm aware that you can force the prompt for credentials, my issue is different. If the user's UPN is changed in AAD (say through O365 management portal to use a different domain for example), ADAL does not detect that the UPN has changed and continues to allow the user to authenticate using refresh tokens. In my opinion, it should be aware that the user name has changed and request the user log in again, especially since I believe some Graph API calls don't work because the access token returned form ADAL does not work for certain queries. (I might be wrong since it's been awhile since I tested that)
