### ISSUE TITLE
TennantId is empty in response to acquireToken if CompanyPortal/Azure Authenticator App is installed

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#444]
Issue#408 [https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/408] is not fixed.

**Comment by weijjia** [comment]
The new fix is in the latest adal, but you also need the updated broker app(company portal or azure authenticator. )

**Comment by weijjia** [comment]
Close for now. Please reopen when you see the issues again.
