### ISSUE TITLE
ic_launcher-web.png resource name conflicts with other 3rd party libraries

### ISSUE THREAD

**Issue by hanselip** [AzureAD/azure-activedirectory-library-for-android#446]
Prior to upgrading our build tools/gradle, our app would compile when importing both the ADAL SDK and another 3rd party SDK (UserVoice). However, after upgrading to the latest build tools/gradle, we were unable to compile with both SDKs due to a resource name conflict (ic_launcher-web.png). Would it be possible to rename this resource to something that would be ADAL-specific? Perhaps add a prefix? We've removed the other SDK for now so we can build and will be asking their team to rename the conflicting resource too. Thanks!

**Comment by weijjia** [comment]
@heidijinxujia You changed it? I saw there is commit related to this from you.

**Comment by heidijinxujia** [comment]
Yes, I think I change the file name. @weijjia

**Comment by addev-ashish** [comment]
this has been fixed.
