### ISSUE TITLE
Review try/catch clauses

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#447]
We should only catch all the known exceptions, and it's better to crash if unknown exception is thrown.

**Comment by heidijinxujia** [comment]
Line 796 in AuthenticationContext.java Should it catch the AuthenticationException for the getToken() method instead of Exception?

**Comment by weijjia** [comment]
@heidijinxujia How are we doing with this change? Are we done?

**Comment by weijjia** [comment]
Done with PR #495 .
