### ISSUE TITLE
Double Prompt For Business Account From OneDrive

### ISSUE THREAD

**Issue by joakley-msft** [AzureAD/azure-activedirectory-library-for-android#451]
1.	Install and enroll the Company Portal
2.	Install OneDrive and launch it
3.	Enter the enrolled user UPN
4.	OneDrive prompts for business or personal. Choose business
5.	OneDrive launches ADAL which launches the Company Portal. ADAL again prompts “Work account” or “Microsoft account” even though I already selected “business” from OneDrive. Even better, there’s a string bug on the ADAL page: it says “It looks like {0} is used with more than one account”

If I sign in to OneDrive without the Company Portal installed/enrolled, I don’t get the “Work account”/”Microsoft account” prompt from ADAL.

I can provide logs on request, I don't seem to have permission to attach them to this bug.

**Comment by weijjia** [comment]
want to confirm the steps, in 4, when one drive prompt, do you need to sign in? And in 5, are you saying there is another prompt letting you type the creds? Also, what is the ADAL page you mentoned? i don't believe ADAL itself display anything like "It looks like {0} is used with more than one account"

**Comment by weijjia** [comment]
Close for now. Please re-open it when you see it again.
