### ISSUE TITLE
In Case of No Network, Library sends SERVER_INVALID_REQUEST instead of DEVICE_CONNECTION_IS_NOT_AVAILABLE 

### ISSUE THREAD

**Issue by vineetsetia** [AzureAD/azure-activedirectory-library-for-android#453]
If user clicks on Sign-In, in Log-In Activity and if there is no network (turn off Wi-fi ) then library sends SERVER_INVALID_REQUEST error with description Error Code:-2 net::ERR_NAME_NOT_RESOLVED. Ideally, It should send DEVICE_CONNECTION_IS_NOT_AVAILABLE in this case so that app could show proper message to user.
Adal library version :- 1.1.10

**Comment by vineetsetia** [comment]
We had opened one more issue earlier https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/407 but instead of sending ERR_PROXY_CONNECTION_FAILED, it is sending ERR_NAME_NOT_RESOLVED. We are on adal library 1.1.10 version. Please have a look

**Comment by weijjia** [comment]
Is this happened when calling broker? Non-broker call should already have the correct error message sending back.

**Comment by vineetsetia** [comment]
This is during non-broker call.

**Comment by weijjia** [comment]
Can you provide some logs for it?

**Comment by heidijinxujia** [comment]
Hi, could you provide the logs here?

**Comment by weijjia** [comment]
Close for now. Please re-open when you see it again and send us the logs.
