### ISSUE TITLE
Lowering the core AAD library's minSdkVersion to 10 

### ISSUE THREAD

**Issue by peternied** [AzureAD/azure-activedirectory-library-for-android#454]
It looks like there is no strict dependency on the features of SDK 14, can you please lower this library have its min version dropped to 10?

**Comment by weijjia** [comment]
Do you have specific requirement to lower the version to 10? 10 is pretty old.

**Comment by peternied** [comment]
The original [LiveSDK](https://github.com/liveservices/LiveSDK-for-Android) supported version 10, and our customers would like to upgrade into the OneDrive SDKs with ADAL and MSA libraries that also support version 10.  This is about lowering friction to integrate ADAL into their platforms.

**Comment by weijjia** [comment]
@RandalliLama What do you think? 10 is pretty old, i don't think we should lower the version to support it.

**Comment by addev-ashish** [comment]
@peternied we do not want to support our SDK in Gingerbread.
