### ISSUE TITLE
Release 2.0-alpha B2C Authorization code malformed error

### ISSUE THREAD

**Issue by neerajyadav** [AzureAD/azure-activedirectory-library-for-android#455]
Release 2.0-alpha. Trying to get access token for a B2C tenant. 

Though successfully got authorization code, however get IO exception when hitting token url (https://login.microsoftonline.com/<tenant>.onmicrosoft.com/oauth2/v2.0/token). 

Error says "invalid_grant" "Authentication failed: Authorization Code is malformed or invalid."
Here is my application log.

11-18 16:58:02.981 3797-3953/com.microsoft.aad.taskapplication E/HttpWebRequest: SERVER_ERROR:2015-11-18 11:28:02-a2a510ea-eaa0-4ac0-809b-b8d4a71896a8-IOException:https://login.microsoftonline.com/<tenant>.onmicrosoft.com/oauth2/v2.0/token ver:1.1.7 
11-18 16:58:02.989 3797-3953/com.microsoft.aad.taskapplication V/HttpWebRequest: 2015-11-18 11:28:02-a2a510ea-eaa0-4ac0-809b-b8d4a71896a8-Status code:400 ver:1.1.7
11-18 16:58:02.993 3797-3953/com.microsoft.aad.taskapplication V/HttpWebRequest: 2015-11-18 11:28:02-a2a510ea-eaa0-4ac0-809b-b8d4a71896a8-Response is received ver:1.1.7
11-18 16:58:03.000 3797-3953/com.microsoft.aad.taskapplication V/Oauth: 2015-11-18 11:28:02-a2a510ea-eaa0-4ac0-809b-b8d4a71896a8-Token request does not have exception ver:1.1.7
11-18 16:58:03.005 3797-3953/com.microsoft.aad.taskapplication V/Oauth: 2015-11-18 11:28:03-afcf3d51-2e53-4316-a67c-10289e37f872-OAuth2 error:invalid_grant Description:AADSTS70000: Authentication failed: Authorization Code is malformed or invalid.
11-18 16:58:03.005 3797-3953/com.microsoft.aad.taskapplication V/Oauth: Trace ID: d30e8e7b-da5f-49be-aea6-03ac41f8e1d3
11-18 16:58:03.005 3797-3953/com.microsoft.aad.taskapplication V/Oauth: Correlation ID: afcf3d51-2e53-4316-a67c-10289e37f872
11-18 16:58:03.005 3797-3953/com.microsoft.aad.taskapplication V/Oauth: Timestamp: 2015-11-18 11:28:03Z ver:1.1.7

**Comment by weijjia** [comment]
Can you try the 2.0.1-alpha?

**Comment by neerajyadav** [comment]
Thanks @weijjia !! This has been resolved in release 2.0.1-alpha.
