### ISSUE TITLE
Adal version 2.0.1-alpha refreshToken argument not found

### ISSUE THREAD

**Issue by vikasgrover33** [AzureAD/azure-activedirectory-library-for-android#456]
Adal Version 2.0.1-alpha working fine for getting access token, but api has been changed. There are no argument found for refresh token when calling acquireToken method response callback. When calling acquireTokenSlient() it failed with refresh token not available for version 2.0.1.

**Comment by weijjia** [comment]
2.0.1-alpha is targeted for the new converged endpoint, it needs to take in the scope. Can you send me fiddler trace or logs?

**Comment by vikasgrover33** [comment]
When my access token expire i call acquireTokenSilent() method to refresh the token, but it prompts with error log.

526 25948-26157/com.arkaa.app.patient V/AuthenticationContext: 2015-12-09 13:59:49-dc1cc571-6a83-4dae-9b14-e5e2ec1c8667-Token request started ver:2.0.1-alpha
12-09 19:29:49.526 25948-26157/com.arkaa.app.patient V/DefaultTokenCacheStore: 2015-12-09 13:59:49-dc1cc571-6a83-4dae-9b14-e5e2ec1c8667-Looking for id token... ver:2.0.1-alpha
12-09 19:29:49.536 25948-26157/com.arkaa.app.patient E/DefaultTokenCacheStore: CACHE_MULTIPLE_ENTRIES:2015-12-09 13:59:49-dc1cc571-6a83-4dae-9b14-e5e2ec1c8667-Multiple entries in the cache for key:Authority:https://login.microsoftonline.com/abc.onmicrosoft.com scope:4bace7a2-16a2-4435-aa49-099e9d9519e3 clientid:4bace7a2-16a2-4435-aa49-099e9d9519e3 uniqueid: mrrt:false p:B2C_1_Patient_SignIn ver:2.0.1-alpha  TokenCache:getItem
12-09 19:29:49.536 25948-25948/com.abc.app.patient D/MYLOG: com.microsoft.aad.adal.AuthenticationException: Cache has multiple entries                    ----    at com.abc.app.patient.ui.activity.SplashActivity$2$1.onError(SplashActivity.java:168)

**Comment by brandwe** [comment]
@vikasgrover33 do you pass in the UPN of the user in `acquireTokenSilent()` call? If you have multiple users (cache entries) you must tell the SDK which one to use as the UI can't ask the user (you are doing this silently)

**Comment by vikasgrover33** [comment]
Yes ! I am already passing the UPN in acquireTokenSilent() callback, Below is the code for the same.

 mAuthContext.acquireTokenSilent(ApplicationConstants.SCOPES, ApplicationConstants.EMAIL_SIGNIN_POLICY, ApplicationConstants.CLIENT_ID, new UserIdentifier("vikasgrover100@gmail.com", UserIdentifier.UserIdentifierType.OptionalDisplayableId), new AuthenticationCallback<AuthenticationResult>() {
                        @Override
                        public void onSuccess(AuthenticationResult result) {
                         }
                        @Override
                        public void onError(Exception exc) 
                   });

But Receiving the error log.

12-11 10:51:48.982 11848-11848/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:48-fc4eade6-6b84-4dc1-a33e-de745c599d70-Sending async task from thread:11848 ver:2.0.1-alpha

12-11 10:51:48.982 11848-11963/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:48-fc4eade6-6b84-4dc1-a33e-de745c599d70-Running task in thread:11963 ver:2.0.1-alpha

12-11 10:51:48.982 11848-11963/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:48-fc4eade6-6b84-4dc1-a33e-de745c599d70-Token request started ver:2.0.1-alpha

12-11 10:51:48.992 11848-11963/com.abc.app.doctor V/DefaultTokenCacheStore: 2015-12-11 05:21:48-fc4eade6-6b84-4dc1-a33e-de745c599d70-Looking for id token... ver:2.0.1-alpha

12-11 10:51:48.992 11848-11963/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:48-fc4eade6-6b84-4dc1-a33e-de745c599d70-Checking refresh tokens ver:2.0.1-alpha

12-11 10:51:48.992 11848-11963/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:49-fc4eade6-6b84-4dc1-a33e-de745c599d70-Looking for regular refresh token. 

Key:Authority:https://login.microsoftonline.com/abc.onmicrosoft.com scope:4bace7a2-16a2-4435-aa49-099e9d9519e3 clientid:4bace7a2-16a2-4435-aa49-099e9d9519e3 uniqueid: mrrt:false p:B2C_1_Patient_SignIn ver:2.0.1-alpha


12-11 10:51:48.992 11848-11963/com.abc.app.doctor V/DefaultTokenCacheStore: 2015-12-11 05:21:49-fc4eade6-6b84-4dc1-a33e-de745c599d70-Looking for id token... ver:2.0.1-alpha

12-11 10:51:49.002 11848-11963/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:49-fc4eade6-6b84-4dc1-a33e-de745c599d70-Looking for Multi Resource Refresh token ver:2.0.1-alpha

12-11 10:51:49.002 11848-11963/com.abc.app.doctor V/DefaultTokenCacheStore: 2015-12-11 05:21:49-fc4eade6-6b84-4dc1-a33e-de745c599d70-Looking for id token... ver:2.0.1-alpha

12-11 10:51:49.002 11848-11963/com.abc.app.doctor V/AuthenticationContext: 2015-12-11 05:21:49-fc4eade6-6b84-4dc1-a33e-de745c599d70-Refresh token is not available ver:2.0.1-alpha

12-11 10:51:49.002 11848-11963/com.abc.app.doctor E/AuthenticationContext: AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED:2015-12-11 05:21:49-fc4eade6-6b84-4dc1-a33e-de745c599d70-Prompt is not allowed and failed to get token: ver:2.0.1-alpha 

12-11 10:51:49.012 11848-11848/com.abc.app.doctor D/MYLOG: com.microsoft.aad.adal.AuthenticationException: Refresh token is failed and prompt is not allowed                    ----    at com.abc.app.doctor.ui.activity.SplashActivity$2.onError(SplashActivity.java:144)

**Comment by sunny01gupta** [comment]
I am also facing the same problem when i call acquireTokenSilent() to refresh access Token with Azure ADAL ver:2.0.1-alpha.

**Comment by weijjia** [comment]
Can you share a full log with the initial request and refresh request?

**Comment by harjot-singh** [comment]
I am still facing the multiple caching issue with 2.0.1-alpha.
@vikasgrover33 Are you able to resolve this issue?

**Comment by vikasgrover33** [comment]
Yes,  i managed the code to solve multiple cache entry issue and refresh
token issue by modifying the sdk.

**Comment by harjot-singh** [comment]
@vikasgrover33 You modified the code for ADAL-2.0.1-alpha?. I am unable to locate source code for ADAL 2.0.1-Alpha.Can you please share the link for the same?

**Comment by sunny01gupta** [comment]
Hi harjot,

we don't have open source for ADAL-2.0.1-alpha. we are using convergence
branch for ADAL library mention in below link:
https://github.com/AzureAD/azure-activedirectory-library-for-android/tree/convergence
The ADAL library is in src folder and samples/hello
<https://github.com/AzureAD/azure-activedirectory-library-for-android/tree/convergence/samples/hello>
is
demo project.

We have done some changes into ADAL library for multiple cache and other
issues, if u want so we can share it.

Thanks.

On Tue, May 3, 2016 at 9:36 PM, harjot-singh <notifications@github.com>
wrote:

> @vikasgrover33 <https://github.com/vikasgrover33> You modified the code
> for ADAL-2.0.1-alpha?. I am unable to locate source code for ADAL
> 2.0.1-Alpha.Can you please share the link for the same?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/456#issuecomment-216578394>
>



-- 
*With Regards,*

*Shani Gupta*


*Software Developer*

*Growtech Solutions Pvt. Ltd.*





*23/80 Khizrabad Opp. NFCNew Delhi-110025011-26933055,011-65578993Mob.
08800752520E-mail: sunny_01gupta@yahoo.co.in
<sunny_01gupta@yahoo.co.in>            sunny.gupta@growtech.co.in
<sunny.gupta@growtech.co.in>*

**Comment by harjot-singh** [comment]
@sunny01gupta @vikasgrover33 
Thanks for sharing the link for the ADAL-2.0.1-alpha library
Yes it will be really helpful if you can share the updated library with fixes for multiple cache and other issues.

**Comment by sunny01gupta** [comment]
Hi harjot,

Please provide your personal email id so i can share zip file of library.

Thanks.

On Wed, May 4, 2016 at 10:35 PM, harjot-singh <notifications@github.com>
wrote:

> @sunny01gupta <https://github.com/sunny01gupta> @vikasgrover33
> <https://github.com/vikasgrover33>
> Thanks for sharing the link for the ADAL-2.0.1-alpha library
> Yes it will be really helpful if you can share the updated library with
> fixes for multiple cache and other issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/456#issuecomment-216933401>
>



-- 
*With Regards,*

*Shani Gupta*


*Software Developer*

*Growtech Solutions Pvt. Ltd.*





*23/80 Khizrabad Opp. NFCNew Delhi-110025011-26933055,011-65578993Mob.
08800752520E-mail: sunny_01gupta@yahoo.co.in
<sunny_01gupta@yahoo.co.in>            sunny.gupta@growtech.co.in
<sunny.gupta@growtech.co.in>*

**Comment by harjot-singh** [comment]
hi sunny,

My Email Id is harjotsingh1234@gmail.com

Regards,
Harjot Singh

**Comment by harjot-singh** [comment]
@sunny01gupta have u shared the library?

**Comment by sunny01gupta** [comment]
Hi Harjot,

I have shared library with sample project on drive.
If you have any confusion, feel free to ask me.

Thanks.

On Wed, May 11, 2016 at 9:14 PM, harjot-singh <notifications@github.com>
wrote:

> @sunny01gupta <https://github.com/sunny01gupta> have u shared the library?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/456#issuecomment-218500414>
>



-- 
*With Regards,*

*Shani Gupta*


*Software Developer*

*Growtech Solutions Pvt. Ltd.*





*23/80 Khizrabad Opp. NFCNew Delhi-110025011-26933055,011-65578993Mob.
08800752520E-mail: sunny_01gupta@yahoo.co.in
<sunny_01gupta@yahoo.co.in>            sunny.gupta@growtech.co.in
<sunny.gupta@growtech.co.in>*

**Comment by harjot-singh** [comment]
@sunny01gupta  Thanks for the help :)

**Comment by cilvet** [comment]
Hi, @vikasgrover33, may you share with us how you managed to tell the sdk to use a certain user? I am having trouble with this part

**Comment by sunny01gupta** [comment]
Hi cilvet,

Can you explain your problem?

Thanks.

**Comment by cilvet** [comment]
I am having the exact same problem as @vikasgrover33 originaly posted, I don't seem to be able to ask for a token silently since "Refresh token is not available". Maybe you can share the library with the sample project with me as well it would be nice. I am using 2.0.3-alpha btw

**Comment by cilvet** [comment]
Forgot my email: inigo.cilveti@gmail.com

**Comment by sunny01gupta** [comment]
Hi cilvet,

I have shared library with sample project on drive.

Thanks

**Comment by cilvet** [comment]
Thank you very much!

**Comment by brucemax** [comment]
Hi! I use adal-2.0.3-alpha
And when I do acquireTokenSilent() I get next error:
mCode AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED
Refresh token is failed and prompt is not allowed

Could you provide link with demo for this case or describe what i do wrong. 
My email  maximpipkin@gmail.com

**Comment by sunny01gupta** [comment]
hey brucemax,

We have fixed many bugs in their SDK.
I am sharing our demo project with your gmail account.

Thanks.

**Comment by brucemax** [comment]
Thanks. Trying sdk from disk. Now if I call 
acquireTokenSilent(String[] scope, String clientId, UserIdentifier user, AuthenticationCallback<AuthenticationResult> callback)
I get next in onError:
AUTH_FAILED_NO_TOKEN
"Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference"

In your demo as I see you use this method but with other signature.
Note: for AuthContext I provide own tokenCache wich I deserialize from my preference and I checked that it consist token and refreshToken and other info.

**Comment by sunny01gupta** [comment]
Yes brucemax,

We have passed one more argument of REDIRECT_URL because we need it in acquireTokenSilent method on AuthenticationContext class as well we have added one more parameter in same sdk method.
If you use own tokenCache so you can pass every info from your preference.

Thanks

**Comment by mifurm** [comment]
can I get the lib as well? my email is michal.furmankiewicz@hotmail.com

**Comment by sunny01gupta** [comment]
Hi Michal,

I have shared library with you.

Thanks.

**Comment by mifurm** [comment]
Sunny, I get the lib. but was able to manage and use 2.0.3 with some changes. thank you for the help!

**Comment by gavina01** [comment]
Sunny, can you please share with my account gavin.a.armitage@gmail.com. Thanks

**Comment by weijjia** [comment]
This branch of the library is going to be retired, so no new updates will be made.  Please take a look at the OSS OAuth libraries mentioned on http://aka.ms/aadb2c as a replacement.  We are working on the next gen library, the Microsoft Authentication Library (MSAL), that will work with B2C, and will be previewed later this year.

**Comment by dnyaneshwaruttarwar** [comment]
I'm getting the same issue but I'm working on ionic and I'm using **azure-activedirectory-library-for-cordova**
If anyone knows solutions please let me know
