### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State

### ISSUE THREAD

**Issue by girish878** [AzureAD/azure-activedirectory-library-for-android#457]
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more

**Comment by weijjia** [comment]
Could you provide more context for this? When does the exception happen?

**Comment by girish878** [comment]
Hi,
We are trying to build android app in Travis. We are using pom.xml to download supporting libraries for our app. We are not sure that this exception is because of "maven plugin" version. While building our android app in Travis we are getting this exception.

**Comment by weijjia** [comment]
Which version of maven you are on? It looks like maven 3.3.1 may cause the issue.

**Comment by girish878** [comment]
We are using `maven - 3.1` and `android-maven - 3.8.0`. By default Travis will use maven version 3. 
This is my `.travis.yml`:

`language: android`
`env:`
`- BRANCH_NAME=$TRAVIS_BRANCH`
`android:`
 `components:`
`# The BuildTools version used by your project`
`  - build-tools-19.1.0`
`# The SDK version used to compile your project`
`  - android-19`
`before_script:`
` - python addServer.py`
` - python modifyPom.py`
`script:`
` mvn -X clean install`

I think we need to change maven version in Travis. Can we change maven version in Travis?

**Comment by heidijinxujia** [comment]
Hi, you may need to change to Maven 3.2.3 to solve this problem. It works in my situation.

**Comment by girish878** [comment]
Thanks guys.. I found the solution. I have changed the maven version used by Travis. By default maven uses 3.2.5, I have changed it to 3.2.4.

**Comment by efalk** [comment]
I got the exact same error using mvn 3.3.9. I was trying to follow the tutorial at https://spring.io/guides/gs/maven-android/

**Comment by starfighter-ix** [comment]
Probably a little late @efalk but for others having the same problem and coming across this thread as I have, the solution is as follows:

You need to replace the plugin with groupId "com.jayway.maven.plugins.android.generation2" with "com.simpligility.maven.plugins" due to a compatibility issue.

So the new plugin is:

<plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>4.1.1</version>
                <configuration>
                    <sdk>
                        <platform>21</platform>
                    </sdk>
                    <deleteConflictingFiles>true</deleteConflictingFiles>
                    <undeployBeforeDeploy>true</undeployBeforeDeploy>
                </configuration>
                <extensions>true</extensions>
            </plugin>

**Comment by JesseChisholm** [comment]
@starfighter-ix - Thanks. Worked a treat. Now to go learn what other things can be set in the `sdk` node.

**Comment by Tim-A-Harris** [comment]
@efalk - did you ever get this to work?  I was trying to follow the same tutorial with 3.3.9 and can't get it with the original jayway or the simpligility android-maven-plugin.
