### ISSUE TITLE
acquireTokenSilent Prompts Error To refresh token

### ISSUE THREAD

**Issue by vikasgrover33** [AzureAD/azure-activedirectory-library-for-android#466]
When my access token expires i call acquireTokenSlient () to refresh the token, but my call back failed with server error response with adal ver:2.0.1-alpha.

 SERVER_ERROR:2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-IOException:https://login.microsoftonline.com/abc.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1_Patient_SignIn ver:2.0.1-alpha 
12-24 17:24:57.106 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Status code:400 ver:2.0.1-alpha
12-24 17:24:57.106 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Response is received ver:2.0.1-alpha
12-24 17:24:57.106 31903-31971/com.abc.app.patient V/Oauth: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Token request does not have exception ver:2.0.1-alpha
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth: SERVER_INVALID_JSON_RESPONSE:2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Value Bad of type java.lang.String cannot be converted to JSONObject ver:2.0.1-alpha 
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth: org.json.JSONException: Value Bad of type java.lang.String cannot be converted to JSONObject
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at org.json.JSON.typeMismatch(JSON.java:111)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at org.json.JSONObject.<init>(JSONObject.java:159)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at org.json.JSONObject.<init>(JSONObject.java:172)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.extractJsonObjects(Oauth2.java:348)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.processTokenResponse(Oauth2.java:590)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:516)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.refreshToken(Oauth2.java:380)
12-24 17:24:57.116 31903-31971/com.arkaa.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1447)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.access$500(AuthenticationContext.java:54)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext$3.call(AuthenticationContext.java:1084)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext$3.call(AuthenticationContext.java:1079)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-24 17:24:57.116 31903-31971/com.arkaa.app.patient E/Oauth:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-24 17:24:57.116 31903-31971/com.abc.app.patient E/Oauth:     at java.lang.Thread.run(Thread.java:841)
12-24 17:24:57.126 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Refresh token is not returned or empty ver:2.0.1-alpha
12-24 17:24:57.126 31903-31971/com.abc.app.patient W/AuthenticationContext: AUTH_FAILED_NO_TOKEN:2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Refresh token did not return accesstoken. ver:2.0.1-alpha Request authority:https://login.microsoftonline.com/abc.onmicrosoft.com resource:4bace7a2-16a2-4435-aa49-099e9d9519e3 clientid:4bace7a2-16a2-4435-aa49-099e9d9519e3 ErrorCode:It failed to parse response as json ErrorDescription:Value Bad of type java.lang.String cannot be converted to JSONObject
12-24 17:24:57.126 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Remove refresh item from cache:com.microsoft.aad.adal.TokenCacheKey@4de123f7 ver:2.0.1-alpha
12-24 17:24:57.136 31903-31971/com.abc.app.patient V/StorageHelper: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Starting encryption ver:2.0.1-alpha
12-24 17:24:57.136 31903-31971/com.abc.app.patient V/StorageHelper: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Encrypt version:A001 ver:2.0.1-alpha
12-24 17:24:57.146 31903-31971/com.abc.app.patient V/StorageHelper: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Finished encryption ver:2.0.1-alpha
12-24 17:24:57.146 31903-31910/com.abc.app.patient I/dalvikvm: Total arena pages for JIT: 11
12-24 17:24:57.146 31903-31910/com.abc.app.patient I/dalvikvm: Total arena pages for JIT: 12
12-24 17:24:57.146 31903-31910/com.abc.app.patient I/dalvikvm: Total arena pages for JIT: 13
12-24 17:24:57.146 31903-31910/com.abc.app.patient I/dalvikvm: Total arena pages for JIT: 14
12-24 17:24:57.176 31903-31971/com.abc.app.patient D/dalvikvm: GC_FOR_ALLOC freed 1721K, 27% free 14397K/19552K, paused 30ms, total 30ms
12-24 17:24:57.176 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Token request started ver:2.0.1-alpha
12-24 17:24:57.176 31903-31971/com.abc.app.patient V/DefaultTokenCacheStore: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Looking for id token... ver:2.0.1-alpha
12-24 17:24:57.176 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-getItemFromCache accessTokenId:TdmNZ0CGNCZXArARke1RRFWLtU8JQ5U3OvQ3r/7E9/I= refreshTokenId:qZyt1OVxs4pPMtus6Xm1Vi6cFTCug0touvJAE2hsNKc= ver:2.0.1-alpha
12-24 17:24:57.176 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-UniqueId is specified. ver:2.0.1-alpha
12-24 17:24:57.176 31903-31971/com.abc.app.patient V/TokenCacheItem: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-expiresOn:Thu Dec 24 17:28:20 GMT+05:30 2015 timeWithBuffer:Thu Dec 24 17:29:57 GMT+05:30 2015 Buffer:300 ver:2.0.1-alpha
12-24 17:24:57.186 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Checking refresh tokens ver:2.0.1-alpha
12-24 17:24:57.186 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Looking for regular refresh token. Key:Authority:https://login.microsoftonline.com/abc.onmicrosoft.com scope:4bace7a2-16a2-4435-aa49-099e9d9519e3 clientid:4bace7a2-16a2-4435-aa49-099e9d9519e3 uniqueid:null mrrt:false p:B2C_1_Patient_SignIn ver:2.0.1-alpha
12-24 17:24:57.186 31903-31971/com.abc.app.patient V/DefaultTokenCacheStore: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Looking for id token... ver:2.0.1-alpha
12-24 17:24:57.186 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Refresh token is available and id:qZyt1OVxs4pPMtus6Xm1Vi6cFTCug0touvJAE2hsNKc= Key used:com.microsoft.aad.adal.TokenCacheKey@4de123f7 ver:2.0.1-alpha
12-24 17:24:57.186 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Refresh token is available and it will attempt to refresh token ver:2.0.1-alpha
12-24 17:24:57.186 31903-31971/com.abc.app.patient V/AuthenticationContext: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Process refreshToken for Request authority:https://login.microsoftonline.com/arkaa.onmicrosoft.com resource:4bace7a2-16a2-4435-aa49-099e9d9519e3 clientid:4bace7a2-16a2-4435-aa49-099e9d9519e3 refreshTokenId:qZyt1OVxs4pPMtus6Xm1Vi6cFTCug0touvJAE2hsNKc= ver:2.0.1-alpha
12-24 17:24:57.196 31903-31971/com.abc.app.patient V/WebRequestHandler: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-WebRequestHandler thread31971 ver:2.0.1-alpha
12-24 17:24:57.196 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-HttpWebRequest send thread:31971 ver:2.0.1-alpha
12-24 17:24:57.196 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-HttpWebRequest setupConnection thread:31971 ver:2.0.1-alpha
12-24 17:24:57.196 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: client-request-id ver:2.0.1-alpha
12-24 17:24:57.196 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-OS ver:2.0.1-alpha
12-24 17:24:57.196 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-DM ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-SKU ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: Host ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-Ver ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.arkaa.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-ms-PKeyAuth ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.arkaa.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-last-endpoint ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-last-request ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.arkaa.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: x-client-last-response-time ver:2.0.1-alpha
12-24 17:24:57.206 31903-31971/com.arkaa.app.patient V/HttpWebRequest: 2015-12-24 11:54:57-fe4f88db-a533-40b3-9488-a228feff68c5-Setting header: Accept ver:2.0.1-alpha
12-24 17:25:05.416 31903-31971/com.abc.app.patient E/HttpWebRequest: SERVER_ERROR:2015-12-24 11:55:05-fe4f88db-a533-40b3-9488-a228feff68c5-IOException:https://login.microsoftonline.com/arkaa.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1_Patient_SignIn ver:2.0.1-alpha 
12-24 17:25:05.416 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:55:05-fe4f88db-a533-40b3-9488-a228feff68c5-Status code:400 ver:2.0.1-alpha
12-24 17:25:05.426 31903-31971/com.abc.app.patient V/HttpWebRequest: 2015-12-24 11:55:05-fe4f88db-a533-40b3-9488-a228feff68c5-Response is received ver:2.0.1-alpha
12-24 17:25:05.426 31903-31971/com.abc.app.patient V/Oauth: 2015-12-24 11:55:05-fe4f88db-a533-40b3-9488-a228feff68c5-Token request does not have exception ver:2.0.1-alpha
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth: SERVER_INVALID_JSON_RESPONSE:2015-12-24 11:55:05-fe4f88db-a533-40b3-9488-a228feff68c5-Value Bad of type java.lang.String cannot be converted to JSONObject ver:2.0.1-alpha 
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth: org.json.JSONException: Value Bad of type java.lang.String cannot be converted to JSONObject
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at org.json.JSON.typeMismatch(JSON.java:111)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at org.json.JSONObject.<init>(JSONObject.java:159)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at org.json.JSONObject.<init>(JSONObject.java:172)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.extractJsonObjects(Oauth2.java:348)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.processTokenResponse(Oauth2.java:590)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:516)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.Oauth2.refreshToken(Oauth2.java:380)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1447)
12-24 17:25:05.436 31903-31971/com.arkaa.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
12-24 17:25:05.436 31903-31971/com.arkaa.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
12-24 17:25:05.436 31903-31971/com.arkaa.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext.access$500(AuthenticationContext.java:54)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext$3.call(AuthenticationContext.java:1084)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at com.microsoft.aad.adal.AuthenticationContext$3.call(AuthenticationContext.java:1079)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-24 17:25:05.436 31903-31971/com.abc.app.patient E/Oauth:     at java.lang.Thread.run(Thread.java:841)

**Comment by weijjia** [comment]
can you get a fiddler trace for log for this?

**Comment by vikasgrover33** [comment]
This Log received when my access token expires, where i am calling acquireTokenSilent() to get access token every time for calling services 

Failed to get access token from refresh token, Status code:400 ver:2.0.1-alpha returned.

SERVER_ERROR:2015-12-25 07:59:53-43f3139b-5a7a-4f54-93de-cface2fa027d-IOException:https://login.microsoftonline.com/arkaa.onmicrosoft.com/oauth2/v2.0/token ver:2.0.1-alpha
2015-12-25 07:59:53-f9e6ce0a-aa8d-487b-bcb7-a30af6ebfdab-OAuth2 error:invalid_request Description:AADSTS50091: Passed query string length exceeds supported limit

**Comment by weijjia** [comment]
Same as issue #467.

**Comment by weijjia** [comment]
Closed for now. Tracking the duplicate issue #467.
