### ISSUE TITLE
Token expiring in less then 20 seconds

### ISSUE THREAD

**Issue by cmicoe** [AzureAD/azure-activedirectory-library-for-android#468]
I am using Cordova 5.4.1 version. I am able to authenticate against Azure AD but the token expiring in less than 20 seconds.

**Comment by mahmoudabogwella** [comment]
i have the same issue any updates please .

**Comment by weijjia** [comment]
@cmicoe @mahmoudabogwella Can you provide more details on it?

**Comment by cmicoe** [comment]
@weijjia : Please find the requested information from the below URL

https://social.msdn.microsoft.com/Forums/en-US/4301be9e-7722-4c0c-a0e6-75c5ea1ac081/single-sign-on-using-azure-for-web-and-mobile-applications?forum=AzureDataLake

**Comment by weijjia** [comment]
@cmicoe Is 401: unauthorised request" thrown by OWIN? Just want to make sure all the configurations are done correctly. You created the native application? When you call adal, the client id you passed is for native app? It will be nice if have logs and detailed errors.

**Comment by addev-ashish** [comment]
No updates for a while. @cmicoe let us know if you are still hitting this issue.
