### ISSUE TITLE
Prevent non http redirects in the web view 

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#474]
ADAL should ensure that all redirects that happen in the web view are SSL protected to prevent phishing attacks.

**Comment by heidijinxujia** [comment]
Do you mean AUTHORITY_URL should be SSL protected?

**Comment by heidijinxujia** [comment]
Do you mean we need to put a listener to check if the URL is SSL protected after jumping into the web view?

**Comment by heidijinxujia** [comment]
One question, do we only want to pass the "https://" or just prevent from "http://"?
