### ISSUE TITLE
ADAL should fail if permissions to use broker are not available.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#475]
If the developer has not opted out of the broker then we should fail as soon as possible if it would not be possible to invoke it.  That means we should detect early that the app does not have the necessary permissions to the Account Manager and fail, rather than falling back to the local flow.

**Comment by heidijinxujia** [comment]
In the BrokerProxy, we check the permission to Account Manager when we want to acquire token after validation. For this issue, do you mean we need to bring forward the permission checking before the validation?

**Comment by weijjia** [comment]
we should fail upfront if developer clearly choose to use broker.

**Comment by heidijinxujia** [comment]
Shipped for review last week. Thanks!

**Comment by addev-ashish** [comment]
looks like this was fixed.

**Comment by weijjia** [comment]
Why we are closing this? is the PR merged or this is a duplicate issue?
