### ISSUE TITLE
AuthenticationCallback passed in acquireToken() can reference an invalid UI causing memory leaks and NullPointerExceptions

### ISSUE THREAD

**Issue by murki** [AzureAD/azure-activedirectory-library-for-android#479]
Since the Activity/Fragment can be destroyed at anytime by Android there is a big risk of memory leaks and the app crashing when implementing AuthenticationCallback's `onSuccess()` and `onError()` methods.

The easiest way to see this is by enabling the "Don't keep actives" option on Android's Developer options. After that methods like Fragment's `isAdded()` and `getActivity()` would report an invalid state when used inside the AuthenticationCallback.

``` java
@Override
public void onCreate(Bundle savedInstanceState) {
  //...
  AuthenticationContext adalAuthContext = new AuthenticationContext(getActivity().getApplicationContext(), AUTHORITY_URL, true);
  //…
}

public void loginClick() {
  adalAuthContext.acquireToken(wrapFragment(this), RESOURCE_ID, CLIENT_ID, REDIRECT_URL, emailTextView.getText().toString(), PromptBehavior.Always, "", new AuthenticationCallback<AuthenticationResult>() { // <-- This callback holds a reference to the "original" fragment (the one used to call `startActivityForResult()`)
    @Override
    public void onSuccess(AuthenticationResult authenticationResult) {
      String token = authenticationResult.getAccessToken(); // <-- Valid token is returned, but can't be used
      Boolean isFragmentInAValidState = isAdded() && getActivity() != null; // <— This is false, which means the callback is referencing an old fragment instance effectively leaking it, and also causing all kinds of NPEs
    }

    @Override
    public void onError(Exception e) {
      //...
    }
  });
}

@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  // At this point, this is a new Fragment that has been created by Android
  super.onActivityResult(requestCode, resultCode, data);
  adalAuthContext.onActivityResult(requestCode, resultCode, data);
}
```

This issue has been discussed with @weijjia and she is looking into it.

**Comment by RandalliLama** [comment]
@murki @weijjia If we fix this will there be backward compatibility issues with apps that did not have bugs?

**Comment by murki** [comment]
@RandalliLama I think all apps are exposed to this bug (again the easy way to see it, is by enabling the dev option). 

My naive workaround would not break compatibility, it just adds an extra method overload to an existing method. 

The proper fix in my mind would require to break compatibility (i.e. would require a major version upgrade) since we should probably not be sending the `AuthenticationCallback` at all on `AuthenticationContext.acquireToken()` (and only send it on `AuthenticationContext.onActivityResult()`)

**Comment by mbelsky** [comment]
@murki I've found the issue too and I'd like to tell you that this solution has the bug too. 
`adalAuthContext.onActivityResult(…)` is asynchronous and if a user taps back/home button, gets incoming call or something other until the method working the activity or fragment can be destroyed too.

To solve this issue the library should return an `AuthenticationResult` entity in Activity's or Fragment's `onActivityResult(int requestCode, int resultCode, Intent data)` method in `Intent data` argument

Unfortunately I had no time to check how it's easy to implement the solution 😟

**Comment by weijjia** [comment]
@addev-ashish and I talked about it, the current pending pr can fix the potential leak. We can make sure that we are not holding a strong reference to the activity or fragment, But let's talk more on Monday about the potential app crash.

**Comment by murki** [comment]
@weijjia do you have a link to said pr?

**Comment by weijjia** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/722/files

**Comment by murki** [comment]
@weijjia If I'm understanding that PR correctly, it will avoid the memory leak and NPE but not address the underlying issue of not being able to resume the login operation when the navigated back to the origin Activity, meaning there is no way to react to the login result in the `onSuccess` callback

**Comment by piqiums** [comment]
Hi Miguel
   Thanks for reporting this, but I don't think it is an issue. 'AuthenticationCallback' is an interface that ADAL tell the consumer app (i.e, outlook, onenote) about the 'AuthenticationResult'. As long as the 'AuthenticationResult' is passed, then how to update the UI is beyond ADAL's scope.Let's make the border clear. The consumer apps should take care of the UI part.
1. if you found any memory leak, please dump the .hprof file first then analyze it. To analyze the mem leak, please read https://eclipsesource.com/blogs/2013/01/21/10-tips-for-using-the-eclipse-memory-analyzer/ . Though it's written years ago, the method still works great. If you find it's related with 'AuthenticationCallback' or any class in ADAL, please loop in us. 
2. for the NullPointerException, the consumer app should check the variable if necessary. 
Thanks
