### ISSUE TITLE
ResumeRequestinBroker should use account manager, and not try to launch the activity itself.

### ISSUE THREAD

**Issue by sdabbiru** [AzureAD/azure-activedirectory-library-for-android#485]
I like Rich's suggestion - let's use the account manager to get the token again. This way, there will be no need for the package name to be specified while launching the activity.

**Comment by addev-ashish** [comment]
Open new issues and then close this one.

**Comment by weijjia** [comment]
This part is done, the current open issue for resume flow is:1) remove the global broadcast receiver 2) re-launch activity actually launching the auth related activity. There are issues opened for each individual items. Close this one.
