### ISSUE TITLE
Remove Android Permission Dependency From ADAL Library

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#487]
On Android M, getBrokerUsers returns nothing even if Company Portal or Authenticator app is configured but app doesn't have GET_ACCOUNTS, MANAGE_ACCOUNTS permissions. 

In such case, either library should prompt to user to set those permissions explicitly or shouldn't depend on those permissions.

**Comment by weijjia** [comment]
We have to depend on those permissions, and client app should start requesting the run-time permission for GET_ACCOUNTS.

**Comment by weijjia** [comment]
Close for now, and let me know if you have any concerns on it.
