### ISSUE TITLE
Add "OneLog" functionality to ADAL for Android

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-android#488]
We're currently suffering from hard to diagnose issues partly due to difficulties in gathering logs from all the disparate apps using ADAL that can be interacting with each other. A background logging utility that would collect all ADAL and InTune logs would help us tremendously in quickly figuring out what's going on.

**Comment by addev-ashish** [comment]
@RPangrle we need more detail here, closing in the mean time
