### ISSUE TITLE
Logout/CookieManager Code Deprecated

### ISSUE THREAD

**Issue by bschnack** [AzureAD/azure-activedirectory-library-for-android#489]
Hello,

The logout code for ADAL is Deprecated on the latest version of Android SDK. So this code:
```
            // logout
            CookieManager cookieManager = CookieManager.getInstance();
            cookieManager.removeAllCookie();
            CookieSyncManager.getInstance().sync();
            mAuthContext.getCache().removeAll();
```

Has no guarantees that it will continue to work. According to the docs, CookieSyncManager might not be necessary and you would need to remove all cookies asynchronously.  My untested code looks like:
```
        if (Build.VERSION.SDK_INT < 21) {
                CookieSyncManager syncManager = CookieSyncManager.createInstance(
                        getContext().getApplicationContext());
                cookieManager.removeSessionCookie();
                cookieManager.removeAllCookie();
                syncManager.sync();
                AppLog.d("ADALAuth", "cookies should be cleared by now");
            } else {
                // We should not need to sync since "The WebView now automatically syncs cookies as necessary"
                cookieManager.removeAllCookies(new ValueCallback<Boolean>() {
                    @Override
                    public void onReceiveValue(Boolean value) {
                        Log.d("ADALAuth", "Has removed all cookies and received value:" + value);
                    }
                });
                cookieManager.removeSessionCookies(new ValueCallback<Boolean>() {
                    @Override
                    public void onReceiveValue(Boolean value) {
                        Log.d("ADALAuth", "Has removed all session cookies and received value:" + value);
                    }
                });
            }
```

If I end up testing it before you respond, I will make a pull request.

Thanks,
Brian

**Comment by vikasgrover33** [comment]
How can I logout from my application, what i am doing is clearing the cache, but doing this it clears all my mobile cache, which i don't want, i have some information to be there in cache.

 if (GenericRequestClass.getInstance() != null && GenericRequestClass.getInstance().mAuthenticateContext!= null
        && GenericRequestClass.getInstance().mAuthenticateContext.getCache() != null)
         GenericRequestClass.getInstance().mAuthenticateContext.getCache().clear();

Thanks
Vikas Grover

**Comment by weijjia** [comment]
What we usually suggest for logging out, is to only clear the cache for your app(client id). You can handle this on the client side, isn't it?

**Comment by addev-ashish** [comment]
@bschnack kindly reactivate if you still this is an issue.

**Comment by nhelclamor** [comment]
I'm getting "Cannot resolve method 'CookieManager.getInstance()'" please help me, I'm new in android webview. I imported import android.webkit.CookieManager; import android.webkit.CookieSyncManager; but still I'm getting error. what seems to be the problem?
