### ISSUE TITLE
Tombstone RTs instead of Removing them on server refusal

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/azure-activedirectory-library-for-android#502]
We need to use "tombstone" where we keep an entry around after a refresh token is deleted so that we can report what happened to it later when we attempt to find one. We can record that fact that it was deleted due to an error, when and from what API. That way when no refresh token is found we can tell OneDrive what happened.

**Comment by weijjia** [comment]
We're not going to do tombstone for android.
