### ISSUE TITLE
Don't call UUID.fromString() on server returned correlation ids.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#511]
There is no contract that the server must always return a guid.  And even if there was a bug it shouldn't cause an IllegalArgument exception if the server returned a non-guid.  If comparisons need to be done with locally generated guids then they should be done as case insensitive strings.

**Comment by iambmelt** [comment]
Instances of this, as of 6/20/2018

![capture](https://user-images.githubusercontent.com/990063/41687435-ae2a2df4-74b5-11e8-96f1-5fcfebf66e60.JPG)

**Comment by iambmelt** [comment]
Closing due to age. No plans to change this currently
