### ISSUE TITLE
Need to scrub exceptions and make them prescriptive

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/azure-activedirectory-library-for-android#513]
We need to make the error message more prescriptive. It should direct the developer to the readme, and we need to add a section to the readme that explains the issues around invoking the broker.

We need to track the need to scrub exceptions and make them prescriptive and point to documentation that can help the developer figure out what they need to change.

**Comment by addev-ashish** [comment]
Being done across all ADALs, tracked externally
