### ISSUE TITLE
MSA Desktop View instead of Mobile View

### ISSUE THREAD

**Issue by bschnack** [AzureAD/azure-activedirectory-library-for-android#515]
If I try to log into an MSA account using a common domain name (@google.com, @outlook.com, @yahoo.com, etc) it takes me to the desktop version of MSA login. However, if I use an unknown domain name (@olook.com) it takes me to the mobile version of MSA login. It should always take me to the mobile version of MSA login though.

**Comment by weijjia** [comment]
This looks like an service side issue.

**Comment by addev-ashish** [comment]
Not an ADAL issue.
