### ISSUE TITLE
FoCI scenarios open for discussions

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#525]
Pre-requisite:
App A and App B, A and B are in the same family. 

1. App A found its own refresh token, and use it to redeem AT. But the refresh token request failed, should App A try to use RT from its family?
Today, our design for FoCI cache look up is: 1) try to find regular RT for app itself 2) If nothing is found in 1, will try to find MRRT 3) If nothing is found in 2, will try to find family item. 

2. If App A doesn't have it's own RT, App A found a RT from it's family app App B, but the refresh token fails, App A will be prompted for username and password again. The discussion here is should we delete the RT for app B. Our current logic is, we shouldn't. Event the two apps are in the same family, but app A should delete app B's token.

**Comment by weijjia** [comment]
@imakhalova Anything else you want to add?

**Comment by imakhalova** [comment]
The main concern is that there is some scenario when Application A will prompt for credentials when B has account signed it. And this is regression for them (without familyId this scenario would never happen to them).

**Comment by weijjia** [comment]
@imakhalova You raised a good point, if App A found a RT but the refresh token request fails, it should retry with the refresh token from its family. But we don't have time for this yet, and this needs to be changed across ADAL platform supporting FoCI. We're in the middle of security push, and we should be able to come back later to address this. @RandalliLama FYI

**Comment by addev-ashish** [comment]
The new foci design will store separate entries for foci, in CR now.
