### ISSUE TITLE
library versioning

### ISSUE THREAD

**Issue by twentynothing** [AzureAD/azure-activedirectory-library-for-android#540]
https://github.com/AzureAD/azure-activedirectory-library-for-android/releases/tag/v1.1.14
This release breaks default API behavior. It should at least have a minor version bump. 

Also it seems that 1.1.14 aar is packed differently, causing gradle unable to find the classes.jar file at the expected path. Try create a test app that uses adal 1.1.14.

**Comment by weijjia** [comment]
thanks @twentynothing. @heidijinxujia is investigating it.

**Comment by heidijinxujia** [comment]
@twentynothing  Thank you for your contribution. It is fixed now.
