### ISSUE TITLE
Broker and runtime permissions (API 23)

### ISSUE THREAD

**Issue by sgrebnov** [AzureAD/azure-activedirectory-library-for-android#554]
[canSwitchToBroker](
https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/de9ec87f3d09310a735d371b959f75e1d3b89fa4/src/src/com/microsoft/aad/adal/BrokerProxy.java#L107) always returns `false` when I target Android SDK 23.

This happens due to `verifyManifestPermissions` test does not pass. I confirm requried permissions are in manifest file and this works correct when I changing target SDK to 22 or earlier.

Please verify

**Comment by weijjia** [comment]
for API 23, GET_ACCOUNTS is a runtime permission. You need to start requesting the runtime permission.

**Comment by sgrebnov** [comment]
Should ADAL library be responsible for checking if permission is granted or not and triggering permission prompt?

**Comment by weijjia** [comment]
The long term plan is to remove the dependency on account manager for broker, then we don't need those permissions. For now, we totally rely on calling app itself to request the permission.

**Comment by sgrebnov** [comment]
Makes sense

**Comment by sgrebnov** [comment]
Taking into account there is explicit method `setUserBroker` to tell ADAL should ADAL library be on response for asking for required runtime permissions?

**Comment by weijjia** [comment]
We don't have the plan for requesting the permission yet. As I mentioned before, the long term plan is to remove the dependency on account manager.
