### ISSUE TITLE
No way to close Dialog

### ISSUE THREAD

**Issue by bluehallu** [AzureAD/azure-activedirectory-library-for-android#557]
When using Dialog-based interactive flow, there is no way to close the current Dialog. I'm calling acquireToken inside onResume() and all works well, except if the user minimises the app and opens it again while the Dialog is present (i.e: to open a password manager) then two Dialogs are stacked on top of each other.

**Comment by nazukj** [comment]
This sounds like a user bug and not a library issue. Wont Fix.

**Comment by bluehallu** [comment]
@nazukj I think you missunderstood. By two dialogs I mean, two identical dialogs coming from the azure library.

**Comment by nazukj** [comment]
Happy to reopen issue if you can please provide us with detailed repro steps, version of the library you're seeing the issue on and logs. Screenshots would be very helpful as well to gauge the issue.

**Comment by bluehallu** [comment]
@nazukj Given it's been over a year since I opened the issue that's going to prove very difficult. I no longer have access to the project that had the issue, however I think the description is quite explicit. 

"When using Dialog-based interactive flow, there is no way to close the current Dialog"

By no way I mean, the library doesn't provide any means to do it, no that the functionality is broken.

**Comment by nazukj** [comment]
Ok. We'll try a repro on our side.

**Comment by nazukj** [comment]
Closing issue. Please reopen if it still exists

**Comment by bluehallu** [comment]
So, how do I close the dialog?
