### ISSUE TITLE
Auth prompt incorrectly informs users that MSA is supported, even when not

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#563]
I've registered an application on https://manage.windowsazure.com

This application requires the following permissions:

- Sign in and read user profile
- Have full access to user files and files shared with user
- Have full access to user calendars
- Read and write access to user mail
- Send mail as a user
- Read user mail
- Read and write directory data
- Read all users' basic profiles
- Read and write all groups

When using `ADAL 1.1.11` it prompts me to log in w/ the following information

![device-2016-03-28-145011](https://cloud.githubusercontent.com/assets/990063/14091317/72946d74-f4f4-11e5-9330-96df716d743c.png)

But this auth can't work w/ MSA, right? Because it wasn't registered using the [converged-auth registration portal](https://apps.dev.microsoft.com)? 

ADAL seems to be showing the wrong sign-in. AFAIK this can only work with work/school accts...

**Comment by weijjia** [comment]
It will work with guest account. Also, this page is not controlled by adal, aad display the sign-in page.

**Comment by addev-ashish** [comment]
@iambmelt What authority are you passing in to the Authentication Context?

**Comment by weijjia** [comment]
Service issue, close for now.
