### ISSUE TITLE
No way to distinguish between different  BROWSER_ERROR_CODE

### ISSUE THREAD

**Issue by dbahat** [AzureAD/azure-activedirectory-library-for-android#569]
Looking inside AuthenticationContext.java (and in our telemetry), we can see SERVER_INVALID_REQUEST returned from Adal as the error code whenever onActivityResult is invoked with BROWSER_ERROR_CODE, which in our traces we see has many reasons (one of them being the un-trusted root CA on the corporate STS, others are just timeouts, cache miss, un-resolvable names, etc...).
In AuthenticationContext, line 843 I see you perform the following in case of BROWSER_ERROR_CODE:

waitingRequestOnError(waitingRequest, requestId, 
new AuthenticationException(ADALError.SERVER_INVALID_REQUEST, errCode + " " + errMessage 
- correlationInfo));

Unfortunately, this means we cannot access the errCode without having to parse errMessage, which we were hoping to avoid.
In such cases, the errCode should be propagated back to the caller.

Some examples of errors Adal propagate to the caller with a generic SERVER_INVALID_REQUEST error codes:
  "errorDetails": "Error Code:-1 net::ERR_CACHE_MISS",
  "errorDetails": "Code:-11 primary error: 3 certificate: Issued to:..."
  "errorDetails": "Error Code:-2 net::ERR_NAME_NOT_RESOLVED",
  "errorDetails": "Error Code:-8 net::ERR_CONNECTION_TIMED_OUT",

**Comment by nazukj** [comment]
Will be solved when we pass sub error code from server.
