### ISSUE TITLE
Breaking change in 1.1.15. AuthenticationException is now a checked exception, it was un-checked previously

### ISSUE THREAD

**Issue by Ricalo** [AzureAD/azure-activedirectory-library-for-android#578]
Hi,

You introduced a breaking change in v1.1.15.

By making `AuthenticationException` inherit from `Exception` you are effectively requiring the developers to check for this Exception. If they didn't, then their code breaks when they try to update to v1.1.15

Look at `AuthenticationException` class in this [compare view](https://github.com/AzureAD/azure-activedirectory-library-for-android/compare/ea39f50d44a401f1e9a0647853df446270f6c1d2...96cd347e6329fc666db85b349c2e626163e10da2).

Or just this image highlighting the change.
![2016-04-08_10-32-22](https://cloud.githubusercontent.com/assets/989368/14392302/8af28412-fd75-11e5-8426-6eb36e865da9.png)

This should  not be a *revision* number update. Since this breaks existing code, this should be added to your next *major* update.

**Comment by imakhalova** [comment]
Hello,
Thank you so much for your feedback. Sorry, that we didn't set version to 1.2.0 as we probably should have to.
You're right, this is build break change, but if your app wasn't catching this exceptions before this change, it could easily get runtime exception and your app will crash. So we see a big benefit of notifying user that method can throw an exception.

**Comment by Ricalo** [comment]
Thanks for the explanation, @imakhalova. My app wasn't catching this exception because it's handling the **onError** method of the callback.

What is the purpose of having a duplicated error handling code in client apps? With this change, my app has to handle errors in the **onError** method of the callback and also set a *try/catch* statement for **AuthenticationException**.

I think this should serve different purposes, but right now it seems like you could just report an error either way, and developers have to check for both of them. It seems like duplicated work for client apps.

**Comment by imakhalova** [comment]
Thank you so much for following back with us, your feedback is very important for us.
There are 2 major interfaces that this library provides: 
1 is async call which will return error in callback.onError method 
2 is sync method which doesn't have callback but throws AuthenticationException in case of error 
So if you're using async methods they do not require any change, as for sync method they do require try/catch statement.
So if library upgrade showed that you need to add try/catch method it means that you have some sync method that throws an exception. 
If you see that requirement for some methods that has callback, please let us know, this actually should never be the case. Which method returns exception in callback and throws exception for you?

**Comment by Ricalo** [comment]
Yes, I can see that now. My team has been working with the ADAL library for quite some time and I expected the code to just keep working.

However, the change looks like a step in the right direction. Just the versioning was confusing.

I'm happy to see this repo is active and well maintained.
Thanks for all the clarification!

**Comment by weijjia** [comment]
@Ricalo Yup, it's our bad to not update the version correctly for causing the confusion. Also thank you @imakhalova  for the explanation.
