### ISSUE TITLE
test service for getting challenges is down.  Need to remove that dependency.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#579]
The site:

https://graphtestrun.azurewebsites.net/api/WebRequestTest

was created to return 401 pkeyauth challenges, and a few other things.  It seems to be used exclusively for WebRequestHandlerTests.java.  The site is now down and we are no longer able to manage it.  We need to remove this test dependency on an outside web service and replace it with a mock or something.

**Comment by weijjia** [comment]
Done with latest tests change in dev.
