### ISSUE TITLE
StorageHelperTests:testKeyPair test can't work.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#580]
This test is currently failing for me, and I don't see how it could have ever worked.  There doesn't appear to be anything in the test file that would place any keypairs in the KeyStore.  The setup method passes in an explicit key which causes StorageHelper to bypass creating and storing a key in the KeyStore.

The only way that I can see that this might have worked is if it is run on a device where a keypair was previously created by a test app.

I am going to disable it for now.

**Comment by heidijinxujia** [comment]
Merged into dev branch.
