### ISSUE TITLE
On tablet rotation, white screen is shown

### ISSUE THREAD

**Issue by V1rus999** [AzureAD/azure-activedirectory-library-for-android#586]
Hi.

Device:
Tablet, Phone

Issue:
When you rotate on the initial white loading screen (when trying to fetch the first token), the loading dialog disappears and you are left with a white blank page. You need to exit the activity and try again to fix this.

Expected behavior:
On rotate it should probably just reload the page or even keep the state of the loading dialog.

**Comment by weijjia** [comment]
Can you share how you declare AuthenticationActivity in manifest?

**Comment by V1rus999** [comment]
Hi.

`        <activity
            android:name="com.microsoft.aad.adal.AuthenticationActivity"
            android:label="@string/app_name" />`

This is how we do it. We can't block the rotation as we still want rotation to happen. When the webview is done loading and you rotate, everything is fine. It is just before the webview is done.

**Comment by weijjia** [comment]
Have you tried to add this android:configChanges="orientation" in the manifest for AuthenticationActivity?

**Comment by addev-ashish** [comment]
@V1rus999 Was your issue solved? If not, kindly activate this issue again.
