### ISSUE TITLE
Adal version 2.0.1-alpha-Multiple Caching Issue

### ISSUE THREAD

**Issue by harjot-singh** [AzureAD/azure-activedirectory-library-for-android#602]
Hi,
I am able to fetch the token using adal android 2.0.1 -alpha but fetching the token next time from cache gives multiple caching issue Used the following steps
- Once the token is fetched ,it is getting saved in cache inside setItemToCache() of AuthenticationContext.java. PFB the snippet from Library

```
TokenCacheItem cacheItem = new TokenCacheItem(request, result, result.getIsMultiResourceRefreshToken());
            mTokenCacheStore.setItem(key, cacheItem); 

           // Record idtoken with clientid as scope
            if(request.isIdTokenRequest()){
                cacheItem.setScope(new String[]{request.getClientId()});
                key.setScope(new String[]{request.getClientId()});
                mTokenCacheStore.setItem(key, cacheItem);
            }
```
- Since scope is used as clleintid the above condition is satisfied and same item is cached twice While debugging saw that mTokenCacheStore has 2 items with same key and value.
- Next time when token is fetched using ADAL cache got the exception 'Multiple entries in the cache for key...'

**Comment by harjot-singh** [comment]
@weijjia @brandwe  Please share your understanding on above

**Comment by weijjia** [comment]
@harjot-singh Do you still have the issue? The latest version on b2c has already fixed it.

**Comment by weijjia** [comment]
Haven't heard back for a while, close the issue for now.
