### ISSUE TITLE
Samsung Galaxy Note 3 - could not generate key

### ISSUE THREAD

**Issue by pradeepkumargali** [AzureAD/azure-activedirectory-library-for-android#618]
On Samsung Galaxy Note 3 (http://www.samsung.com/us/mobile/cell-phones/SM-N900AZKEATT-specs) - Android 5.0, I am seeing the following error. 

E/StorageHelper(16882): java.lang.IllegalStateException: could not generate key in keystore
E/StorageHelper(16882):     at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
E/StorageHelper(16882):     at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
E/StorageHelper(16882):     at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:525)
E/StorageHelper(16882):     at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:447)
E/StorageHelper(16882):     at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:163)
E/StorageHelper(16882):     at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:275)
E/StorageHelper(16882):     at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:107)
E/StorageHelper(16882):     at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:182)
E/StorageHelper(16882):     at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1506)
E/StorageHelper(16882):     at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1486)
E/StorageHelper(16882):     at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:58)
E/StorageHelper(16882):     at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:828)
E/StorageHelper(16882):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/StorageHelper(16882):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/StorageHelper(16882):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/StorageHelper(16882):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/StorageHelper(16882):     at java.lang.Thread.run(Thread.java:818)
V/StorageHelper(16882): 2016-05-06 13:30:24-1363b8ff-8fe8-4fc4-ac4b-39bbd69ebe1a-Encryption will use secret key from Settings ver:1.1.12
E/DefaultTokenCacheStore(16882): ENCRYPTION_FAILED:2016-05-06 13:30:24-1363b8ff-8fe8-4fc4-ac4b-39bbd69ebe1a-Encryption failure ver:1.1.12 
E/DefaultTokenCacheStore(16882): java.lang.IllegalArgumentException: rawBytes
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.StorageHelper.getSecretKey(StorageHelper.java:229)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:174)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:275)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:107)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:182)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1506)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1486)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:58)
E/DefaultTokenCacheStore(16882):    at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:828)
E/DefaultTokenCacheStore(16882):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/DefaultTokenCacheStore(16882):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/DefaultTokenCacheStore(16882):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/DefaultTokenCacheStore(16882):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/DefaultTokenCacheStore(16882):    at java.lang.Thread.run(Thread.java:818)
E/DefaultTokenCacheStore(16882): ENCRYPTION_FAILED:2016-05-06 13:30:24-1363b8ff-8fe8-4fc4-ac4b-39bbd69ebe1a-Encrypted output is null ver:1.1.12 

Please help.

**Comment by weijjia** [comment]
Please check the wiki https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
