### ISSUE TITLE
RefreshToken is empty in response to acquireToken if CompanyPortal/Azure Authenticator App is installed

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#619]
If Company Portal App/Azure Authenticator app is installed then ADAL library returns empty refresh token in response to acquireToken while if those apps are not installed then library returns valid refresh token.

Expected: Library should always returns valid refresh token.

**Comment by weijjia** [comment]
This is the agreement the sdk has with Broker. Broker never return refresh token back to ADAL. Just out of curiosity, why do you care if the RT is returned? As an app, all you should care is AT. If you want to get token silently, ADAL manages the logic to find RT and use RT to get new AT.

**Comment by talk2arpit** [comment]
In MDM less MAM solution, enroll method takes RT, which is their SDK contract and fails in case Broker app is installed so I talk to SDK owner if that is supported scenario or not and update this bug,

**Comment by talk2arpit** [comment]
AS per Broker app contract, this is not needed so closing this bug.
