### ISSUE TITLE
acquireTokenSilentSync should throw NetworkOnMainThreadException if invoked on UI thread

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#622]
it's not allowed to make network call on Main thread
Even if implementation creates another thread in executor we shouldn't allow to use this method on main thread

**Comment by Ricalo** [comment]
Hi @imakhalova 

Does this mean that client apps would have to call **acquireTokenSilentSync** from a non-UI thread?

I think this is the right thing to do. I'm just trying to understand how to use the API and see if this is going to be a breaking change in customers' apps.

Thank you

**Comment by imakhalova** [comment]
Yes, it actually means that acquireTokenSilentSync must be invoked only from non-UI thread.
Moreover it's not recommended in Android having blocking network calls on UI thread in order to provide good user experience and avoid ANR dialog
http://developer.android.com/training/articles/perf-anr.html

Since this might a breaking change this change will come in next major release.

Regards,
Irina

**Comment by nazukj** [comment]
This is a breaking change and cannot be made on current release. The recommendation here is to not make a synchronous call on main thread. Wont Fix.
