### ISSUE TITLE
When broker just installed user silent request fails

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#623]
If app was using cache it will receive prompt isn't allowed for new broker app that has UI for sign in flow.

**Comment by weijjia** [comment]
Working on it, favoring local cache will look up local cache first, if there is a AT for the user with the given resource, we'll return the AT. If there is a RT, we'll use the RT to get a new AT. If AT is not returned successfully, and we can talk to broker, we'll switch to broker for auth.

**Comment by weijjia** [comment]
Merged with PR #655.
