### ISSUE TITLE
Telemetry around encryption

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#624]
Need a way to gather statistics that acquire new token failed because it wasn't able to decrypt token from cache

**Comment by weijjia** [comment]
Working on it, see https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/607
Adding telemetry events for Encryption, Decryption and also the AndroidKeyStore failure.

**Comment by weijjia** [comment]
Merged with the reference PR. Let me know if you have any concerns. :) Closed for now
