### ISSUE TITLE
Returns user cancelled instead of access denied error, when AD FS denies access because the device couldn't do device authn.

### ISSUE THREAD

**Issue by sdabbiru** [AzureAD/azure-activedirectory-library-for-android#625]

**Comment by weijjia** [comment]
@sdabbiru Can you elaborate a little bit more on this?

**Comment by sdabbiru** [comment]
When AD FS denies access, ADAL's webview navigation comes to a halt until timeout occurs or the user cancels the request. I wonder whether ADAL ever knows that AD FS denied access.

**Comment by weijjia** [comment]
@sdabbiru Do you actually see this happening? ADAL today translated all the error if we get any from redirect back to cancel webrequest. So if ADFS sends the access denied as an extra qp, we'll cancel the request. If you actually see this happening, please forward logs to us.

**Comment by weijjia** [comment]
I'm closing this unless there are more details provided. If ADFS sends back us the error and error_description as qp in the redirect, adal will initiate the cancel request. I don't understand what do you mean by "navigation comes to a halt until timeout". What do you mean by the timeout? Is it timeout in the webview or? We'll look into it more when more details are provided.
