### ISSUE TITLE
Provide API to invalidate access token

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#627]
Scenario: Service returned error that access token is invalid, but it doesn't mean that refresh token isn't valid. We should be able to invalidate access token and try to obtain new one.

Real life scenario: user switched password, our Cookie server responded that access token isn't valid, but when we sign in again, it will get access token from cache until it expires and user won't be able to sign in.

**Comment by weijjia** [comment]
Good call, if user change the password within one hour, we'll have the AT in the cache.  I think maybe we should always just use RT to get a new AT.

**Comment by imakhalova** [comment]
I don't think it's good idea, I would prefer ability to remove token when it's invalid or remove old access tokens after I was prompted for UI, or ability to remove all tokens when user got signed out.
But I leave this design up to you

**Comment by weijjia** [comment]
I'll follow up with server side, access token is just a bearer token, even user changes the password, it shouldn't be invalidated.

**Comment by imakhalova** [comment]
Keep in mind that it's not for all services.
But cookie API tends to be more aggressive on validating the token rather than just decoding it, and the API somehow is aware of the password change and deems the token is not up to date any more
The AuthInstant is extracted from the token. If you are not refreshing the token, then you will keep failing.

**Comment by imakhalova** [comment]
Is there any news on that? We still need this feature for iOS and Android

**Comment by weijjia** [comment]
@imakhalova Sorry for getting back to you late on this. Access token is a bearer token, service should not invalidate it. I think we need more info on why the API knows that user has changed the password and deems it as invalid token before we provide the API to do this. @addev-ashish FYI

**Comment by imakhalova** [comment]
Which info do you need from me?

**Comment by weijjia** [comment]
We need to know what is the API that rejects access token.

**Comment by brentschmaltz** [comment]
We shouldn't get hung up on why the access_token was rejected.

**Comment by imakhalova** [comment]
Here is API that rejects access token when you changed password:
POST /_api/SP.OAuth.NativeClient/Authenticate HTTP/1.1
Host: mod106297.sharepoint.com
Content-Length: 0
Connection: keep-alive
X-IDCRL_ACCEPTED: t
Proxy-Connection: keep-alive
Accept: */*
User-Agent: SharePoint for iOS/v1.6.0.b6630.Debug (iOS/9.3.0;en;Apple/x86_64)
Accept-Language: en;q=1.0
Authorization: Bearer HERE_WAS_VALID_CACHED_TOKEN
Accept-Encoding: gzip;q=1.0, compress;q=0.5

HTTP/1.1 403 Forbidden
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/xml;charset=utf-8
Expires: Sun, 28 Aug 2016 22:50:51 GMT
Last-Modified: Mon, 12 Sep 2016 22:50:51 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 143
X-AspNet-Version: 4.0.30319
SPRequestGuid: 562ca39d-a060-3000-9fd2-20870d5d5fea
request-id: 562ca39d-a060-3000-9fd2-20870d5d5fea
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5701
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Mon, 12 Sep 2016 22:50:50 GMT

<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.Client.ClientServiceException</m:code><m:message xml:lang="en-US">Exception of type 'Microsoft.SharePoint.Client.ClientServiceException' was thrown.</m:message></m:error>

**Comment by nazukj** [comment]
Won't fix. This will be supported in V2.
