### ISSUE TITLE
Web view loses state on device rotation

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#633]
If user got 2nd factor auth:
1) input password and click sign in
2) web view asks you to insert pin
3) rotate screen
expected: that it waits for pin
result: it starts process over again and you have to input password

**Comment by weijjia** [comment]
Do you have "android:configChanges="orientation" in manifest for AuthenticationActivity?

**Comment by nazukj** [comment]
Not a library issue. Should be resolved with Wei's comment above. Please reactivate if you disagree. :)
