### ISSUE TITLE
Login dialog suddenly terminates with no callback

### ISSUE THREAD

**Issue by VirtuallyInvincible** [AzureAD/azure-activedirectory-library-for-android#641]
Hello.

I'm using the latest version of your Android library via Gradle bins:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.microsoft.aad:adal:1.1.18'
    ...
}

I re-installed the app on one of my devices and as it starts, I see the login dialog on top of the splash screen as I usually do. The login dialog is empty (completely white) with the progress dialog on top of it. This much is usual. However, all of a sudden, the dialog and the progress dialog terminate and no callback is reached (I did set breakpoints in the onSuccess() and onError() method calls and while in debug mode, the breakpoints aren't reached). This only happens for a Samsung Galaxy 5 device and only started today. Why?

Thanks in advance.

**Comment by caltseng** [comment]
+1

**Comment by LogcatTiger** [comment]
Thanks but can you please elaborate some more? You mean a method of the azure library has been called from my code when I was not logged in causes the dialog to be closed?

**Comment by weijjia** [comment]
We'll need you to share more info i.e. logs for us to further investigate.

**Comment by nazukj** [comment]
Please update to latest version and reactivate (with logs) if you still see the issue. Thanks!
