### ISSUE TITLE
Unit test failures caused by the packageName

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/azure-activedirectory-library-for-android#645]
There are five tests failures cause by the getPackageName().
- testBrokerRedirectUri
- testEmptyRedirect
- testCacheItemRetrieval
- testDateTimeFormatterOldFormat24hourFormat
- testDateTimeFormatterOldFormatWithAMOrPM

**Comment by weijjia** [comment]
This is already fixed, close the issue.
