### ISSUE TITLE
DCR: Provide a test hook so code outside of ADAL can access webview's HTML elements using IDs

### ISSUE THREAD

**Issue by sdabbiru** [AzureAD/azure-activedirectory-library-for-android#646]
Right now, inTune's test automation uses tab order which is fragile. They need a different way (access elements by ID) to drive the interactive sign-in using test automation.

**Comment by weijjia** [comment]
On 4.4+, webview provides the static method setWebContentsDebuggingEnabled to enable debugging of web contents loaded into webviews by the application. App can enable it when it's created.
