### ISSUE TITLE
DefaultTokenCacheStore.getTokensForResource() returns duplicate entries

### ISSUE THREAD

**Issue by murki** [AzureAD/azure-activedirectory-library-for-android#656]
I'm calling the `getTokensForResource()` method while using the `DefaultTokenCacheStore` inside the `AuthenticationContext` after a successful AAD login, and even though I'm providing the unique resourceId used to authenticate our app this methods returns (what appears to be) identical entries, in my case it's returning three of them.

Code snippet (put after successful login):
```java
  int tokenCount = 0;
  ITokenCacheStore adalCache = authenticationContext.getCache();
  if (adalCache != null && adalCache instanceof DefaultTokenCacheStore) {
    List<TokenCacheItem> tokens = ((DefaultTokenCacheStore) adalCache).getTokensForResource(adalConfigRepository.getResourceId());
    if (tokens != null && tokens.size() > 0) {
      Log.d("TAG", "tokenCount=" + tokens.size()); // this will always print 3
    }
  }
```

This is using v1.2.0.

**Comment by addev-ashish** [comment]
@murki what are you trying to achieve here? We do not expect anyone to be using the DefaultTokenCacheStore class. Its an internal implementation detail that we do not expect any of our customers to have to use. 
A guide on how to use our library is https://github.com/AzureAD/azure-activedirectory-library-for-android#how-to-use-this-library. Kindly let us know if there is a need that the standard usage does not provide for you.

**Comment by murki** [comment]
@addev-ashish thanks for your reply. 

Irregardless of using `DefaultTokenCacheStore.getTokensForResource()` or just iterating through the results of `ITokenCacheStore.getAll()` and filtering by our resourceId manually we still get the same 3 repeated entries. The bug appears to be in the way you generate the keys for the entries stored in `com.microsoft.aad.adal.cache.xml` since they are not unique (even though they contain the same information).

(Note: `DefaultTokenCacheStore` is explicitly marked as public, if it is meant to be an internal implementation detail why not mark it as package-private?)

**Comment by weijjia** [comment]
I think we had offline discussions via emails. The right behavior we propose is that app itself keeping track of the signed in user and maintain the "signed-in user list". Closing the issue for now. Re-open it if you have any other questions around it. Thanks. :)
