### ISSUE TITLE
Server response is not traced 

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#670]
It would be nice to trace what server responded if it didn't return token in response.
Currently it looks something like this:
HttpWebRequest: SERVER_ERROR:2016-07-05 16:32:20-e5951c6c-c38c-4190-9868-7ac1f6e8a75d-IOException:https://login.windows.net/common/oauth2/token ver:1.2.1 
HttpWebRequest: 2016-07-05 16:32:20-e5951c6c-c38c-4190-9868-7ac1f6e8a75d-Response is received ver:1.2.1
Oauth: 2016-07-05 16:32:20-e5951c6c-c38c-4190-9868-7ac1f6e8a75d-Token request does not have exception ver:1.2.1

**Comment by weijjia** [comment]
@imakhalova In our logger, you'll get back message and additional message, we return the detailed error in the additional part. I also check the log file you sent to me last time via email, if server returns back the error and error_description, we do return it back and it's logged in the additional message. Can you check if oneDrive also log the message in additional part?

**Comment by imakhalova** [comment]
I see, thanks
