### ISSUE TITLE
In Network failures, Library sends SERVER_INVALID_REQUEST instead of DEVICE_CONNECTION_IS_NOT_AVAILABLE

### ISSUE THREAD

**Issue by talk2arpit** [AzureAD/azure-activedirectory-library-for-android#672]
While loading any web page if OS detect any network issue and gives callbacks at BasicWebView.onReceivedError, library returns SERVER_INVALID_REQUEST to caller,

Here is the log:

05-16 12:43:03.463  1933  1933 E BasicWebViewClient: ERROR_WEBVIEW:2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Webview received an error. Errorcode:-6 net::ERR_CONNECTION_RESET ver:1.1.18

05-16 12:43:03.467  1933  1933 V AuthenticationActivity: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Return To Caller:2002 ver:1.1.18

05-16 12:43:03.471  1933  1933 V AuthenticationActivity: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-displaySpinner:false showing:false ver:1.1.18

05-16 12:43:03.475  1933  1933 V AuthenticationActivity: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Return To Caller REQUEST_ID:-1515218496 ver:1.1.18

05-16 12:43:03.479  1933  1933 V BasicWebViewClient: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Page finished: *************************\* ver:1.1.18

05-16 12:43:03.499  1933  1933 V BasicWebViewClient: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Page finished:data:text/html,chromewebdata ver:1.1.18

05-16 12:43:03.507  1933  1933 V AuthenticationActivity: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-AuthenticationActivity onPause unregister receiver ver:1.1.18

05-16 12:43:03.511  1933  1933 V AuthenticationActivity: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Spinner at onPause will dismiss ver:1.1.18

05-16 12:43:03.511  1933  1933 D LifecycleMonitor: Lifecycle status change: com.microsoft.aad.adal.AuthenticationActivity@a5a69508 in: PAUSED

05-16 12:43:03.667  1933  1933 I AppHost.Android: onActivityResult called with requestCode: 1001, Number of listeners: 1

05-16 12:43:03.679  1933  1933 V AuthenticationContext: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Get waiting request: -1515218496 ver:1.1.18

05-16 12:43:03.683  1933  1933 V AuthenticationContext: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-onActivityResult RequestId:-1515218496 ver:1.1.18

05-16 12:43:03.687  1933  1933 V AuthenticationContext: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Error info:Error Code:-6 net::ERR_CONNECTION_RESET for requestId: -1515218496 CorrelationId: 6b61d27b-1168-4c92-b6ec-a9810a792194 ver:1.1.18

05-16 12:43:03.691  1933  1933 V AuthenticationContext: 2016-05-16 19:43:03-a7e5ea80-1431-43a5-8995-5ffdf9e94251-Sending error to callback CorrelationId: 6b61d27b-1168-4c92-b6ec-a9810a792194 ver:1.1.18

05-16 12:43:03.691  1933  1933 W ADALAccountManager: Error Code:-6 net::ERR_CONNECTION_RESET CorrelationId: 6b61d27b-1168-4c92-b6ec-a9810a792194

05-16 12:43:03.691  1933  1933 E K2_ULS a9z8z ADAL Authentication: ADALError {"Error": "SERVER_INVALID_REQUEST", "ErrorDescription": "Error Code:-6 net::ERR_CONNECTION_RESET CorrelationId: 6b61d27b-1168-4c92-b6ec-a9810a792194"}

**Comment by weijjia** [comment]
This is by design. Before we sent out any authorize or token request, we'll check nextwork conncetion, if it's not available, we throw out the nextwork_not_available. If the error is returned from webview itself, we treat it as server_invalid_request.
