### ISSUE TITLE
Add API that allows apps to report app name and version for telemetry.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-android#674]
It would be helpful to be able to identify which apps have which version of ADAL so that we can identify apps that should be updated.

Do not implement this until we have agreement on the shape of the public API changes.

**Comment by iambmelt** [comment]
Application `name` and `version` is tracked [here](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/telemetry/java/com/microsoft/aad/adal/DefaultEvent.java#L61-L62).

Closing. /cc @nazukj
