### ISSUE TITLE
ADAL will crash on downloaded but disabled certificate on Android

### ISSUE THREAD

**Issue by clintyoung123** [AzureAD/azure-activedirectory-library-for-android#690]
ADAL will crash on downloaded but disabled certificate on Android

for detail log, contact and bug opened in product team, please refer to VSO item following the url below: 
Bug 630856: [ADAL][Certificate] SFB crash after kill app then uncheck/disable Baltimore certificates then try to launch again

log:
153 07-28 14:56:27.732 20455 21236 E AndroidRuntime: FATAL EXCEPTION: pool-14-thread-1
154 
155 07-28 14:56:27.732 20455 21236 E AndroidRuntime: Process: com.microsoft.office.lync15, PID: 20455
156 
157 07-28 14:56:27.732 20455 21236 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.microsoft.aad.adal.HttpWebResponse.getStatusCode()' on a null object reference
158 
159 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.Discovery.sendRequest(Discovery.java:201)
160 
161 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.Discovery.queryInstance(Discovery.java:158)
162 
163 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.Discovery.isValidAuthority(Discovery.java:115)
164 
165 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.AuthenticationContext.validateAuthority(AuthenticationContext.java:1563)
166 
167 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1247)
168 
169 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.AuthenticationContext.access$900(AuthenticationContext.java:73)
170 
171 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at com.microsoft.aad.adal.AuthenticationContext$7.run(AuthenticationContext.java:1220)
172 
173 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
174 
175 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
176 
177 07-28 14:56:27.732 20455 21236 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)

**Comment by weijjia** [comment]
This is already fixed in the latest adal version 1.10.0. Please re-open the issue if you see it happen again.
