### ISSUE TITLE
Provide handle to control the loading spinner 

### ISSUE THREAD

**Issue by msmoosa** [AzureAD/azure-activedirectory-library-for-android#691]
For accounts that have 2 factor authentication, after entering username, password, AuthenticationActivity waits for user to enter the pin on his phone. At this point, the Loading Spinner hides the message asking the user to check for 2 factor auth (Check screenshot). This seems to be a valid concern from the user’s perspective, when the app says ‘Loading…’, he’s expecting the app to do something. So they don’t check for auth requests and are unable to login.

![screenshot_20160711-220417](https://cloud.githubusercontent.com/assets/19523487/17364033/6ea3d3a6-599b-11e6-94c2-1338d7dab2d6.png)

I checked the code for AuthenticationActivity from github

@Override
protected void onResume() {
    super.onResume();
    Logger.v(TAG, "onResume");
    // It can come here from onCreate, onRestart or onPause.
    // Don't load url again since it will send another 2FA request
    if (mRegisterReceiver) {
        Logger.v(TAG, "Webview onResume will register receiver:" + mStartUrl);
        if (mReceiver != null) {
            Logger.v(TAG, "Webview onResume register broadcast receiver for requestId"
                    + mReceiver.mWaitingRequestId);
            LocalBroadcastManager.getInstance(this).registerReceiver(mReceiver,
                    new IntentFilter(AuthenticationConstants.Browser.ACTION_CANCEL));
        }
    }
    mRegisterReceiver = false;

```
// Spinner dialog to show some message while it is loading
mSpinner = new ProgressDialog(this);
mSpinner.requestWindowFeature(Window.FEATURE_NO_TITLE);
mSpinner.setMessage(this.getText(this.getResources().getIdentifier("app_loading", "string",
        this.getPackageName())));
```

}

Is it possible, to expose a handle on **enabling/disabling the ProgressDialog** in a future version?
Or can we have an **alternate experience to show the loading** (like a transparent spinner overlay without dialog box), one that doesn’t hide messages on such a 2 factor auth screen?

**Comment by nazukj** [comment]
Wont fix.
