### ISSUE TITLE
Does not build with 2.1.3

### ISSUE THREAD

**Issue by mikemcl-msft** [AzureAD/azure-activedirectory-library-for-android#702]
We just introduced ADAL into our app and it worked well.  Then I upgraded to Android Studio 2.1.3 and am now getting a build error everywhere we have "((AppCompatActivity) getActivity())".  The error says "Cannot access android.support.v4.app.BaseFragmentActivityEclair".  Our code works when we revert the commit which introduces ADAL.

**Comment by alhend** [comment]
This can be fixed by updating the appcompat libraries in gradle to 24.2.0
