### ISSUE TITLE
Gettokensilent returns new token everytime while my token is not expired.

### ISSUE THREAD

**Issue by sunny01gupta** [AzureAD/azure-activedirectory-library-for-android#704]
I am using convergence branch for ADAL B2C, and there is a feature "Get token" is working fine with this branch but when i go for "Get token silent", every time it returns new token while my token is not expired yet. we are working with ADAL B2C for entity management since last 6-8 months but still we didn't find any stable sdk for ADAL B2C. Please may you tell us when would we expect stable build or provide us other solutions.

**Comment by vijaylaxmivl** [comment]
Hello

I am also getting the same issue. Please provide some information to resolved this issue.

**Comment by nazukj** [comment]
This branch of the library is going to be retired, so no new updates will be made.  Please take a look at the OSS OAuth libraries mentioned on http://aka.ms/aadb2c as a replacement.  We are working on the next gen library, the Microsoft Authentication Library (MSAL), that will work with B2C, and will be previewed later this year.
