### ISSUE TITLE
Provide option to use the device browser for the auth flow

### ISSUE THREAD

**Issue by Ricalo** [AzureAD/azure-activedirectory-library-for-android#710]
Recently, Google has alerted developers of the advantages and reduced risks of using the device browser instead of embedded mechanisms like *WebView*. They clearly specify their stance in the post, 
[Modernizing OAuth interactions in Native Apps for Better Usability and Security](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).

The post mentions alternatives such as the AppAuth library. However, this 3rd party library can't implement *Conditional Access* or *Intune policy management* according to [Azure documentation](https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-devquickstarts-android/).

The only way for developers to comply with Google's recommendation and use the mentioned features is if Azure AD Library for Android supports using the device browser for the auth flow.

Is there something in the works to address this? Or is there a workaround?

Thank you,
&nbsp;&nbsp;&nbsp;&nbsp;Ricardo

**Comment by weijjia** [comment]
This is the work we're doing for MSAL not ADAL, and we're not planning to support system browser for ADAL.

**Comment by Ricalo** [comment]
Good to hear. Can't wait for MSAL to see the light.
