### ISSUE TITLE
Gradle 2.2.0 build with Instant run fails

### ISSUE THREAD

**Issue by headsvk** [AzureAD/azure-activedirectory-library-for-android#720]
Download the new Android Studio 2.2 and setup a project with Gradle 2.2.0 and ADAL 1.10.0.
It will fail on build with this exception if you have Instant run turned on.
```
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> class "com.microsoft.aad.adal.AuthenticationCallback"'s signer information does not match signer information of other classes in the same package
```

**Comment by trevorwang** [comment]
I have met this issue while upgrading Android studio to 2.2. But it works with 2.1.3.

**Comment by gauravgaikwad777** [comment]
It's letting us use the latest Android Studio 2.2 with instant run.

![image](https://cloud.githubusercontent.com/assets/8176450/19049245/7b54bd16-895e-11e6-9d76-13e2d8754204.png)

Here all previous discussion to this issue 
https://github.com/microsoftgraph/android-java-snippets-sample/issues/5

**Comment by headsvk** [comment]
If it works, why do you get the exception?

**Comment by gauravgaikwad777** [comment]
It works only if I use a previous gradle version (gradle 2.1.3), but it fails the build if I try to use gradle 2.2.

**Comment by headsvk** [comment]
Yes, because using the old gradle version disables Instant Run.

**Comment by gauravgaikwad777** [comment]
True, using "com.microsoft.aad.adal.AuthenticationCallback;" creates this error using gradle 2.2 with Android 2.2.

Is there any fix for this?

**Comment by bomiyr** [comment]
+1

**Comment by bduhbya** [comment]
I have tested and found that removing the signature data from the Adal library classes.jar manifest can work around the issue.

**Comment by dbahat** [comment]
+1

**Comment by matteinn** [comment]
+1

**Comment by tellarin** [comment]
Works fine for me with com.android.tools.build:gradle:2.2.0
Breaks with 2.2.1

**Comment by imakhalova** [comment]
+1
Is someone looking at this issue?

**Comment by weijjia** [comment]
Duplicate as #724 Use #724 to track the issue. @addev-ashish and myself are looking into it.

**Comment by bduhbya** [comment]
There is local work around. Remove the manifest signature from the jar within the aar. Not ideal but for local debug will get instant run going.

**Comment by lddatacom** [comment]
I think there is some problem with Instant run while trying to compile com.microsoft.aad. Turn off instant run works for me, although it is not a proper method.
