### ISSUE TITLE
acquire token doesn't follow 302 (Temprorary moved) redirects

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#723]
10-04 14:33:46.833 17451-17541/com.microsoft.skydrive E/AcquireTokenSilentHandler: AUTH_FAILED_NO_TOKEN:2016-10-04 21:33:46-83ec4786-b5ab-4906-a532-015e7765ffcb-Error in refresh token for request:Request authority:https://login.windows.net/common resource:https://microsoft-my.sharepoint.com clientid:b26aadf8-566f-4478-926f-589f601d9c74 ver:1.2.0 Status code:302
com.microsoft.aad.adal.AuthenticationException: Status code:302
at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:465)
at com.microsoft.aad.adal.Oauth2.refreshToken(Oauth2.java:314)
at com.microsoft.aad.adal.AcquireTokenSilentHandler.acquireTokenWithRefreshToken(AcquireTokenSilentHandler.java:126)
at com.microsoft.aad.adal.AcquireTokenSilentHandler.acquireTokenWithCachedItem(AcquireTokenSilentHandler.java:269)

**Comment by weijjia** [comment]
No 302 should ever been sent from token endpoint, and ADAL never supports 302 from token endpoint.  Can you gather fiddler trace?

**Comment by imakhalova** [comment]
This server response doesn't persist forever so I would be almost impossible to fiddler it, but I've got some logs that definitely caught 302

**Comment by weijjia** [comment]
@imakhalova Can you share the logs for 302 on token endpoint? We definitely need to talk to server folks for this.

**Comment by imakhalova** [comment]
Logs are already in first message to this issue. At least the interesting part...The rest is just regular acquireTokenSilently flow

**Comment by weijjia** [comment]
Oh ok, i thought you have some other verbose logs. I'll see if I can gather some info from server side with the above.

**Comment by nazukj** [comment]
Please reopen if still an issue.
