### ISSUE TITLE
Sign in problem

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#725]
10-06 17:41:54.685 10510-10510/com.microsoft.skydrive E/[ADAL]AuthenticationContext: 2016-10-07 00:41:54-dd71a006-f9d4-4a77-b834-4f5972a03ff0-Request callback is not available for requestId:261119023 ver:1.10.0 -                                                                                      com.microsoft.aad.adal.AuthenticationException: Active callback is not found                                                                                         at com.microsoft.authorization.adal.ADALNetworkTasks$2.Log(ADALNetworkTasks.java:93)                                                                                         at com.microsoft.aad.adal.Logger.logCommon(Logger.java:268)                                                                                         at com.microsoft.aad.adal.Logger.error(Logger.java:242)                                                                                         at com.microsoft.aad.adal.Logger.e(Logger.java:381)                                                                                         at com.microsoft.aad.adal.AuthenticationContext.getWaitingRequest(AuthenticationContext.java:998)                                                                                         at com.microsoft.aad.adal.AcquireTokenRequest.onActivityResult(AcquireTokenRequest.java:529)                                                                                         at com.microsoft.aad.adal.AuthenticationContext.onActivityResult(AuthenticationContext.java:731)                                                                                         at com.microsoft.authorization.adal.ADALNetworkTasks.onActivityResult(ADALNetworkTasks.java:287)                                                                                         at com.microsoft.authorization.odb.OdbSignInContext.onActivityResult(OdbSignInContext.java:169)                                                                                         at com.microsoft.authorization.adal.ADALSignInFragment.onActivityResult(ADALSignInFragment.java:224)                                                                                         at com.microsoft.authorization.SignInActivity.onActivityResult(SignInActivity.java:207)                                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:6428)                                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)                                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)                                                                                         at android.app.ActivityThread.-wrap16(ActivityThread.java)                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                         at android.os.Looper.loop(Looper.java:148)                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)                                                                                         at java.lang.reflect.Method.invoke(Native Method)                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

**Comment by addev-ashish** [comment]
@imakhalova can you please add more details, probably the full logs.

**Comment by zedixns** [comment]
It seems that you'r callback was destroyed prior to the result of the request, and then the AuthenticationContext tries to call your callback but it's null or something.

More code would help.

**Comment by imakhalova** [comment]
That's all I got for now, but if I get repro I'll add logs.

**Comment by imakhalova** [comment]
I think that was a problem on my side. I can't repro it anymore, closing issue
