### ISSUE TITLE
brokerRedirectPrint.ps1 not returning the correct base64Encoded string.

### ISSUE THREAD

**Issue by ramaguduri** [AzureAD/azure-activedirectory-library-for-android#729]
I am using [adal-cordova](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/releases) 0.8.0, which is using adal android release version 1.1.18.

As part of the CI I am trying to use the 'brokerRedirectPrint.ps1' to generate the redirectURL during build phase. But during the run time when the application is trying to get the token using broker we get below error.

"code": "DEVELOPER_REDIRECTURI_INVALID",
"errorDescription": The base64 url encoded signature component of the redirect uri does not match the expected value.  This apps signature is: L%2BsoR7TE7ETwcCjXpBhncoGIa9Q%3D so the redirect uri is expected to be: msauth://io.cordova.hellocordova/L%2BsoR7TE7ETwcCjXpBhncoGIa9Q%3D ver:1.1.18 

Attached the sample key store used for this test app.
key store config
CN=adal test, OU=adal, O=adal, L=adal, ST=adal, C=US
key store pass - adaltest
[test-adal-key.zip](https://github.com/AzureAD/azure-activedirectory-library-for-android/files/556362/test-adal-key.zip)

Any idea what is going on? Why the generated encoded string different to the one app is trying compare with?

Thanks in Advance!

**Comment by weijjia** [comment]
It could be the environment reading the key causing the issue. When we calculate the key tag inside ADAL code, we actually ask the os to give us the signature hash for the running app. Can you use getBrokerRedirect inside AuthenticationContext to get the correct redirect uri back?

**Comment by nazukj** [comment]
@ramaguduri Please feel free to reopen if above comment does not resolve your issue. Thanks!
