### ISSUE TITLE
AADSTS70000: Authentication failed: Refresh Token is malformed or invalid.

### ISSUE THREAD

**Issue by AngryITGuy** [AzureAD/azure-activedirectory-library-for-android#737]
I am successfully generating tokens, but acquireTokenSilent throws up an error when the bearer token expires and I attempt to refresh the token. I have the http transaction details in an exported charles file if that helps. If someone can advise if this is sufficient or what other data is needed, I would be happy to provide.

Error description response from host is:

AADSTS70000: Authentication failed: Refresh Token is malformed or invalid.
Trace ID: 4f4c1375-f527-4f78-9e4a-570b36e47561
Correlation ID: 7e9ded5f-e09a-45d9-b0ad-2ff3bb7d015c
Timestamp: 2016-11-23 13:15:35Z

**Comment by weijjia** [comment]
logs will help in this case. Please share logs with us.

**Comment by AngryITGuy** [comment]
Alot has been done since my post. I have abandoned acquireTokenSilent method in Android in favour of a manual HTTP refresh token request which has been working. The difficulty has been to correctly configure the paramters in the refresh call. The demo/sample code does not provide a working example. I will submit more information soon. But if you can demonstrate a working code inthe sample app, that may answer this question.

**Comment by weijjia** [comment]
Close for now, please re-open if you still see the issue.
