### ISSUE TITLE
ADAL not working for Mobile client with ADFS 4.0

### ISSUE THREAD

**Issue by tinafanms** [AzureAD/azure-activedirectory-library-for-android#739]
We have a SfB hybrid topology with ADAL enabled for both OnPrem and Online. When we use ADFS 3.0, our Mobile app can log in, but with ADFS 4.0 , the mobile app can't login. 
Here is what we got in the client log. We are wondering what could be the problem, is it a real bug or a configuration issue.
Let me know what are the other logs I can get for you.

We have tested with market version; it is failing in ADAL SDK itself. 
 
It is failed to create device certificate response ver:1.2.0, additionalMessage CertAuthorities com.microsoft.aad.adal.AuthenticationException
 
 
 
11-17 22:29:22.213 9956 DEBUG [ADAL] AdalUtils: tag: BasicWebViewClientonPageStarted, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-page is started with the url urn:http-auth:PKeyAuth?SubmitUrl=https%3a%2f%2ffs.cbasfb.directtaps.net%3a443%2fadfs%2foauth2%2fauthorize%3fresponse_type%3dcode%26client_id%3dd3590ed6-52b3-4102-aeff-aad2292ab01c%26resource%3dhttps%253A%252F%252Fpool01.cbasfb.directtaps.net%26redirect_uri%3dmsauth%253A%252F%252Fcom.microsoft.office.lync15%252Ffcg80qvoM1YMKJZibjBwQcDfOno%25253D%26state%3dYT1odHRwczovL2ZzLmNiYXNmYi5kaXJlY3R0YXBzLm5ldC9hZGZzJnI9aHR0cHM6Ly9wb29sMDEuY2Jhc2ZiLmRpcmVjdHRhcHMubmV0%26login_hint%3dua0005%2540cbasfb.directtaps.net%26x-client-SKU%3dAndroid%26x-client-Ver%3d1.2.0%26x-client-OS%3d24%26x-client-DM%3dNexus%2b5X%26client-request-id%3d881de3bb-83da-4f71-b7b7-47dd5827d448%26nux%3d1&nonce=fTPpMh-EU-KoxIGtUNV_1Q&Version=1.0&Context=AAEAABh2vORNgkkpePCescQpqV58Di3d_S8dYOzDQqV2wTOv9Fzn9xEMElAoHbjfG12RXA_Sbi8MkzE9UGRv5E6w_SJm4mjD9yBC7nrYIJnZoooSGwt8E4YtM9eHSi98qV3bWPQQvSKLZVBR-GlEPLydZcASaA7R7n3M36VD1DsdBTFHRUfW3L69DYAxJDrHYWIjuz8KISZOcwTqfIEKVaqYRtoyJW-afsRJNlcKPbtIICMlww7ZIC3add_07ShCjWj_JlUmhgjHnIuxqrEoRhG-oTjnblh2GPTKmAgF5CRwJgwsDqpSaIizwxTDi0zPZcoUdgPPgo_A2C8Tgs_gTD4HcoZXGgdKG7dD4cu2ZOWGHhFOcF3mKbexOrzgwrxC0t1EZQABAACTzJK14sGvmwt16n3J0PrPeHCkUPMJQmnl8qPqFE85Wi7hbsvg0EvI-A-X2wOERnX75A9HbbexwxglgLDg9kmh7L1gr8KMTxjJhRx_9aW1pcy_eT9MBFJiJ2svpCRh_VohiLknIRWN5SLmCpXTmCPyDFhI9kpACADcqzphDvj63OF-YHLwq-DZ169-cppLhWWloz_wjPctO6S_eMDLhKYXHBiK6aToTlxYegFHbRaC-STw6nyvtGtfdSI3p1TQI997hKncDtsOYxHGhvobF4dccMf569XgzKWrx4vR7V1Qr3XtG-Bybsk1yJvpm7Wirwb-hmASiBxRuRXUqF5kGtL3YAAAAKTtcYmGwzV8zFJm8GglRVPdZJhRNxDfaNsbE-xIWmcGduUYYYJy-l_NeJpdG9a1zwL3QWk9KUd94VXRZu8ZVTrlRRa4NcupiQFkIVkBGzxSTKLawloi3E-oR71gmWK34Q&CertAuthorities=&client-request-id=881de3bb-83da-4f71-b7b7-47dd5827d448 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.215 9956 DEBUG [ADAL] AdalUtils: tag: AuthenticationActivity, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-displaySpinner:true showing:true ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.235 9956 DEBUG [ADAL] AdalUtils: tag: BasicWebViewClient, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Navigation is detected ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.237 9956 DEBUG [ADAL] AdalUtils: tag: BasicWebViewClient, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Webview detected request for pkeyauth challenge. ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.251 11560 ERROR [ADAL] AdalUtils: tag: BasicWebViewClient, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-It is failed to create device certificate response ver:1.2.0, additionalMessage CertAuthorities com.microsoft.aad.adal.AuthenticationException: CertAuthorities
                at com.microsoft.aad.adal.ChallengeResponseBuilder.validateChallengeRequest(ChallengeResponseBuilder.java:286)
                at com.microsoft.aad.adal.ChallengeResponseBuilder.getChallengeRequest(ChallengeResponseBuilder.java:299)
                at com.microsoft.aad.adal.ChallengeResponseBuilder.getChallengeResponseFromUri(ChallengeResponseBuilder.java:95)
                at com.microsoft.aad.adal.BasicWebViewClient$3.run(BasicWebViewClient.java:173)
                at java.lang.Thread.run(Thread.java:761)
, adalError: It is failed to create device certificate response
11-17 22:29:22.253 11560 DEBUG [ADAL] AdalUtils: tag: AuthenticationActivity, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Return To Caller:2005 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.255 11560 DEBUG [ADAL] AdalUtils: tag: AuthenticationActivity, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-displaySpinner:false showing:true ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.256 11560 DEBUG [ADAL] AdalUtils: tag: AuthenticationActivity, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Return To Caller REQUEST_ID:53066355 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.403 9956 DEBUG [ADAL] AdalUtils: tag: AuthenticationActivity, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-AuthenticationActivity onPause unregister receiver ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.403 9956 DEBUG ActivityMonitor: Activity Pause: AuthenticationActivity
11-17 22:29:22.404 9956 DEBUG [ADAL] AdalUtils: tag: AuthenticationActivity, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Spinner at onPause will dismiss ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.416 9956 DEBUG [ADAL] AdalUtils: tag: BasicWebViewClient, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Page finished:urn:http-auth:PKeyAuth?SubmitUrl=https%3a%2f%2ffs.cbasfb.directtaps.net%3a443%2fadfs%2foauth2%2fauthorize%3fresponse_type%3dcode%26client_id%3dd3590ed6-52b3-4102-aeff-aad2292ab01c%26resource%3dhttps%253A%252F%252Fpool01.cbasfb.directtaps.net%26redirect_uri%3dmsauth%253A%252F%252Fcom.microsoft.office.lync15%252Ffcg80qvoM1YMKJZibjBwQcDfOno%25253D%26state%3dYT1odHRwczovL2ZzLmNiYXNmYi5kaXJlY3R0YXBzLm5ldC9hZGZzJnI9aHR0cHM6Ly9wb29sMDEuY2Jhc2ZiLmRpcmVjdHRhcHMubmV0%26login_hint%3dua0005%2540cbasfb.directtaps.net%26x-client-SKU%3dAndroid%26x-client-Ver%3d1.2.0%26x-client-OS%3d24%26x-client-DM%3dNexus%2b5X%26client-request-id%3d881de3bb-83da-4f71-b7b7-47dd5827d448%26nux%3d1&nonce=fTPpMh-EU-KoxIGtUNV_1Q&Version=1.0&Context=AAEAABh2vORNgkkpePCescQpqV58Di3d_S8dYOzDQqV2wTOv9Fzn9xEMElAoHbjfG12RXA_Sbi8MkzE9UGRv5E6w_SJm4mjD9yBC7nrYIJnZoooSGwt8E4YtM9eHSi98qV3bWPQQvSKLZVBR-GlEPLydZcASaA7R7n3M36VD1DsdBTFHRUfW3L69DYAxJDrHYWIjuz8KISZOcwTqfIEKVaqYRtoyJW-afsRJNlcKPbtIICMlww7ZIC3add_07ShCjWj_JlUmhgjHnIuxqrEoRhG-oTjnblh2GPTKmAgF5CRwJgwsDqpSaIizwxTDi0zPZcoUdgPPgo_A2C8Tgs_gTD4HcoZXGgdKG7dD4cu2ZOWGHhFOcF3mKbexOrzgwrxC0t1EZQABAACTzJK14sGvmwt16n3J0PrPeHCkUPMJQmnl8qPqFE85Wi7hbsvg0EvI-A-X2wOERnX75A9HbbexwxglgLDg9kmh7L1gr8KMTxjJhRx_9aW1pcy_eT9MBFJiJ2svpCRh_VohiLknIRWN5SLmCpXTmCPyDFhI9kpACADcqzphDvj63OF-YHLwq-DZ169-cppLhWWloz_wjPctO6S_eMDLhKYXHBiK6aToTlxYegFHbRaC-STw6nyvtGtfdSI3p1TQI997hKncDtsOYxHGhvobF4dccMf569XgzKWrx4vR7V1Qr3XtG-Bybsk1yJvpm7Wirwb-hmASiBxRuRXUqF5kGtL3YAAAAKTtcYmGwzV8zFJm8GglRVPdZJhRNxDfaNsbE-xIWmcGduUYYYJy-l_NeJpdG9a1zwL3QWk9KUd94VXRZu8ZVTrlRRa4NcupiQFkIVkBGzxSTKLawloi3E-oR71gmWK34Q&CertAuthorities=&client-request-id=881de3bb-83da-4f71-b7b7-47dd5827d448 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.417 9956 DEBUG OAuthStateHandler: OAuth responses requestCode 1001, resultCode 2005
11-17 22:29:22.426 9956 DEBUG [ADAL] AdalUtils: tag: AuthenticationContext, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Get waiting request: 53066355 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.428 9956 DEBUG [ADAL] AdalUtils: tag: AuthenticationContext, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-onActivityResult RequestId:53066355 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.429 9956 WARN [ADAL] AdalUtils: tag: AuthenticationContext, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Webview returned exception ver:1.2.0, additionalMessage CertAuthorities, adalError: Webview returned Authentication Exception
11-17 22:29:22.431 9956 DEBUG [ADAL] AdalUtils: tag: AuthenticationContext, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-Sending error to callback CorrelationId: 881de3bb-83da-4f71-b7b7-47dd5827d448 ver:1.2.0, additionalMessage null, adalError: NULL
11-17 22:29:22.431 9956 WARN OAuthStateHandler: AuthenticationCallback onError CertAuthorities
11-17 22:29:22.432 9956 DEBUG SignInTelemetry: ui_auth_finished {DeviceId=0-0-c1976429369bfe063ed8b3409db7c7e7d87196d9, ErrorString=AUTH_FAILED, SignInCorrelationId=f5345f10-68d7-418b-b01e-01950b0afa47, Status=, ErrorCode=E_UI_ClientOAuthError, AuthenticationTopology=oAuth}

**Comment by weijjia** [comment]
Aren't we already having an email thread for this? why an empty cert authority is returned from adfs? I'll close the issue for now, and we'll follow up more in the email thread if needed.
