### ISSUE TITLE
Facebook login broken

### ISSUE THREAD

**Issue by zedixns** [AzureAD/azure-activedirectory-library-for-android#749]
In  AADL, the point at which the code parses the wrong part of the redirect URL and fails to complete the flow is as follows:
- Library: adal-2.0.3-alpha
- Class: StringExtensions.java
- At line 122 a method called getUrlParameters(String finalUrl) which receives the final URL that both Google and Facebook login returned back from their respective web logins.

The key difference between them is in the ending part of the URL:
o   Google: urn:ietf:wg:oauth:2.0:oob?code=eyJraWQiOiJjc………….5UvY1-KoXhOxCw#
o   Facebook: urn:ietf:wg:oauth:2.0:oob?code=eyJraWQiOiJjcGl………….uotViihMUAYA#_=_

The next step in the library is that it checks the part of the URL after the hashtag(#). For Google login that part is empty and it takes the part that contains the “code=….” But for the Facebook login it takes the “_=_” and determines that it is not empty and uses that to try and fetch the code, where it fails. I am not exactly sure why it even looks for that last part because it doesn’t actually contain anything.

If i missed something please let me know, but I bumped into this, so was wondering if I could get any info in it or something, if its even a valid bug or not.

**Comment by weijjia** [comment]
PR merged https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/764

**Comment by zedixns** [comment]
Its great that the fix has finally been applied. But can you tell me when will this be included in the new 2.0.4-alpha build and published to jcenter?

**Comment by weijjia** [comment]
@zedixns https://search.maven.org/#artifactdetails%7Ccom.microsoft.aad%7Cadal%7C2.0.4-alpha%7Caar

**Comment by zedixns** [comment]
@weijjia Thank you. Confirmed that the issue has been fixed.
