### ISSUE TITLE
Crash:  invalid date string: Unparseable date: "ag`a`a`b`cbbGMT+00:00" (at offset 0)

### ISSUE THREAD

**Issue by khalidaw** [AzureAD/azure-activedirectory-library-for-android#753]
Reason: 
java.lang.IllegalArgumentException: invalid date string: Unparseable date: "ag`a`a`b`cbbGMT+00:00" (at offset 0)

Location: 
com.microsoft.aad.adal.StorageHelper.generateKeyPairFromAndroidKeyStore, line 414

Can be related to number in Arabic issue, but for sure this should be in catch an not cause app crashes.

**Comment by e54999** [comment]
e549999@yahoo.com.tw

**Comment by e54999** [comment]
0974294297@e549999.onmicrosoft.com

**Comment by hjymandroid** [comment]
It crashes bad for us.

Exception Backtrace:
1	android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair	AndroidKeyStoreKeyPairGeneratorSpi.java, line 504
2	java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair	KeyPairGenerator.java, line 276
3	com.microsoft.aad.adal.StorageHelper.generateKeyPairFromAndroidKeyStore	StorageHelper.java, line 414
4	com.microsoft.aad.adal.StorageHelper.getKeyOrCreate	StorageHelper.java, line 362
5	com.microsoft.aad.adal.StorageHelper.loadSecretKeyForEncryption	StorageHelper.java, line 320
6	com.microsoft.aad.adal.StorageHelper.encrypt	StorageHelper.java, line 178
7	com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt	DefaultTokenCacheStore.java, line 122
8	com.microsoft.aad.adal.DefaultTokenCacheStore.setItem	DefaultTokenCacheStore.java, line 190
9	com.microsoft.aad.adal.TokenCacheAccessor.setItemToCacheForUser	TokenCacheAccessor.java, line 227
10	com.microsoft.aad.adal.TokenCacheAccessor.updateTokenCache	TokenCacheAccessor.java, line 165
11	com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode	AcquireTokenInteractiveRequest.java, line 121
12	com.microsoft.aad.adal.AcquireTokenRequest$4.run	AcquireTokenRequest.java, line 651
13	java.util.concurrent.ThreadPoolExecutor.runWorker	ThreadPoolExecutor.java, line 1113

**Comment by weijjia** [comment]
This is a common issue with AndroidKeyStore, please check the below link:
https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
