### ISSUE TITLE
Login page on edit_policy

### ISSUE THREAD

**Issue by brucemax** [AzureAD/azure-activedirectory-library-for-android#758]
Hi! When I run aquireToken with edit_policy I have login screen first. How I could run right away to edit screen and do not ask user for input credentials?

**Comment by weijjia** [comment]
Can you expand a little bit more? I'm not sure i'm following.

**Comment by brucemax** [comment]
As I see it does not matter because new  
[sdk appeared](https://github.com/Azure-Samples/active-directory-b2c-android-native-nodejs-webapi)

**Comment by weijjia** [comment]
Seems like the issue is resolved, please re-open if it's not the case.
