### ISSUE TITLE
Failed to get Token (Certificate Issue)

### ISSUE THREAD

**Issue by Eqbalazar** [AzureAD/azure-activedirectory-library-for-android#759]
After updating System Web view on Android OS it seems to get certificate error issue.It happens when web view wants to open login page.
 **Error** : 
 Code : -11 primary error : 5 certificate :issued to : CN= securre.aadcdn.microsoftonline- p.com,0=microsoftcorporation,L= Redmond,ST=Washington ,C=US Issued by:CN=Symantec Class 3 Secure Server CA =G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US on URL=:https://secure.aadcdn.microsoftonline-p.com/ests/2.1.5274.8/content/cdnbundels/login.min.css corelationid : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Info** : 
Android 6.0.1  , System WebView Vesion(default): 49.0.2623.105 
targetSdkVersion 21 , Adal version com.microsoft.aad:adal:1.2.0 .

**Solution :** 
 I unistalled the updated version of System Webview and set to default .

 **It seems developer does not have option to control this for now .**
https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/BasicWebViewClient.java

**Comment by weijjia** [comment]
Please check the wiki https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/SSL-Certificate-Validation-Issue
