### ISSUE TITLE
KeyPairGeneratorSpec is deprecated in API level 23

### ISSUE THREAD

**Issue by caltseng** [AzureAD/azure-activedirectory-library-for-android#762]
This library uses KeyPairGeneratorSpec, which is deprecated in newer API levels (see below). Please update to using the newer API call. 

https://developer.android.com/reference/android/security/KeyPairGeneratorSpec.html
https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.html

**Comment by weijjia** [comment]
We're going to deprecate the usage of android keystore, this will be based on the prioritization.

**Comment by weijjia** [comment]
Please check the link https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore

With all the issues we have with android keystore, we're requiring all our developers to provide us the encryption key before we figure out a better way to do encryption.
