### ISSUE TITLE
Azure Active Directory Authentication Library - not working in Google Pixel (Android Nougat 7.1.1)

### ISSUE THREAD

**Issue by fa-sathya** [AzureAD/azure-activedirectory-library-for-android#763]
Integrated ADAL 1.10.0 (Tried earlier version 1.1.11 also) with native Android App. While Azure Login works fine in Phones using Android 5.x.x and 6.x.x, Azure login does not work in Google Pixel which runs on Android version 7.1.1. (Nougat).

We get the following exception in ADAL:

com.microsoft.aad.adal.authenticationException:code:-11 primary error: 5 certificate: issued to:CN=sercure.aadcdn.microsoftonline-p.com,O=Microsoft corporation, L=redmond, ST=Washington, C=US; Issued by: CN=Symantec Trust Network, O=Symantec Corporation, C=US; on URL:https://secure.aadcdn.microsoftonline-p.com/ests/2.1.5364.5/content/cnbundles/jquery.1.11.min.js correlationId:6dc07a37-b7e8-4ea9-9e8e-92d62ed2c0b1 

I am not sure if ADAL supports this new version of Android. Any help will be appreciated.

**Comment by hjymandroid** [comment]
Our user saw similar error.

**Comment by weijjia** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/SSL-Certificate-Validation-Issue
Please check the above link.
