### ISSUE TITLE
Not getting an error callback when as part of login you are redirected to an HTTP endpoint

### ISSUE THREAD

**Issue by mpaliath** [AzureAD/azure-activedirectory-library-for-android#767]
[ADAL.log.txt](https://github.com/AzureAD/azure-activedirectory-library-for-android/files/756297/ADAL.log.txt)

Trying to authenticate against AAD but in scenarios where it is redirected to an HTTP endpoint during login, ADAL fails with an SSL error but the callback is not invoked informing the app about the error.

**Comment by weijjia** [comment]
From the log, i'm not seeing that error is actually returned back. There was a request sent to authorize endpoint, we detect an non-safe http endpoint, but before we actually send error back. Then a new AutheticationContext is created, onActivity result is call but the intent has an empty waiting request id. 

Does it work in any other scenarios or this is the only one not working?

**Comment by weijjia** [comment]
There was a bug in 1.10.0 and 1.11.0 that we are clearing the map storing the callback, which is keyed by request id. It's fixed in the upcoming release 1.12.0.
