### ISSUE TITLE
App crashes when the broker Authenticator is not installed

### ISSUE THREAD

**Issue by vkislicins** [AzureAD/azure-activedirectory-library-for-android#769]
I've just recently implemented ADAL support into my app and while going through the different test scenarios, noticed that if you uninstall the Authenticator app, my app crashes with the following error:

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seenit.unilever/com.microsoft.aad.adal.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.webkit.WebSettings android.webkit.WebView.getSettings()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.webkit.WebSettings android.webkit.WebView.getSettings()' on a null object reference
    at com.microsoft.aad.adal.AuthenticationActivity.onCreate(AuthenticationActivity.java:230)
    at android.app.Activity.performCreate(Activity.java:6679)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
    <...>`

This seems to be coming from the WebView used by the library. Is there any way to work around this? Also is it possible to check if the authenticator app is installed via the library?

**Comment by weijjia** [comment]
What's the adal version you're using?

**Comment by vkislicins** [comment]
I'm using ADAL version 1.10.0. Support libraries are on 25.1.0, build tools 24.0.2 and compile/target sdks are 25, min sdk is 16

Please let me know if you need any other info

**Comment by weijjia** [comment]
Thanks @vkislicins. Stack trace indicates that the webview is null, so when we call mWebview.getSettings it throws out the nullpointer. mWebview is created by loading the resource file, can you please check to make sure that the resources are merged correctly into your app?

**Comment by alexkhomenko** [comment]
Had exactly same exception, and find this issue by googling. In my case I created activity for authentication and named it AuthenticationActivity. Somehow it intersects with adal.AuthenticationActivity, and after I renamed my activity in my package, problem gone.

**Comment by vkislicins** [comment]
My app's auth activity is not called AuthenticationActivity, however, the layout resource is actually the same name as the ADAL's one - `activity_authentication.xml`. That's probably why the problem occurs.

**Comment by weijjia** [comment]
It seems that the issue has been resolved. Please re-open if you see it again.

**Comment by Journeyman42** [comment]
I have experienced this problem too. Exactly the same code works fine on iOS

[Mono] Image addref System.ServiceModel.Internals[0xab243e00] -> System.ServiceModel.Internals.dll[0x9b104800]: 2
[Mono] Prepared to set up assembly 'System.ServiceModel.Internals' (System.ServiceModel.Internals.dll)
[Mono] Assembly System.ServiceModel.Internals[0xab243e00] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/com.companyname.PreviewAuthenticate-1/lib/x86/libaot-System.ServiceModel.Internals.dll.so" not found
[Mono] AOT: image '/usr/local/lib/mono/aot-cache/x86/System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/com.companyname.PreviewAuthenticate-1/lib/x86/libaot-System.ServiceModel.Internals.dll.so" not found
[Mono] Config attempting to parse: 'System.ServiceModel.Internals.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System.ServiceModel.Internals/System.ServiceModel.Internals.config'.
[Mono] Assembly Ref addref System.Runtime.Serialization[0xab243c20] -> System.ServiceModel.Internals[0xab243e00]: 2
[Mono] Assembly Ref addref System.ServiceModel.Internals[0xab243e00] -> mscorlib[0xab26c440]: 52
[Mono] Assembly Ref addref System.ServiceModel.Internals[0xab243e00] -> System.Xml[0xad9a8da0]: 5
[Mono] Assembly Ref addref System.Runtime.Serialization[0xab243c20] -> System[0xad9a84a0]: 15
Loaded assembly: System.ServiceModel.Internals.dll [External]
[Mono] Assembly Ref addref System.ServiceModel.Internals[0xab243e00] -> System[0xad9a84a0]: 16
TKM42 Error AuthenticationActivity failed to start

**Comment by dharashahkenya** [comment]
Hi.,

I just got this issue with msal sdk 0.2.2 version:

> java.lang.RuntimeException: Unable to resume activity {packagename/com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.webkit.WebSettings android.webkit.WebView.getSettings()' on a null object reference
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3109)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3140)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
>         at android.app.ActivityThread.access$900(ActivityThread.java:150)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.app.ActivityThread.main(ActivityThread.java:5423)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:766)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

Would anyone please direct me as to what i might be doing wrong ?
