### ISSUE TITLE
plugin has conflicts with cordova-plugin-ms-adal while cordova build andoid

### ISSUE THREAD

**Issue by greybax** [AzureAD/azure-activedirectory-library-for-android#770]
After installation of plugin with follow parameters:

```
cordova plugin add cordova-plugin-ms-azure-mobile-engagement 
  --variable AZME_IOS_CONNECTION_STRING=<ios_connection_string>
  --variable AZME_ANDROID_CONNECTION_STRING=<android_connection_string>
```
and build my android application I've faced with follow exception:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/MSFTSIG.RSA
        File1: C:\One\MobileApp\platforms\android\libs\mobile-engagement-4.2.3.jar
        File2: C:\One\MobileApp\platforms\android\build\intermediates\exploded-aar\com.microsoft.aad\adal\1.1.18\jars\classes.jar


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.2 secs
Error: Error code 1 for command: cmd with args: /s,/c,"c:\One\MobileApp\platforms\android\gradlew cdvBuildDebug -b c:\One\MobileApp\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
```

After some investigation I've found that root cause of this issue is conflicting with next plugin:

<plugin name="cordova-plugin-ms-adal" spec="~0.9.0" />

and seems plugin do some things which conflicted with this plugin.

**Comment by weijjia** [comment]
com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/MSFTSIG.RSA

It looks like the apk compilation fails since both the sdks are has the same signature file. I'm not sure I follow that "After some investigation I've found that root cause of this issue is conflicting with next plugin:", can you elaborate a little bit more?

**Comment by weijjia** [comment]
Close since there is no response. Please re-open if you see the issue again.
