### ISSUE TITLE
You need to set a lock screen PIN or password

### ISSUE THREAD

**Issue by rknarla** [AzureAD/azure-activedirectory-library-for-android#777]
In our automation runs, during ADAL authentication, we are seeing unexpected popup asking to set a lock screen PIN or password to use credential storage.
This seems to be coming from onReceivedClientCertRequest in CustomWebViewClient. 
In happy path scenario, I am not seeing this code getting hit. In which error case, this onReceivedClientCertRequest callback gets called?

**Comment by weijjia** [comment]
This is for cert based auth. What is the account used to do the automation run? And is CBA enabled for the account? For CBA, the OS is displaying the cert picker and it will write the cert into the credential storage. So this is the expected behavior.

**Comment by weijjia** [comment]
Close it for now and please re-open if you still think it's a bug.
