### ISSUE TITLE
Minor Optimization - Empty check DefaultTokenCacheStore.getItem()

### ISSUE THREAD

**Issue by caltseng** [AzureAD/azure-activedirectory-library-for-android#779]
If the returned value is "", don't bother decrypting it.

**Comment by heidijinxujia** [comment]
There is already a null/blank check for the input parameters at the beginning of the decrypt function. IllegalArgumentException will be thrown if the input is null or blank. (see Line 235 at StorageHelper.java)

I think we should close this issue. Because no change is needed here. @addev-ashish
