### ISSUE TITLE
Adal asking users with old webView upgrade system.WebView, although Android 7 doesn't uses system.WebView

### ISSUE THREAD

**Issue by dbahat** [AzureAD/azure-activedirectory-library-for-android#784]
Adal asking users with old webView upgrade the component called system.WebView (e.g. for users with Chrome version 53).
Devices with Android 7 no longer use system.WebView, but uses Chrome for web rendering instead.
For users with Android 7, need to send the users to install the latest Chrome, not the latest System.WebView app.

**Comment by weijjia** [comment]
@dbahat This is the page displayed by server side. They already have the fix in testslice, we're planning to push it to prod later this week assuming everything goes well.

**Comment by weijjia** [comment]
The change is already deployed on ests prod. Closed for now.
