### ISSUE TITLE
Unused dimens values override app-local ones

### ISSUE THREAD

**Issue by FD-** [AzureAD/azure-activedirectory-library-for-android#788]
The library defines a dimension value "activity_horizontal_margin" of 128dp for sw720dp-land. 

Apps (when created from a template within Android Studio) typically define that value as well, but don't use 128dp (don't seem to include a specific value for sw720dp-land).
As it seems qualified resources from a library override app-local resources, this leads to strange behaviour when app-local components use that dimens value (expecting to see 16dp on sw720dp-land).
For example, when adding a navigation drawer from a template, it uses the 128dp as margin in landscape on tablets, which looks awkward.

The library doesn't seem to use this value anyway, so I suggest removing it to get rid of the issues.

**Comment by nazukj** [comment]
Usage issue. Wont Fix

**Comment by FD-** [comment]
Does this mean you consider it an issue that comes from wrong usage or one that comes from just using your library? This is an annoying issue that should be easy to fix. If you need more details, I'm happy to help.

**Comment by addev-ashish** [comment]
@FD- please feel free to propose a PR. Thanks.
