### ISSUE TITLE
AcquireTokenSilent does not return tokens in FRT scenarios where user ID is not given.

### ISSUE THREAD

**Issue by HSAR** [AzureAD/azure-activedirectory-library-for-android#792]
Repro steps:
Call acquireToken for a resource, with the OneDrive client ID.
Call acquireTokenSilent for a resource, with the Office client ID, without providing a user ID.

Expected: token returned.
Actual: no token returned, auth attempt fails.

This is a documented test case, with an automated test, and we expect it to pass.

**Comment by HSAR** [comment]
Further investigation: getFRTItem() in TokenCacheAccessor (https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/a3ed8ad60d91ec9c80283c1c1a50c58081b7e863/adal/src/main/java/com/microsoft/aad/adal/TokenCacheAccessor.java#L127) immediately returns null if no user was specified.

For further details, see the bug at (Internal VSTS link):
https://identitydivision.visualstudio.com/IDDP/_workitems?id=48123&_a=edit&triage=false

**Comment by weijjia** [comment]
This is by design. We explicitly force the upn or user id to be passed in for foci. Family refresh token is per user/authority/apps within the same family.

**Comment by HSAR** [comment]
Please update the test case to include this information.
https://identitydivision.visualstudio.com/IDDP/_workitems?id=5408&_a=edit

**Comment by heidijinxujia** [comment]
Updated the test case. Close the issue.
