### ISSUE TITLE
 ADAL login page is not showing up When rotating the Samsung Android Tablet while the ADAL screen is loading  

### ISSUE THREAD

**Issue by AndroidTeamsUSer** [AzureAD/azure-activedirectory-library-for-android#811]
Repro steps

Login in to Microsoft Teams app
Enter user name and click on  Sign  in landscape Mode
When the ADAL screen is loading rotate the tablet to Portrait Mode

Actual
White page shows up in the portrait mode and even turning back to landscape mode the ADAL page doesn't shows up

**Comment by heidijinxujia** [comment]
Hi @AndroidTeamsUSer  thank you for filing the issue. Could you attach the ADAL logs here, as well as the detail info, such as app version, android version, adal version, broker version (if Authenticator or Company Portal is installed) so that I could try to repro? Thanks!

**Comment by heidijinxujia** [comment]
Hi @AndroidTeamsUSer Please send me the details for repro. I've tried on the Teams app from Playstore on my Android N device. Everything works fine when I rotated the screen. Cannot repro so far.

**Comment by nazukj** [comment]
Closing issue since we can't repro and don't have logs/repro steps. Please feel free to re-open issue with relevant information requested. Thanks!
