### ISSUE TITLE
We occassionally met duplication login pages when I tried to login with AAD account. 

### ISSUE THREAD

**Issue by Fshiner** [AzureAD/azure-activedirectory-library-for-android#815]
After the login page shows up, we just input the AAD account and then go to the second login page for AAD account, Input password and click signin, it takes to the first login page again without giving any error messages.
It went through just fine after login with the 2 login pages again.

**Comment by heidijinxujia** [comment]
Hi @Fshiner thank you for filing this issue. Could you give us more details for repro (device, app, android version, adal version) and attach the verbose level ADAL logs for us to triage the issue? Thanks!

**Comment by nazukj** [comment]
@Fshiner we will need requested information to look at the issue. Thanks!

**Comment by heidijinxujia** [comment]
Lack of the repro info and haven't got any reply from the customer for more then one week. Going to close the issue. Please feel free to reopen this issue if you see this issue again or has details for repro. Thanks.
