### ISSUE TITLE
Potential issue with ADAL 1.12 and app using other SDKs which inturn use ADAL

### ISSUE THREAD

**Issue by nazukj** [AzureAD/azure-activedirectory-library-for-android#819]
When apps using ADAL 1.12.0 use another SDK that includes a lower version of ADAL (1.11.0 and lower) the guidance is to not ask for Contacts permission till ADAL throws the exception. This will cause problems with the other SDK (with earlier ADAL) as a generic exception will be thrown.
Do you have any proposal for workaround?

**Comment by addev-ashish** [comment]
The proposed workaround is that the apps continue requesting contacts permission till all the SDKs that they use, have ADAL 1.12.0 or higher.
