### ISSUE TITLE
Adal 1.12 is reporting "Broker related permissions are missing for GET_ACCOUNTS."

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#822]
I am logging to an MAM account, and I have authenticator and company portal installed. When try to login, it reports 
'Caused by: com.microsoft.aad.adal.UsageAuthenticationException: Broker related permissions are missing for GET_ACCOUNTS.
\tat com.microsoft.aad.adal.AcquireTokenRequest.validateAcquireTokenRequest(AcquireTokenRequest.java:200)
\tat com.microsoft.aad.adal.AcquireTokenRequest.access$100(AcquireTokenRequest.java:46)
\tat com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:108)
\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
\tat java.lang.Thread.run(Thread.java:818)'

I did dig a bit into the code
seems 
'private boolean isServiceSupported(Context context, Intent intent) {
        if(intent == null) {
            return false;
        } else {
            PackageManager packageManager = context.getPackageManager();
            List infos = packageManager.queryIntentServices(intent, 0);
            return infos != null && infos.size() > 0;
        }
    }'
Here package query is against azure authenticator and returns 0 size infos list, which leads to isBrokerAccountServiceSupported return false. 

After reset authenticator I see this problem gone.   Why that is happening? 

I am having trouble to reproduce this, and will update if I do.

**Comment by heidijinxujia** [comment]
Hi @hjymandroid thank you for filing this issue. What is the version of Authenticator you installed? And could you attached the verbose level of adal logs? Thanks.

**Comment by hjymandroid** [comment]
I think it is 6.1.4 of Authenticator, however I am not able to recover the bug scenarios to reproduce it, and can't provide with the logs, if we see it again, I will let you know.

**Comment by nazukj** [comment]
Thanks for reporting the issue. Please reopen the issue with logs when you see it again. Thanks!

**Comment by weijjia** [comment]
@hjymandroid ADAL will not need GET_ACCOUNTS permission with 1.12 and the latest version of Authenticator. I guess you were using an old version of the Authenticator, when you reset it, you updated to the latest version which has the service support to remove the need for the permission.
