### ISSUE TITLE
Getting MainAxgetToken: Prompt is not allowed and failed to get token in Android 7.1 devices

### ISSUE THREAD

**Issue by ramprasad1477** [AzureAD/azure-activedirectory-library-for-android#829]
Hi,

We are getting the error "MainAxgetToken: Prompt is not allowed and failed to get token" after entering the user credential and failed to get the token in both Android 7.1 device and Emulator. Could you please look into this and let me know the solution..Thanks in advance..

**Comment by heidijinxujia** [comment]
Hi @ramprasad1477 Thank you for filing the issue. The error "Prompt is not allowed and failed to get token" is thrown when you are trying to make a silent auth call and it fails to get the AT from the cache. Could you send me the ADAL verbose level logs / repro steps for me to triage the issue?

**Comment by heidijinxujia** [comment]
@ramprasad1477 Hi, any update on the logs?

**Comment by ramprasad1477** [comment]
Hi, 
Thanks for the support and please find the attached log below. 

05-11 11:20:06.921 8137-8187/micro.mics V/PRNGFixes: 2017-05-11 16:20:06-ee0860d6-7630-48d9-bb78-40dd5b2969d5-No need to apply the fix ver:1.12.0

05-11 11:20:06.922 8137-8187/micro.mics V/PRNGFixes: 2017-05-11 16:20:06-ee0860d6-7630-48d9-bb78-40dd5b2969d5-No need to apply the fix ver:1.12.0

05-11 11:20:06.929 8137-8187/micro.mics V/AuthenticationContext: 2017-05-11 16:20:06-ee0860d6-7630-48d9-bb78-40dd5b2969d5-Broker redirectUri:msauth://micro.mics/9DlLI%2FfvqCapQN58ZYNYYwwDJN8%3D packagename:micro.mics signatureDigest:9DlLI/fvqCapQN58ZYNYYwwDJN8= ver:1.12.0

05-11 11:20:06.930 8137-8187/micro.mics V/BrokerProxy: 2017-05-11 16:20:06-ee0860d6-7630-48d9-bb78-40dd5b2969d5-Misused of the checking function. This is function is only used to checking the broker permissions of API 22 or less. ver:1.12.0

05-11 11:20:06.933 8137-8187/micro.mics V/AcquireTokenRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Sending async task from thread:8187 ver:1.12.0

05-11 11:20:06.935 8137-8249/micro.mics V/AcquireTokenRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Running task in thread:8249 ver:1.12.0

05-11 11:20:06.944 8137-8249/micro.mics V/AuthenticationContext: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Broker redirectUri:msauth://micro.mics/9DlLI%2FfvqCapQN58ZYNYYwwDJN8%3D packagename:micro.mics signatureDigest:9DlLI/fvqCapQN58ZYNYYwwDJN8= ver:1.12.0

05-11 11:20:06.947 8137-8249/micro.mics V/AcquireTokenRequest:verifyBrokerRedirectUri: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-The broker redirect URI is valid: msauth://micro.mics/9DlLI%2FfvqCapQN58ZYNYYwwDJN8%3D ver:1.12.0

05-11 11:20:06.948 8137-8249/micro.mics V/AcquireTokenRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Try to acquire token silently, return valid AT or use RT in the cache. ver:1.12.0

05-11 11:20:06.949 8137-8249/micro.mics V/AcquireTokenRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Try to silently get token from local cache. ver:1.12.0

05-11 11:20:06.955 8137-8249/micro.mics V/TokenCacheAccessor: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-No access token exists. ver:1.12.0

05-11 11:20:06.957 8137-8249/micro.mics V/AcquireTokenSilentHandler: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-No valid access token exists, try with refresh token. ver:1.12.0

05-11 11:20:06.959 8137-8249/micro.mics V/AcquireTokenSilentHandler: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Regular token cache entry does not exist, try with MRRT. ver:1.12.0

05-11 11:20:06.961 8137-8249/micro.mics V/AcquireTokenSilentHandler: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-MRRT token does not exist, try with FRT ver:1.12.0

05-11 11:20:06.965 8137-8249/micro.mics V/AcquireTokenSilentHandler: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-FRT cache item does not exist, fall back to try MRRT. ver:1.12.0

05-11 11:20:06.966 8137-8249/micro.mics V/AcquireTokenSilentHandler: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Send request to use MRRT for new AT. ver:1.12.0

05-11 11:20:06.968 8137-8249/micro.mics V/AcquireTokenSilentHandler: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-MRRT does not exist, cannot proceed with MRRT for new AT. ver:1.12.0

05-11 11:20:06.975 8137-8249/micro.mics D/AcquireTokenRequest: Cannot get AT from local cache, switch to Broker for auth, clear tokens from local cache for the user.

05-11 11:20:06.977 8137-8249/micro.mics V/AcquireTokenRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-No token items need to be deleted for the user. ver:1.12.0

05-11 11:20:06.981 8137-8249/micro.mics I/AcquireTokenWithBrokerRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Broker app is: com.azure.authenticator;Broker app version: VersionName=6.1.4;VersonCode=79. ver:1.12.0 

05-11 11:20:06.982 8137-8249/micro.mics V/AcquireTokenWithBrokerRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-User is not specified, skipping background(silent) token request ver:1.12.0

05-11 11:20:06.983 8137-8249/micro.mics D/AcquireTokenRequest: Trying to acquire token interactively.

05-11 11:20:06.986 8137-8249/micro.mics V/AuthenticationContext: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Put waiting request: 220792015 CorrelationId: 94362ede-267f-4eb6-8dca-1366688edf88 ver:1.12.0

05-11 11:20:06.993 8137-8249/micro.mics V/AcquireTokenRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Launch activity for interactive authentication via broker with callback: 220792015 ver:1.12.0

05-11 11:20:06.995 8137-8249/micro.mics V/AcquireTokenWithBrokerRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Launch activity for interactive authentication via broker. ver:1.12.0

05-11 11:20:06.999 8137-8249/micro.mics I/AcquireTokenWithBrokerRequest: 2017-05-11 16:20:06-94362ede-267f-4eb6-8dca-1366688edf88-Broker app is: com.azure.authenticator;Broker app version: VersionName=6.1.4;VersonCode=79. ver:1.12.0 

05-11 11:20:07.005 8137-8249/micro.mics V/BrokerAccountServiceHandler: 2017-05-11 16:20:07-94362ede-267f-4eb6-8dca-1366688edf88-Binding to BrokerAccountService for caller uid: 10191 ver:1.12.0

05-11 11:20:07.458 8137-8137/micro.mics V/BrokerAccountServiceHandler: 2017-05-11 16:20:07-94362ede-267f-4eb6-8dca-1366688edf88-Broker Account service is connected. ver:1.12.0

05-11 11:20:07.576 8137-8137/micro.mics V/MainAx: getToken Error:Refresh token is failed and **prompt is not allowed**

**Please do the needful..Thanks**

**Comment by ramprasad1477** [comment]
Hi,
Any solution or ideas to resolve this..Thanks

**Comment by heidijinxujia** [comment]
Hi @ramprasad1477  It seems the Authentication is involved to do the interactive auth. Could you send me the broker logs or any correlationID? So that we could see if the login is succeed at the beginning.

**Comment by heidijinxujia** [comment]
What's the version of the Authenticator?

**Comment by heidijinxujia** [comment]
Checked Kusto with correlationID 94362ede-267f-4eb6-8dca-1366688edf88, no records found.

**Comment by heidijinxujia** [comment]
Haven't heard from the customer for 18 days. Please reopen this issue when getting the broker logs or encounter this issue again. Thanks.

**Comment by harshil93** [comment]
Hi, 

I am not able to use Outlook on my OnePlus 5. I seem to face the same error. The authenticator prompt is not coming up for any of the Office365 application. My email id is @microsoft.com 

This happens only when Authenticator app is installed. If I uninstall the authenticator app, the browser prompt for 2FA comes up and it works.
