### ISSUE TITLE
Consider using Moshi instead of Gson

### ISSUE THREAD

**Issue by jaredsburrows** [AzureAD/azure-activedirectory-library-for-android#840]
- Moshi has lower method count
  - Moshi: http://www.methodscount.com/?lib=com.squareup.moshi%3Amoshi%3A1.5.0 (exclude okio)
  - Gson: http://www.methodscount.com/?lib=com.google.code.gson%3Agson%3A2.8.0
- Moshi is just as fast/faster
  - http://blog.takipi.com/the-ultimate-json-library-json-simple-vs-gson-vs-jackson-vs-json/
  - https://github.com/fabienrenaud/java-json-benchmark

**Comment by jaredsburrows** [comment]
I can make a PR for this.

**Comment by nazukj** [comment]
From Ashish:
Internal partners have dependencies that rely on a GSON serialized blob being returned from ADAL. That GSON serialized blob is passed back into another app which passes it to its own ADAL to read into the cache. At this time we are unable to accept this suggestion.

**Comment by jaredsburrows** [comment]
@nazukj Thanks for the reply. I believe you responded with a similar response via email. The serialized blob is JSON, correct? Both GSON and Moshi serialize and deserialize JSON.
