### ISSUE TITLE
DEVICE_INTERNET_IS_NOT_AVAILABLE is not used

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/azure-activedirectory-library-for-android#846]
This ADALError is never used in code. Consider removing from `ADALError.java`

**Comment by iambmelt** [comment]
As an FYI, this change touches a `public enum` - if any customers are using this field they will experience a break.

/cc @nazukj @danieldobalian

**Comment by danieldobalian** [comment]
In that case, I'm fine closing this.

**Comment by iambmelt** [comment]
@danieldobalian I _highly_ doubt any customer would be switching around an error that the library itself doesn't use. I've submitted a PR (#996) to close this issue. We can see what @heidijinxujia and @addev-ashish think in CR

**Comment by nazukj** [comment]
Wont Fix
