### ISSUE TITLE
Explore ways to prevent an app from sending multiple interactive requests at the same time

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#849]
If and app sends multiple interactive requests at the same time to ADAL we should error out. 

The issue here is if a MFA is required, the user will see multiple quick flashes and the call may or maynot resolve the MFA prompt.

**Comment by nazukj** [comment]
This is already fixed for calls coming from same process. Investigate ways to do this for different processes.

**Comment by addev-ashish** [comment]
Closing this, we are revisiting our threading model.
