### ISSUE TITLE
Add Doze Awareness Network Checking - add new exception type

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/azure-activedirectory-library-for-android#870]
The network requests will be deferred when the device is in doze mode. Doze and App Standby are two power-saving features introduced by Android from Android 6.0. These two features defer background network activity for apps when the device/app is unused for long periods of time. That’s for device with Android 6.0+, when Doze and App Standby are enabled, background auth will fail because of no network connection. 

Currently network checking function HttpWebRequest.throwIfNetworkNotAvailable() does not have doze mode support. The proposed solution is to add isDeviceIdleMode() and isIgnoringBatteryOptimizations(packagename) should be added into the network check when the device is under Android 23 or above.

**Comment by iambmelt** [comment]
Useful documentation regarding [adapting applications for Doze](https://developer.android.com/training/monitoring-device-state/doze-standby.html)

**Comment by addev-ashish** [comment]
Change to plan, we should detect doze mode and throw a different network error if doze mode is on.
