### ISSUE TITLE
Update Readme to provide guidance to partners on handling doze mode

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#871]
When ADAL starts returning a new error message for doze mode, we should update the readme so that any partner using ADAL can handle doze mode correctly.
We also need to add a section about partners refreshing token in the background, and how they should check doze mode before calling ADAL.

**Comment by nazukj** [comment]
@heidijinxujia please work with @addev-ashish on this. thanks!

**Comment by weijjia** [comment]
Wiki page is created for handling doze mode https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Handle-Doze-and-App-Standby
