### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by dchdch1234** [AzureAD/azure-activedirectory-library-for-android#875]
```
AcquireTokenRequest:2017-06-07 22:04:19-af8a8143-8f68-49b4-b019-17f0ccc33d7f-Error info:Code:-11 primary error: 3 certificate: Issued to: CN=adfs.dssmith.com,OU=IT,O=DS Smith PLC,L=London,ST=London,C=GB;
                                                                                     Issued by: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US;
                                                                                      on URL: https://adfs.dssmith.com/adfs/ls/?login_hint=...
```

Checked android doc, error 3 means certificate is not trusted. But there is no error when open https://adfs.dssmith.com/adfs/ls/ with Chrome on the same device. So maybe it's related to WebView.

As shown in https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html, google begins to block OAuth request made from WebView. Maybe ADAL should also move from using webview to use browser.

**Comment by addev-ashish** [comment]
@dchdch1234 did you try the steps here https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/SSL-Certificate-Validation-Issue

**Comment by dchdch1234** [comment]
yes, I tried that. It cannot fix the issue. I have an email address which can be used to reproduce the issue, but I don't have a private way to send to you.

**Comment by nazukj** [comment]
Can you please provide us with detailed logs with user agent string we can investigate futher

**Comment by nazukj** [comment]
Closing issue due to lack of information for investigation. Please re-open if issue still persists with appropriate information. thanks!
