### ISSUE TITLE
userappwithbroker not working in dev branch

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#878]
I just tried to install the userappwithbroker from current branch, and get this error `java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@69e6b6f does not exist`. Then I tried on our release branch, everything works fine. So I'm wondering if there is anyone else encountering the same error. If so, then there must be something break the current code.

**Comment by heidijinxujia** [comment]
Turns out this line broke the build `testCoverageEnabled true` 
Everything works fine when comment it out.
