### ISSUE TITLE
Broker Auth for non joined account fails on both Android O and Android N devices.

### ISSUE THREAD

**Issue by piqiums** [AzureAD/azure-activedirectory-library-for-android#886]
When I was trying to walk thru the test cases, it failed to pass the test case "FoCI: Broker Auth For Non-Joined Account (Multi-users)"  on both Android O and Android N devices.
After adding another account(user B) in OneDrive, then clear webview cookie, and it failed in step 8, while trying to add user B to Word, there's a dialog, " can't add another OneDrive account ", "Sorry, another account from your organization is already signed in on this device. To use a different account, go to Settings and reset Office".

**Comment by titorodi** [comment]
Is this MAM or OneDrive related?

**Comment by piqiums** [comment]
the test cases is related with OneDrive and Word.

**Comment by addev-ashish** [comment]
Word does not support 2 users from the same tenant/domain. The test case needs to be updated to make sure userB is a user from another tenant.
