### ISSUE TITLE
How to logout in broker based authentication

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [AzureAD/azure-activedirectory-library-for-android#887]
Hi Team,

Thanks for the great library.
In our application, we have a requirement that user should be logout and after logout user should enter credentials for login. We are using broker based authentication.
We are not able to find out anyway by which user can log out.

Please suggest.

Kind Regards,
Durgaprasad

**Comment by addev-ashish** [comment]
Hi @Durgaprasad-Budhwani 
While using broker, the credentials for the user are managed by the broker app for that device. So signing out effectively means the user gets signed out of every app on the device. 
If the user actually wants to signout of the device they should go to the broker app and remove the account.

Hope this helps. If not, kindly explain your scenario in more details and maybe we can come up with some options that fit your need.

Ashish
