### ISSUE TITLE
Android O: Many instances of 'android.os.Message' were leaked in the stress test.

### ISSUE THREAD

**Issue by piqiums** [AzureAD/azure-activedirectory-library-for-android#888]
when I was running the stress test following the instructions, I found the allocated memory was increasing all the way. I dumped the hprof files and found there's a memory leak. In one of the hprof files, there're more than 180,000 instances of 'android.os.Message' (each take a 616 bytes) in handler's MessageQueue of the userappwithbroker's MainActivity.
   Please check the 
![leak_sc](https://user-images.githubusercontent.com/29104968/27935584-bfefd894-6260-11e7-978f-24886555aa26.png)

![leak_callback_sc](https://user-images.githubusercontent.com/29104968/27935622-0a0728ce-6261-11e7-80fc-7e734b671b39.png)

   Since the hprof file is too big to attach it here. Please talk to me to get a copy.

**Comment by piqiums** [comment]
this happens on all Android versions. It's not an Android O specific issue.

**Comment by piqiums** [comment]
I've found the solution to fix the mem leak. After running the stress test for 8 hours, it could prove that the leak is gone. I will post the PR next week.

![leak_too_many_handlers](https://user-images.githubusercontent.com/29104968/27974048-18f983a8-6311-11e7-8986-64f16e2cfa9a.png)
![leak_gone_after_code_change](https://user-images.githubusercontent.com/29104968/27974050-1c95b464-6311-11e7-8394-177bfd881f28.png)

**Comment by heidijinxujia** [comment]
Related to issue#824

**Comment by softmarshmallow** [comment]
having the exact same problem.. T T
how did you solve this???
