### ISSUE TITLE
Outlook: ADAL should return different error message when communcation with broker fails

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#901]
When broker auth is involved, if the broker returns null or an error happens communicating with broker ADAL falls back to returning AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED. 
This makes the apps think that auth failed, and they take the users to the UI breaking the SSO experience.

**Comment by piqiums** [comment]
looking into this.
Ashish, do you know the steps to repro it? thanks

**Comment by heidijinxujia** [comment]
#973

**Comment by nazukj** [comment]
@heidijinxujia if this is fixed and merged, can you please close this issue?
