### ISSUE TITLE
On M+ devices, always logging that we are doing a 'misused' checking for broker permissions - string update

### ISSUE THREAD

**Issue by titorodi** [AzureAD/azure-activedirectory-library-for-android#904]
We have a superfluous and distracting log message

BrokerProxy:2017-06-19 17:12:17-f825cd9d-a210-4d42-bcd2-8f7f0e569af2-Misused of the checking function. This is function is only used to checking the broker permissions of API 22 or less. ver:1.12.0 (null) - null

<ul>
  <li>Only see a broker permission message error if applicable</li>
  <li>On M or greater devices, always see the above log message.</li>
  <li>Do ADAL Broker Auth on an M or greater device.</li>
  <li>ADAL 1.12.0</li>
  <li>Relevant logs and traces</li>
</ul>

<b>Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.</b>

For <b>privacy/security</b> issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>

**Comment by weijjia** [comment]
Merged with PR #963
