### ISSUE TITLE
AcquireToken telemetry sometimes returns AUTH_FAILED_NO_TOKEN

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#905]
We need to validate if this is a real customer scenario or bug in telemetry where AcquireToken call returns auth_failed_no_token

**Comment by iambmelt** [comment]
Occurrences of `AUTH_FAILED_NO_TOKEN` in ADAL codebase.

![capture](https://user-images.githubusercontent.com/990063/28382571-8e19e0f4-6c8c-11e7-9a84-e8a2d65094e5.PNG)

**Comment by iambmelt** [comment]
Currently verifying Kusto query.... will post back.

**Comment by iambmelt** [comment]
Kusto query indicates this error is possible from [`EventStrings#L168`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/telemetry/java/com/microsoft/aad/adal/EventStrings.java#L168) AKA [`AuthenticationContext.java#L415-L434`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L415-L434)

The code path which makes this possible is absurdly complex:

#### AuthenticationContext.java
```java
public void acquireToken(Activity activity, String resource, String clientId,
                             @Nullable String redirectUri, @Nullable String loginHint, @Nullable PromptBehavior prompt,
                             @Nullable String extraQueryParameters, AuthenticationCallback<AuthenticationResult> callback)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L432)
#### AcquireTokenRequest.java
```java
    void acquireToken(final IWindowComponent activity, final boolean useDialog, final AuthenticationRequest authRequest,
                      final AuthenticationCallback<AuthenticationResult> authenticationCallback)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L109)
```java
    private void performAcquireTokenRequest(final CallbackHandler callbackHandle,
                                            final IWindowComponent activity,
                                            final boolean useDialog,
                                            final AuthenticationRequest authenticationRequest)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L273)
```java
private AuthenticationResult tryAcquireTokenSilent(final AuthenticationRequest authenticationRequest)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L293)
```java
private AuthenticationResult acquireTokenSilentFlow(final AuthenticationRequest authenticationRequest)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L337)
```java
private AuthenticationResult tryAcquireTokenSilentLocally(final AuthenticationRequest authenticationRequest)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L373)
#### AcquireTokenSilentHandler.java
```java
AuthenticationResult getAccessToken() throws AuthenticationException
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenSilentHandler.java#L104)
```java
private AuthenticationResult tryRT() throws AuthenticationException
```
has multiple code paths to:
```java
private AuthenticationResult acquireTokenWithCachedItem(final TokenCacheItem cachedItem)
```
[invokes](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenSilentHandler.java#L302)
```java
AuthenticationResult acquireTokenWithRefreshToken(final String refreshToken) 
```
which `throws`
[`AUTH_FAILED_NO_TOKEN`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d286d7b745d0cb99d5a93d97075a4a87821bc8af/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenSilentHandler.java#L144-L155)

**Comment by iambmelt** [comment]
In a nutshell, an AT call is made that tries to acquire a token silently using an RT but fails with either a `ServerRespondingWithRetryableException` or `IOException | AuthenticationException`

**Comment by nazukj** [comment]
Could be related to doze mode. Should monitor this and reopen issue if this is not fixed with Doze Mode fix.
