### ISSUE TITLE
High number of DEVICE_CONNECTION_IS_NOT_AVAILABLE errors

### ISSUE THREAD

**Issue by GauravMahajanMicrosoft** [AzureAD/azure-activedirectory-library-for-android#907]
In our user[PROD] telemetry , we see a lot of errors with AdalCode: [DEVICE_CONNECTION_IS_NOT_AVAILABLE] and Message: Connection is not available to refresh token. What does this error represent?

We use https://github.com/AzureAD/azure-activedirectory-library-for-cordova v0.10.0. It uses version 1.10.0 for azure-activedirectory-library-for-android

Also, this telemetry is across multiple android versions and devices.

**Comment by iambmelt** [comment]
Hi @GauravMahajanMicrosoft 

You are likely seeing [this check for network connectivity](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/44d368d4707cabdfab3f79911e9ffc7f2bb6619a/adal/src/main/java/com/microsoft/aad/adal/HttpWebRequest.java#L171-L182) trigger an `AuthenticationException`.

Our check, used to determine network availability, uses the the [DefaultConnectionService](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/DefaultConnectionService.java) to [probe ](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/DefaultConnectionService.java#L45-L48)the Android system [ConnectivityManager](https://developer.android.com/reference/android/net/ConnectivityManager.html) -- this check allows us to fail-fast when doing actions which rely upon network connectivity; actions such as refreshing tokens.

The reasons a device may lack a stable network connection are numerous: a device may not have cellular service; a wifi connection might be down, weak, or unstable; a user's data-plan might be exhausted; a user's device may be in a [low-power mode](https://developer.android.com/training/monitoring-device-state/doze-standby.html) (we're working on adding more visibility into this [here](https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/891).

Applications with sufficiently large user bases are bound to see this issue, likely in varying numbers depending on user locale, availability/quality of networking infrastructure, usage scenarios, and device operating conditions.

Bearing this in mind, I would advise investigating your telemetry data to determine a few things:
 - Does the amount of telemetry you get around this condition, relative to the size of your user base, indicate suspicious or troublesome behavior on the part of the SDK?
- Is the error distributed evenly or unevenly over device types, users, and versions?
- Are you seeing accompanying or related errors reported in your telemetry which you believe are indicative of a bug in the SDK?

If you're able to identify an issue or bug you would like to see addressed, I'd encourage you to open a separate issue identifying the problem referencing this issue if it provides additional context.

**Comment by anuj-mehta** [comment]
Hello Brian,

based on your suggestion, we added a check to verify device connectivity status in our telemetry. 
In the majority of cases, we see that device has network connectivity but we still get this error.

Any ideas as per what is going on here?

Thanks

Anuj

**Comment by iambmelt** [comment]
Hi @anuj-mehta - I'll reopen this issue to give us a place to investigate.

A detailed description of the behavior you're seeing + logs and telemetry would help us move this forward. Additionally, code examples of ADAL's usage + any network detection code wrapped around it would also be helpful in diagnosing and troubleshooting this issue.

As a friendly reminder; please exercise caution and discretion to ensure that no OII, PII, or credentials are posted when providing telemetry, logs, or otherwise.

**Comment by nazukj** [comment]
@anuj-mehta  @GauravMahajanMicrosoft  Please provide us with the logs as requested. Thanks!

**Comment by nazukj** [comment]
Closing issue. Please reopen if it still reproes with appropriate logs. Thanks!
