### ISSUE TITLE
too much memory retained by Telemetry.mEventTracking while running the stress test

### ISSUE THREAD

**Issue by piqiums** [AzureAD/azure-activedirectory-library-for-android#908]
While running stress tests, I found most of the memory are retained by Telemetry.mEventTracking. In this way it often leads to OutOfMemoryError, and fails the stress test.
   Please find a solution to mitigate this.

**Comment by iambmelt** [comment]
@piqiums Did you happen to run similar tests over MSAL? Do you know if a similar problems exists over there?

**Comment by piqiums** [comment]
@iambmelt I didn't run stress test over MSAL. So I don't know that.
