### ISSUE TITLE
login.windows.net authority migration to login.microsoftonline.com

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#913]
<ul>
  <li>There currently are a number of DNS aliases and redirects used for EvoSTS, all of which currently redirect to login.microsoftonline.com, we're looking to migrate all of these islands into a single source of tokens to eliminate this source of extra authentication prompts. </li>
  <li>The same tokens are issued for all the aliased authority URLs, however client SDKs currently don't have visibility into this aliasing behavior and use the original authority URL provided by the client application for caching tokens, client applications can receive these authorities from a multitude of sources creating islands of tokens when different sources provide different authorities, even though they are equivalent tokens. This results in multiple auth prompts, possibly within the same app, and "islands of SSO"
 effects when multiple apps are involved.</li>
</ul>

**Comment by iambmelt** [comment]
@weijjia Now that #956 #977 and #974 are merged, are we clear to close this issue?

**Comment by weijjia** [comment]
PRs are merged, closed the issue.
