### ISSUE TITLE
improve the code coverage of StorageHelper class

### ISSUE THREAD

**Issue by piqiums** [AzureAD/azure-activedirectory-library-for-android#922]
![storagehelper_coverage_before](https://user-images.githubusercontent.com/29104968/28645230-9c5a4afc-7211-11e7-8e68-2d78bef4a1e4.png)

**Comment by piqiums** [comment]
![storagehelper_coverage_after](https://user-images.githubusercontent.com/29104968/28645740-8ab2c94e-7213-11e7-85fe-c36e2765c6b7.png)

**Comment by iambmelt** [comment]
Closed by #923
