### ISSUE TITLE
[Android] ExpiresOn.getTime() in AuthenticationResult is returning NaN

### ISSUE THREAD

**Issue by GauravMahajanMicrosoft** [AzureAD/azure-activedirectory-library-for-android#927]
### Issue Description
A lot of our customer logs who are not able to login, we see that the expiresOn.getTime is NaN. 

### Repro Environment Details
1. Installed plugin version:  1.10.0
2. Target Platform: Android

**Comment by iambmelt** [comment]
Hi @GauravMahajanMicrosoft Are you able to capture a Fiddler trace with this behavior? Any additional information you could provide around this issue would be helpful (device info, logs, etc.)

**Comment by GauravMahajanMicrosoft** [comment]
We do not have a repro yet but it constitutes 6000errors/day (around 20% of all errors). We do not log the verbose level of Native logs and no error log was logged by the android library. We log the Date.now().getTime() and it evaluated to 1501106663476 when we logged the error. We acquired the token around 5 min of that time.

**Comment by GauravMahajanMicrosoft** [comment]
Observations:
1. I was never able to reproduce this.
2. The users who see this issue, are blocked. Because this reproes for them 100% of the time. Could imply this is device specific
3. Looks like Date.getTime() gives you NaN when the Date object is not able to parse the time. For ex:
var date = "2014-07-23T15:23:12+0000";
var ts = new Date(date).getTime();
ts would be NaN on IE but would work fine on Chrome.

**Comment by GauravMahajanMicrosoft** [comment]
These are the numbers for 2 days:

	Android OS version	count
	5.1	          256
	5.1.1	          542
	5.0.1	          21
	6.0.1	         48
	7.1.1	         14
	5.0	        135
	5.0.2	        128
	6.0	         4
	7.0	        55

**Comment by iambmelt** [comment]
Issue is now tracked via IcM
