### ISSUE TITLE
Distinguish between various silent refresh reasons

### ISSUE THREAD

**Issue by GauravMahajanMicrosoft** [AzureAD/azure-activedirectory-library-for-android#929]
We see a lot of AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED in our telemetry. How can we distinguish between these three error reasons?

1. Refresh token exists and refresh failed.
2. Refresh token exists but is expired/invalid.
3. No tokens exist.

**Comment by iambmelt** [comment]
Hi Gaurav - To provide you the best possible answer, I'll need to understand your question a little better.

Are you seeking clarity as to what these error cases mean? Instructions as to how you might differentiate them using Kusto?

**Comment by gomahajan** [comment]
I am looking for instructions as to how to differentiate them using Kusto. It is not possible right now because all the error cases use the same ADAL_CODE = AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED

**Comment by iambmelt** [comment]
For help with Kusto queries related to ADAL telemetry, please follow-up with me over corpmail. Feel free to /CC @addev-ashish -- we work together on telemetry 😄
