### ISSUE TITLE
Using RedirectUri for Authentication Broker

### ISSUE THREAD

**Issue by GauravMahajanMicrosoft** [AzureAD/azure-activedirectory-library-for-android#935]
We are trying to use authenticator for our authentication and instead of manually creating the redirect uri using the  brokerRedirectPrint.ps1, we are using mContext.getBrokerRedirectUri. However, mContext.getBrokerRedirectUri changes everytime we build the app even if we are not changing the certificate. Is that expected?

**Comment by GauravMahajanMicrosoft** [comment]
Also, I tried building the app using the same certificate on different machines and they all generated different redirecturi. That implies that every time I build the app using a different machine, I need to whitelist the new redirectUri. Is this expected too?

**Comment by iambmelt** [comment]
Hi Gaurav - at a glance this appears to be an issue in the `*.ps1` script; I'll defer a more detailed answer to @weijjia, who I suspect may know more about this setup

**Comment by GauravMahajanMicrosoft** [comment]
Hey, sorry for the scare. We finally figured out to this being a complex certificate issue in our build servers. Does not look like a bug in your code now. Closing the bug. Thanks!

**Comment by iambmelt** [comment]
Glad to hear your got it figured out - thanks for the update 👍
