### ISSUE TITLE
Federated user get stuck in endless redirect

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#946]
Start userappwithbroker, enter the microsoft username, you will be stuck with either a spinner or bought right back to the login page.

**Comment by addev-ashish** [comment]
#949

**Comment by addev-ashish** [comment]
Issue fixed in 1.13.1

**Comment by nazukj** [comment]
@weijjia please add comments, associate with PR and close. thanks!

**Comment by weijjia** [comment]
cache fix has been reverted with PR #949
