### ISSUE TITLE
Empty idToken when using authenticator and acquireTokenSilentAsync 

### ISSUE THREAD

**Issue by GauravMahajanMicrosoft** [AzureAD/azure-activedirectory-library-for-android#951]
When using the authenticator on android, the result returned on acquireTokenAsync has idToken but the result returned on **acquireTokenSilentAsync has empty string as idToken**. It is a 100% repro on version 1.10.0 for azure-activedirectory-library-for-android

**Comment by nazukj** [comment]
@GauravMahajanMicrosoft  can you please update to latest version of ADAL (1.13.1) and provide detailed logs with the error? Thanks!

**Comment by iambmelt** [comment]
Not to investigating dev: may pertain to [BrokerProxy#L475](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/BrokerProxy.java#L475-L476)

**Comment by GauravMahajanMicrosoft** [comment]
@nazukj Thanks for looking at it. I just wanted to clarify that from the adal perspective this is not an error, so there are no logs. The acquireTokenAsync succeeds but returns an empty string for the idToken.

@anuj-mehta can you look at updating the android library to 1.13.1 and see if we still repro this.

**Comment by nazukj** [comment]
Closing issue since there has been no update. Please reopen if this still repros after update to latest
