### ISSUE TITLE
Verify use of thread-safe data structures is consistent

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#978]
Per discussion w/ @GTValentine -- `Telemetry.java` tracks `Events` using a `ConcurrentHashMap` but `*Events` themselves are backed by non-threadsafe `ArrayList`.

Investigate whether or not this inconsistency is cause for concern and evaluate what changes must be made to provide a consistently threadsafe and performant execution environment.

This hasn't yet raised any issues and this investigation can be considered preventative.

**Comment by iambmelt** [comment]
This issue is probably `p2` or `p3` - priority pending next triage

/cc @addev-ashish @nazukj

**Comment by nazukj** [comment]
Given our OM, we will not run into this issue.
