### ISSUE TITLE
Add a wiki page for SSL validation issue when the cert chain required extra download

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#980]
Add how to detect this condition and a link to https://support.microsoft.com/en-us/help/3203929/using-adal-to-authenticate-from-android-devices-fails-if-additional-certificate-downloads-are-required

**Comment by nazukj** [comment]
@addev-ashish to close with comments

**Comment by addev-ashish** [comment]
wiki added https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/SSL-Certificate-Validation-Issue-%232
