### ISSUE TITLE
Outlook app unable to load email after user enrolled device using company portal

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#993]
Originally reported via email
```
After the user enroll to Intune with company portal, the user switches back to the Outlook app.  The Outlook app kept loading (Note: the expectation at this point is that Outlook app should access to user’s email).
It looks like the Outlook app on Android didn’t get the token after user’s enroll to Intune using Company Portal.

See below screenshots

Repro steps:
1.	Launch Outlook app on Android device.
2.	Sign in
3.	Enroll (by download company portal and sign in company portal)
4.	Device compliant
5.	Go back to Outlook app.

Expected: user able to see/access mails.

Actual: Outlook app kept loading (Please see attachment).  It will failed loading eventually.  User has to sign in again to be able to see mails.
```

![image](https://user-images.githubusercontent.com/990063/31632740-11349110-b28c-11e7-9a97-eaf05243a854.png)

![1_edit](https://user-images.githubusercontent.com/990063/31633622-018afdaa-b28f-11e7-9abd-4cc7c16d9b86.jpg)

![2_edit](https://user-images.githubusercontent.com/990063/31633631-04d43940-b28f-11e7-9d44-95c6dc152080.jpg)

![3_edit](https://user-images.githubusercontent.com/990063/31633636-0937b9ee-b28f-11e7-99f8-cb5f6933a21b.jpg)

![4_edit](https://user-images.githubusercontent.com/990063/31633639-0cadfdae-b28f-11e7-8a52-f28e0cf18d13.jpg)

![6](https://user-images.githubusercontent.com/990063/31633643-0f6be704-b28f-11e7-9d33-c8c8093392fb.png)

![7](https://user-images.githubusercontent.com/990063/31633648-12e07f12-b28f-11e7-86f7-9af3b8d3970f.png)

![8_edit](https://user-images.githubusercontent.com/990063/31633657-18926f9c-b28f-11e7-9d7e-0a850b0c0c81.jpg)

![9_edit](https://user-images.githubusercontent.com/990063/31633658-1c3f935e-b28f-11e7-9c91-aacbe14d50ea.jpg)

![10_edit](https://user-images.githubusercontent.com/990063/31633663-1fef5818-b28f-11e7-9682-b1b0931badec.jpg)

![11_edit](https://user-images.githubusercontent.com/990063/31633667-239c6032-b28f-11e7-9bf0-95c0dc0bf18b.jpg)

![12_edit](https://user-images.githubusercontent.com/990063/31633671-26de1178-b28f-11e7-830f-8e6b197366c6.jpg)

![13_edit](https://user-images.githubusercontent.com/990063/31633674-2a29b6f2-b28f-11e7-81ee-e07c9f60cec5.jpg)

![14](https://user-images.githubusercontent.com/990063/31633680-2d3ba576-b28f-11e7-9ac6-3c1b29045085.png)

![15_edit](https://user-images.githubusercontent.com/990063/31633686-30292998-b28f-11e7-9e5d-ce0df8fd832b.jpg)

![16_edit](https://user-images.githubusercontent.com/990063/31633696-34a1df88-b28f-11e7-973b-94a23bdcc0e1.jpg)

![17](https://user-images.githubusercontent.com/990063/31633700-37890ac8-b28f-11e7-940c-0f9dc8b1e5a8.png)

**Comment by nazukj** [comment]
@iambmelt please close this out with comments as discussed

**Comment by iambmelt** [comment]
Per follow up with test:
Recurrence of issue appears to be device specifc - repros possible on devices running `5.1.1`, Outlook version: `2.2.31`, Company Portal version: `5.0.3845.0`

Devices used in repro:
- Motorola 'G' (XT-1032)
- Galaxy Note Tab (SM-P600)

Device used in ADAL-team test (does not repro)
- Motorola Nexus 6 (Flashed @ `5.1.1`)

As issue appears device-specific, investigation has been turned over to Outlook team. Will reopen if ADAL team is reinvolved.
